### ISSUE TITLE
Unclear error message: "Clang failed with error 1"

### ISSUE THREAD

**Issue by ikirill** [Sarcasm/irony-mode#119]
When editing c++ with irony-mode on, I sometimes get messages of the form:

```
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:26:10 -
```

This is a very unclear error message. It doesn't tell me whether I have misconfigured something, or whether the error is expected.

I don't understand what causes this message (maybe it's incorrect syntax), so I can't suggest how to make it clearer.

**Comment by legends2k** [comment]
I'm affected by this issue too. Whenever I'm in `c++-mode` I see `company` and `Irony` in the modeline. However, I see no process by the name `irony-server.exe` running and I see two new buffers by the name `*clang-error*` and `*clang-output*` showing the `clang` output, clearly showing that the `company-clang` is the backend in action. However, I've both `company` and `company-irony` packages installed.

How should I make `company` choose `company-irony` over `company-clang`?

**Comment by Sarcasm** [comment]
You need to prepend company-irony to company-backends.

```el
(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))
```

If you used customize to customize company-backends, maybe you need to do this in the customize interface.

**Comment by legends2k** [comment]
Thanks it works now. I also see the irony-server running. The default `clang` backend has an additional feature of completing a function with it's parameters highlighted. It'll be good to have this feature in the irony backend, particularly when calling functions taking many parameters.

**Comment by Sarcasm** [comment]
install yasnippet maybe, irony-mode support only yasnippet for now.
