### ISSUE TITLE
ycmd

### ISSUE THREAD

**Issue by sevki** [Sarcasm/irony-mode#122]
Any thoughts about this? https://github.com/Valloric/ycmd

**Comment by agauniyal** [comment]
what about irony for vim users? Are there any plans to port it for vim? YCM does well and although it supports C family but is more of a generic type completer. and it lacks parameter completions as well.

**Comment by Sarcasm** [comment]
> what about irony for vim users? Are there any plans to port it for vim?

Nope. irony-server is pretty straightforward and only uses basic functionality of libclang. The rest is emacs-specific interaction with the process that will be different on vim. Nothing very interesting to re-use except libclang IMHO.
