### ISSUE TITLE
The include path in .clang_complete doesn't take effect

### ISSUE THREAD

**Issue by saintaugustinus** [Sarcasm/irony-mode#154]
I have set my include path in the .clang_complete file but it doesn't work
I cannot get the compilation of those functions which in my own headers

And when i want to load the .clang_complete i found that the .clang_complete doesn't show as candidate in the irony-cdb-menu command 
There just one option 'q' to choose while i aready put .clang_complete file in the directory.

My irony-mode version is 0.2.0-cvs2 
archlinux  emacs 24.4.1

**Comment by Sarcasm** [comment]
What happens if you call irony-cdb-autosetup-compile-options?

**Comment by saintaugustinus** [comment]
After run irony-cdb-autosetup-compile-options it works well.
Thank you!

**Comment by Sarcasm** [comment]
To have the compile options setup automatically when irony-mode is enabled you can do:

    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

This is shown in the Configuration section of the README, see here: https://github.com/Sarcasm/irony-mode#configuration

This is something that wasn't present in the previous release so that may be the reason you were confused.

**Comment by saintaugustinus** [comment]
I already notice that
Thank you!

**Comment by dzhwinter** [comment]
there is no irony-cdb-autosetup-compile-options function at all in release v0.1.2. I checked the irony-cdb.el thrid time, 
 how to solve it?
my irony-mode verison is v0.1.2 install by melpa

**Comment by Sarcasm** [comment]
Irony cdb isn't stable, if you want a stable interface you will have to use a .clang_complete.

**Comment by Sarcasm** [comment]
For reference, documentation to the old way: https://github.com/Sarcasm/irony-mode/tree/v0.1.2#compilation-database
