### ISSUE TITLE
Correct handling of libclang crashes

### ISSUE THREAD

**Issue by ikirill** [Sarcasm/irony-mode#157]
I stumbled on this bug by accident: http://llvm.org/bugs/show_bug.cgi?id=14017

When libclang crashes, it prints the "Assertion failed...", but doesn't actually crash, which confuses irony-mode, because it tries to parse the error message as a sexp, expecting a list, which leads to a failure in some unrelated function later on (`Wrong type argument: sequencep, Assertion`)

The output right after the error message is "nil\n\n;;EOT\n", which seems okay.

**Comment by Sarcasm** [comment]
This is indeed an issue, see #137.

Not sure yet how to deal with this properly.

Maybe see what `clang_toggleCrashRecovery()` does or detect that the answer we got was from a process that exited with errors.

**Comment by Sarcasm** [comment]
Wait, in your case the assertion failed but you have the process continued to run? That's more problematic in this case if Clang clutters the output with messages. :-/

**Comment by ikirill** [comment]
I found the bug in emacs, but I reproduced it running irony-server manually (`irony-server diagnostics FILE </dev/null`) under lldb, which is how I know it continues and prints `nil...`

**Comment by ikirill** [comment]
This can be fixed by redirecting stdout/stderr while libclang is parsing.

**Comment by Sarcasm** [comment]
Yep,
Not sure what is the best. I think redirecting libclang to the log file would be fine, irony-mode on the Emacs side should handle the rest nicely, i.e: company will time out.

**Comment by ikirill** [comment]
I'd say best is to redirect cerr to a stringstream (or stderr to a file, then read the file), then return a list `(error STRING)`, and explicitly check for the error the emacs-lisp function that reads process output, which should show a message and behave as if nil was returned.

**Comment by Sarcasm** [comment]
Should be fixed by 4cf02965007062006c5cdb141d0713d6591a4ed7.
