### ISSUE TITLE
Go to definition?

### ISSUE THREAD

**Issue by proofit404** [Sarcasm/irony-mode#161]
Is it possible to implement go to definition with `libclang`?

**Comment by Sarcasm** [comment]
Not really in a perfect way, see #152  and #153. Right now I'm opposed to "half-baked" solutions. Some kind of indexing is necessary to support cross-translation-unit jump to reference/definition/...

**Comment by proofit404** [comment]
So maybe its a task for something like `gnu globals`?

**Comment by Sarcasm** [comment]
GNU Globals is not good for C++. A libclang based indexer would be better, for example https://github.com/Andersbakken/rtags or one of the cited tools here: https://github.com/Sarcasm/irony-mode/issues/85#issuecomment-34978442

Right now my hopes are for the Google project Kythe (see http://llvm.org/devmtg/2014-10/#talk21) but I have no idea when or what it does. I'd like to think they will provide more information in the next few months, I may be wrong.

**Comment by proofit404** [comment]
Actually I doesn't write any `C++` code. I use `irony` for `C` programming only. Thanks for your answers!

**Comment by Sarcasm** [comment]
Great, so I think you will be fine with GNU Globals, I liked when I was working in `C` and the Emacs interface is not too bad.

**Comment by joca-bt** [comment]
Kythe's has arrived http://www.kythe.io/

**Comment by Sarcasm** [comment]
Yup, there is a long way to go though for now it seems. I'm reading slowly the documentation.

**Comment by vellamike** [comment]
Has there been any progress on this issue?

**Comment by Sarcasm** [comment]
None.

**Comment by vellamike** [comment]
Is there any way to get the ability to go to a function declaration/definition with C++ at the moment, perhaps using a different package? Or is it not really possible?

**Comment by Sarcasm** [comment]
Using `rtags` maybe? https://github.com/Andersbakken/rtags
