### ISSUE TITLE
Could NOT find LibClang (missing: LIBCLANG_LIBRARY LIBCLANG_INCLUDE_DIR)   

### ISSUE THREAD

**Issue by stephenry** [Sarcasm/irony-mode#167]
I am attempting to build the irony server. The command fails outright within Emacs and attempting to build manually from the command line, I receive the following error message:

-- C++11 compiler option(s): -std=c++11
CMake Error at /usr/local/Cellar/cmake/3.1.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find LibClang (missing: LIBCLANG_LIBRARY LIBCLANG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.1.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibClang.cmake:78 (find_package_handle_standard_args)
  src/CMakeLists.txt:3 (find_package)

I have XCode6 installed in addition to clang through brew. The missing library libclang.dylib appears at /usr/local/opt/llvm/lib as installed by brew, additionally within /Applications through XCode. Clearly the cmake is simply not recognizing the installation. Can anybody provide any advice?

**Comment by cosmtrek** [comment]
I got this problem too. Similar to #136 .

I assume you have installed the latest version of llvm, if not `brew install llvm --with-clang`. llvm will be installed to `/usr/local/opt` by default. 

When executing `irony-install-server`, you need to add a flag `-DCMAKE_PREFIX_PATH=/usr/local/opt/llvm` after `cmake` to specify where the llvm is. Finally everything is ok.

**Comment by beejig** [comment]
CMake Error at /home/sharath/Downloads/cmake-2.8.8-Linux-i386/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
  Could NOT find LibClang (missing: LIBCLANG_LIBRARY LIBCLANG_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/sharath/Downloads/cmake-2.8.8-Linux-i386/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibClang.cmake:86 (find_package_handle_standard_args)
  src/CMakeLists.txt:3 (find_package)


-- Configuring incomplete, errors occurred!

Compilation exited abnormally with code 1 at Fri May  1 17:02:14


I am using a Ubuntu system unable to resolve this!!

**Comment by Sarcasm** [comment]
Where did you download the libclang package? /usr/lib/llvm-3.4 is a little bit weird for the prefix path. Can you search for the clang-c/Index.h file on your system. If you have mlocate installed:

    sudo updatedb
    locate clang-c/Index.h

**Comment by beejig** [comment]
$ locate clang-c/Index.h
/home/sharath/.emacs.d/elpa/ac-clang-20150414.2032/clang-server/clang-c/Index.h
/usr/lib/llvm-3.5/include/clang-c/Index.h

Can you suggest how I can install irony mode? when i run the install server

**Comment by Sarcasm** [comment]
What about:
    locate libclang.so

If it's `/usr/lib/llvm-3.5/lib/libclang.so`, you shouldn't have to do anything for it to work.

```
mkdir /tmp/irony-build
cd /tmp/irony-build
cmake /home/sharath/.emacs.d/elpa/irony-20150408.1501/server
make
```

Anyway, you can also try to specify LIBCLANG_LIBRARY LIBCLANG_INCLUDE_DIR manually to see if that's work, but that shouldn't be necessary:

```
cmake -DLIBCLANG_LIBRARY=/usr/lib/llvm-3.5/lib/libclang.so -DLIBCLANG_INCLUDE_DIR=/usr/lib/llvm-3.5/include/ ~/.emacs.d/ /home/sharath/.emacs.d/irony/ /home/sharath/.emacs.d/elpa/irony-20150408.1501/server
```

**Comment by beejig** [comment]
That seems to have worked! Thanks!

**Comment by Sarcasm** [comment]
which one?

**Comment by beejig** [comment]
If it's /usr/lib/llvm-3.5/lib/libclang.so, you shouldn't have to do anything for it to work.

mkdir /tmp/irony-build
cd /tmp/irony-build
cmake /home/sharath/.emacs.d/elpa/irony-20150408.1501/server
make

next i run the irony-install-server and it finished!

I have another problem. I do not know how to set up irony-mode. It is not looking at my src files to do code completion. I have installed company-irony as well.

**Comment by Sarcasm** [comment]
What does your irony-mode configuration looks like?

**Comment by beejig** [comment]
My ~/.emacs file snippet

(package-initialize)

(global-auto-complete-mode t)

(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

(package-initialize)


(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))

;; (optional) adds CC special commands to `company-begin-commands' in order to
;; trigger completion at interesting places, such as after scope operator
;;     std::|
(add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)

(package-initialize)


When I type on screen, auto-complete works fine. But no smart completion

**Comment by Sarcasm** [comment]
auto-complete and company-mode are two different completion frameworks. You will have to pick one of them, I think they can't be enabled both at the same time.

Take a look at company-mode's usage here: http://company-mode.github.io/

And disable auto-complete:

```el
;; (global-auto-complete-mode t)
```

**Comment by beejig** [comment]
Yes that seems to fix that issue. But that brings up another:

On occasions it doesn't work. It says "cannot complete at this point" This happens more often than not. It is working ok for small structures. But for boost, for eg boost:: (brings up nothing)

Also, how do i keep it always "on" like auto-complete-mode?

**Comment by Sarcasm** [comment]
Do you have the compile options properly setup? You have to tell irony about the header searchs path and all. What is the output of `M-x irony-cdb-menu RET`?

See https://github.com/Sarcasm/irony-mode#compilation-database

**Comment by beejig** [comment]
It says no compilation database.
[q] to quit

How do i set this up?

**Comment by Sarcasm** [comment]
Did you read: https://github.com/Sarcasm/irony-mode#compilation-database ?

The easiest to get started is to create a `.clang_complete` file with one flag per line.

**Comment by beejig** [comment]
Thank you! I used the cmake options and it seems to work. Appreciate all your help!

**Comment by Sarcasm** [comment]
Great!

**Comment by vermiculus** [comment]
Just a follow-up to this: what should the output of `irony-cdb-menu` be after running `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON <...>`? I'm still getting

```
No compilation database in use.

[q] to quit.
```

I can make a new thread if my error isn't obvious…

**Comment by Sarcasm** [comment]
It should be something like that:

```
Compilation Database: irony-cdb-libclang

  Working Directory: /home/papin_g/dev/irony/irony-mode-clang-build
  Compile Options:   -DCLANG_BUILTIN_HEADERS_DIR="/usr/lib/clang/3.7.1/include" -I/home/papin_g/dev/irony/irony-mode/server/src -fno-exceptions -O3 -DNDEBUG -fcolor-diagnostics -std=c++11 -Wall -Wextra

[q] to quit
```

**Comment by vermiculus** [comment]
I've written #339 above.

**Comment by Sleepful** [comment]
had this error on ubuntu 18, i had installed `clang llvm llvm-dev` but it wasn't working, finally installing `libclang-dev` worked out

**Comment by songmeixu** [comment]
> I assume you have installed the latest version of llvm, if not `brew install llvm --with-clang`. llvm will be installed to `/usr/local/opt` by default.

brew has changed the llvm installation. Now just `brew install llvm`, and set these ENV VARS:
```bash
# use brew llvm
if [ $(brew info llvm 2>&1 | grep -c "(bottled)") -eq 1 ]; then
# we are using a homebrew clang, need new flags
export PATH="/usr/local/opt/llvm/bin:$PATH"
export CC="/usr/local/opt/llvm/bin/clang"
export CXX="/usr/local/opt/llvm/bin/clang++"
export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
export CXXFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1"
export AR="/usr/local/opt/llvm/bin/llvm-ar"
export LD="/usr/local/opt/llvm/bin/clang"
fi
```

**Comment by dfinninger** [comment]
I didn't need to set all of the env vars from the previous comment.

`brew install llvm`
then adding:
`-DCMAKE_PREFIX_PATH=/usr/local/opt/llvm`
_directly_ after cmake (i.e., the first flag) worked for me.
