### ISSUE TITLE
A little hack to speedup using cache

### ISSUE THREAD

**Issue by tsukimizake** [Sarcasm/irony-mode#168]
I found vim-marching, a clang-complete plugin on vim, provides a simple cacheing functionality.

It is using a dictionary of modifiers (such as "std::", "var.", "var->") and candidates.
On completion after scope/dot/arrow operator, push the pair of the modifier and the completion candidates to cache.
On the next time completion requested at the same modifier, just use the cache.

For example, 

`std::|`
  
when completion requested on this situation, push `("std::" . '(candidate-list))` to cache.

Then, when completion requested on the same modifier `std::` next time, just return `(candidate-list)` on the cache, regardless of change in `std::` namespace.
Do the same on variable member completion.

As this cacheing strategy lacks strictness (see line 55-80 of this [doc](https://github.com/osyo-manga/vim-marching/blob/master/doc/marching.txt)), maybe it should be optional. Although it would be very effective when huge libraries are included.

Isn't it good enough to provide as an option of irony-mode?

**Comment by Sarcasm** [comment]
I would like to avoid "unperfect" methods for now. Maybe I could provide some completion hook for this parties to implement such functionality though.

**Comment by tsukimizake** [comment]
I see. Fair enough.
