### ISSUE TITLE
irony in windows problem

### ISSUE THREAD

**Issue by ClancyC** [Sarcasm/irony-mode#170]
I use Emacs 25.0.50.1 in windows. I install irony-mode. But I typed the **M-x irony-install-server RET**.
Then I got some error **Compilation exited abnormally with code 1**.

After that I decided to build myself.
**C:\Users\Clancy\Desktop\irony-mode-master\build>cmake -DLIBCLANG_LIBRARY=C:/LLVM
/bin/libclang.dll -DLIBCLANG_INCLUDE_DIR=C:\LLVM\include\ ..\server**
I typed this command then i got some error.
**C:\LLVM\bin\libclang.dll : fatal error LNK1107: invalid or corrupt file:
cannot read at 0x2F0**

**Comment by Sarcasm** [comment]
You cannot specify this: `-DLIBCLANG_LIBRARY=C:/LLVM
/bin/libclang.dll`

You have to give the path to the `C:/LLVM/lib/libclang.imp`, see https://github.com/Sarcasm/irony-mode/blob/b4f434cb42f3516cd842b61ab4d624d0edefa455/server/cmake/modules/FindLibClang.cmake#L57-L63

But the proper thing to do if LLVM is installed in `C:/LLVM` instead of the default path is to specify this path to the CMAKE_PREFIX_PATH:

    cmake -DCMAKE_PREFIX_PATH=C:/LLVM/ <other args...>

**Comment by ClancyC** [comment]
After that I got lots of link error. It's about clang library. Is there any other cmake arguments I should add. Or i just open the visual studio and set the project properties.

    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_getCString referenced in function _main [C:\Users\Clancy\Desktop\iro
ny-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxproj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_disposeString referenced in function _main [C:\Users\Clancy\Desktop\
irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxproj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_createIndex referenced in function _main [C:\Users\Clancy\Desktop\ir
ony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxproj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_disposeIndex referenced in function _main [C:\Users\Clancy\Desktop\i
rony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxproj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_getNumDiagnostics referenced in function _main [C:\Users\Clancy\Desk
top\irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxpr
oj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_getDiagnostic referenced in function _main [C:\Users\Clancy\Desktop\
irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxproj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_disposeDiagnostic referenced in function _main [C:\Users\Clancy\Desk
top\irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxpr
oj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_formatDiagnostic referenced in function _main [C:\Users\Clancy\Deskt
op\irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vcxpro
j]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_defaultDiagnosticDisplayOptions referenced in function _main [C:\Use
rs\Clancy\Desktop\irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec23
41551271.vcxproj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_parseTranslationUnit referenced in function _main [C:\Users\Clancy\D
esktop\irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.vc
xproj]
    LibClangDiagnosticsChecker.obj : error LNK2019: unresolved external symbol _
_imp__clang_disposeTranslationUnit referenced in function _main [C:\Users\Clancy
\Desktop\irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExec2341551271.
vcxproj]
    C:\Users\Clancy\Desktop\irony-mode-master\build\CMakeFiles\CMakeTmp\Debug\cm
TryCompileExec2341551271.exe : fatal error LNK1120: 11 unresolved externals [C:\
Users\Clancy\Desktop\irony-mode-master\build\CMakeFiles\CMakeTmp\cmTryCompileExe
c2341551271.vcxproj]

**Comment by Sarcasm** [comment]
Did you try this with a clean build directory? The link error appears during cmake generation when libclang looks for the built-in headers directory or when building irony-server?

**Comment by ClancyC** [comment]
Yes, I cleand the build directory before I typed cmake command.

**Comment by Sarcasm** [comment]
The following should be enough:

    cmake -DCMAKE_PREFIX_PATH=C:/LLVM/ ../server 

Do you have the same error?

**Comment by ClancyC** [comment]
I try this before. But cmake gave the error **Could Not find LibCland (missing: LIBCLANG_LIBRARY)**

**Comment by Sarcasm** [comment]
How about:

    cmake -DCMAKE_PREFIX_PATH=C:/ ../server 

?

**Comment by ClancyC** [comment]
Hmm. Link error show up again...

**Comment by ClancyC** [comment]
I change the llvm to 32-bit. Then solve this problem. It's some argument not add with 64-bit msvc or something else?

**Comment by Sarcasm** [comment]
I guess you have to have the same architecture for LLVM and irony-server. It depends on how you built LLVM.

For example it seems that if you want to build irony-server as 64 bit you need to tell cmake during generation with something like:

    cmake -G "Visual Studio 12 2013 Win64"  <...>

See http://stackoverflow.com/a/5359572/951426

**Comment by ClancyC** [comment]
Yeah! Your're right! Thanks for help!!
But why I can't use M-x irony-install-server RET in emacs?

**Comment by Sarcasm** [comment]
Because I didn't know you where using a 64 Bit LLVM. irony-install-server allows you to customize the command, so you can add -G "" to fit your needs.

There is a bug in Emacs I think with regard to the command line, you may have to remove the quote around `"cmake"`.

    "cmake"  "bla" "bla" "bla"

Should be

    cmake "bla" "bla" "bla"

**Comment by Sarcasm** [comment]
Closing.

Feel free to answer, I would be interested to know whether or not removing the quotes around `"cmake"` was the issue.

**Comment by Congee** [comment]
Same link error.
My llvm suite vrsion:
```
C:\Users\Congee\.emacs.d\elpa\irony-20170313.1437\server\build>clang --version
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\Congee\AppData\Local\scoop\apps\llvm\current\bin
```

MSVC, clang, and clang-cl all complain with link errors. While, gcc 4.9.2 worked. But the gcc generated irony-server has trouble in finding standard libraries. Namely, I can't use irony :/
All tools are 64bit.
cmake 3.7.2
Visual Studio 2017

Is it because my tool sets are too new?

**Comment by Congee** [comment]
Made it! Use `libclang.lib` to make a static link instead of `libclang.dll`.
```
make -DLIBCLANG_LIBRARY="C:\Users\Congee\AppData\Local\scoop\apps\llvm\4.0.0\lib\libclang.lib"  -DCMAKE_INSTALL_PREFIX=c:/Users/Congee/.emacs.d/irony/ "c:/Users/Congee/.emacs.d/elpa/irony-20170313.1437/server" -G "Visual Studio 15 2017 Win64"
```
```
cmake --build . --use-stderr --config Release --target install
```
