### ISSUE TITLE
irony server build failure after package upgrade

### ISSUE THREAD

**Issue by ackalker** [Sarcasm/irony-mode#173]
After upgrading the irony package, irony mode informed me that I needed to do `M-x irony-install-server` to upgrade the server:
```
irony-server version mismatch: type `M-x irony-install-server' to reinstall
```
Following this advice, I received the following message:
```
Compilation exited abnormally with code 1
Failed to build irony-server, you are on your own buddy!
```
while the `*irony-server-build*` buffer showed the following error:
```
-*- mode: compilation; default-directory: "~/.emacs.d/irony/build/" -*-
Compilation started at Mon Feb 16 15:30:45

cmake -DCMAKE_INSTALL_PREFIX\=/home/miki/.emacs.d/irony/ /home/miki/.emacs.d/elpa/irony-20150215.1357/server && cmake --build . --use-stderr --config Release --target install
CMake Error: The source "/home/miki/.emacs.d/elpa/irony-20150215.1357/server/CMakeLists.txt" does not match the source "/home/miki/.emacs.d/elpa/irony-20141217.1417/server/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

Compilation exited abnormally with code 1 at Mon Feb 16 15:30:45
```

My guess is that the directory `~/.emacs.d/irony/build` needs to be cleaned out before a rebuild.
Quick testing with:
```sh
$ rm -rf ~/.emacs.d/irony/build
```
then redoing `M-x irony-install-server` appears to confirm this: the build and installation now complete successfully.

**Comment by Sarcasm** [comment]
Thanks, I'm not using the MELPA packages much and I forgot a bit about this one, I will see about a workaround (versioned build directory in `/tmp/` maybe) .

**Comment by Sarcasm** [comment]
It should be fixed now. Thanks!

**Comment by ackalker** [comment]
On 02/17/2015 12:21 AM, Guillaume Papin wrote:
> It should be fixed now. Thanks!

You're welcome :-)
