### ISSUE TITLE
Compile error for find llvm directory, use "llvm-config" for better portable

### ISSUE THREAD

**Issue by sunlin7** [Sarcasm/irony-mode#180]
I use the local build/install LLVM packages.
I got cmake error message when try to configure with follow command line:
**cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ./irony-mode/server**
>CMake Error at /usr/local/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
>  Could NOT find LibClang (missing: LIBCLANG_LIBRARY LIBCLANG_INCLUDE_DIR)
Call Stack (most recent call first):
>  /usr/local/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
>  cmake/modules/FindLibClang.cmake:81 (find_package_handle_standard_args)
>  src/CMakeLists.txt:3 (find_package)

After investigate, I find add the llvm path to "irony-mode/server/cmake/modules/FindLibClang.cmake" can resolve the problem:
>diff --git a/server/cmake/modules/FindLibClang.cmake b/server/cmake/modules/FindLibClang.cmake
>index c99325f..16b9bcb 100644
>--- a/server/cmake/modules/FindLibClang.cmake
>+++ b/server/cmake/modules/FindLibClang.cmake
>@@ -38,6 +38,7 @@ foreach (version ${LIBCLANG_KNOWN_LLVM_VERSIONS})
>     "/usr/local/Cellar/llvm/${version}/include"
>     \# LLVM Homebrew/versions
>     "/usr/local/lib/llvm-${version}/include"
>\+    "~/.root/include"
>     )
>
>   list(APPEND libclang_llvm_lib_search_paths
>@@ -49,6 +50,7 @@ foreach (version ${LIBCLANG_KNOWN_LLVM_VERSIONS})
>     "/usr/local/Cellar/llvm/${version}/lib"
>     \# LLVM Homebrew/versions
>     "/usr/local/lib/llvm-${version}/lib"
>\+    "~/.root/lib"
>     )
> endforeach()

I think use "llvm-config" will better for portable.
[a sample llvm-config in other project] (https://github.com/Andersbakken/rtags/blob/master/cmake/FindLibClang.cmake)
Please check this.
Thank you.

**Comment by Sarcasm** [comment]
Yup, that's a sound proposition, something I have on in a corner of my head for a while now.

In recent version of LLVM there is also a LLVMConfig.cmake file that would be even better than llvm-config.

For your information a "generic" way to solve your issue by using `CMAKE_PREFIX_PATH`:

    cmake -DCMAKE_PREFIX_PATH=$HOME/.root/ <args...>

**Comment by sunlin7** [comment]
MAKE_PREFIX_PATH works.Please close this ticket. 

     Guillaume Papin <notifications@github.com> 于 2015年3月3日, 星期二, 上午 5:52 写道：
   

 Yup, that's a sound proposition, something I have on in a corner of my head for a while now.In recent version of LLVM there is also a LLVMConfig.cmake file that would be even better than llvm-config.For your information a "generic" way to solve your issue by using CMAKE_PREFIX_PATH:cmake -DCMAKE_PREFIX_PATH=$HOME/.root/ <args...>

**Comment by sunlin7** [comment]
Thank you. 

     Guillaume Papin <notifications@github.com> 于 2015年3月3日, 星期二, 上午 5:52 写道：
   

 Yup, that's a sound proposition, something I have on in a corner of my head for a while now.In recent version of LLVM there is also a LLVMConfig.cmake file that would be even better than llvm-config.For your information a "generic" way to solve your issue by using CMAKE_PREFIX_PATH:cmake -DCMAKE_PREFIX_PATH=$HOME/.root/ <args...>

**Comment by sunlin7** [comment]
MAKE_PREFIX_PATH works.
Please close this ticket.
Thank you.
