### ISSUE TITLE
`irony-cdb-autosetup-compile-options` is not a function

### ISSUE THREAD

**Issue by politza** [Sarcasm/irony-mode#181]
The above function is mentioned in the README but does not exist.

**Comment by Sarcasm** [comment]
Is it not? https://github.com/Sarcasm/irony-mode/blob/edbb11253c7deb1e23586e84bb160d5dc7e1f58b/irony-cdb.el#L76

Did you setup irony-mode with MELPA in the same way it's explained here: https://github.com/Sarcasm/irony-mode#configuration ?

**Comment by politza** [comment]
Ah, sorry my package came from melpa-stable, where it is indeed not defined.
