### ISSUE TITLE
irony-mode -D options in JSON compilation database

### ISSUE THREAD

**Issue by kotakotakota** [Sarcasm/irony-mode#185]
Hello,

Thus far I am really enjoying irony-mode... It's been really helping my productivity.

I was wondering about predefined macros. When I have a macro predefined using -D, it does not seem to persist in irony-mode.

My compile_commands.json:

    [
    {
      "directory": "/home/kota/Projects/ogl_template/build",
      "command": "/usr/bin/c++     -std=c++11 -DGL_GLEXT_PROTOTYPES -I/usr/include/SDL2    -o CMakeFiles/main.dir/main.cpp.o -c /home/kota/Projects/ogl_template/main.cpp",
      "file": "/home/kota/Projects/ogl_template/main.cpp"
    },
    {
      "directory": "/home/kota/Projects/ogl_template/build",
      "command": "/usr/bin/c++     -std=c++11 -DGL_GLEXT_PROTOTYPES -I/usr/include/SDL2    -o CMakeFiles/main.dir/ogl_context.cpp.o -c /home/kota/Projects/ogl_template/ogl_context.cpp",
      "file": "/home/kota/Projects/ogl_template/ogl_context.cpp"
    },
    {
      "directory": "/home/kota/Projects/ogl_template/build",
      "command": "/usr/bin/c++     -std=c++11 -DGL_GLEXT_PROTOTYPES -I/usr/include/SDL2    -o CMakeFiles/main.dir/simple_ogl_world.cpp.o -c /home/kota/Projects/ogl_template/simple_ogl_world.cpp",
      "file": "/home/kota/Projects/ogl_template/simple_ogl_world.cpp"
    },
    {
      "directory": "/home/kota/Projects/ogl_template/build",
      "command": "/usr/bin/c++     -std=c++11 -DGL_GLEXT_PROTOTYPES -I/usr/include/SDL2    -o CMakeFiles/main.dir/simple_shader_world.cpp.o -c /home/kota/Projects/ogl_template/simple_shader_world.cpp",
      "file": "/home/kota/Projects/ogl_template/simple_shader_world.cpp"
    }
    ]

Output of `M-x irony-cdb-menu`:

    Compilation Database: irony-cdb-json
    
      Working Directory: /home/kota/Projects/ogl_template/build
      Compile Options:    -std=c++11 -I/usr/include/SDL2

Is this a user error (ie am I just missing some option)? Or is this just not supported by irony-mode?

Thank you!

EDIT: I should also clarify that I know about the variable `irony-additional-clang-options`, (and thus I have scripts for setting that appropriately for each context) but I was just hoping there was some automated way... Though I guess in many cases that might not make much sense.

**Comment by Sarcasm** [comment]
Hum, that's weird, I'm not filtering out the defines, so there might be a bug somewhere.

**Comment by Sarcasm** [comment]
I cannot reproduce the issue, with the following compilation database:

```
[
{
  "directory": "/home/papin_g/projects/irony/test-json-cdb-build",
  "command": "/usr/bin/c++     -std=c++11 -DGL_GLEXT_PROTOTYPES -I/usr/include/SDL2    -o CMakeFiles/foo.dir/foo.cpp.o -c /home/papin_g/projects/irony/test-json-cdb/foo.cpp",
  "file": "/home/papin_g/projects/irony/test-json-cdb/foo.cpp"
}
]
```

Opening the file foo.cpp triggers the following compile options:

```
Compilation Database: irony-cdb-json

  Working Directory: /home/papin_g/projects/irony/test-json-cdb-build
  Compile Options:   -std=c++11 -DGL_GLEXT_PROTOTYPES -I/usr/include/SDL2

[q] to quit
```

**Comment by kotakotakota** [comment]
Strange.. It seems to be working for me now, though I am pretty sure I did not do anything different. Anyway, thanks for the help (and for the awesome software). I'm going to close.
