### ISSUE TITLE
Irony repeatedly loads and parses the compile database

### ISSUE THREAD

**Issue by miabrahams** [Sarcasm/irony-mode#204]
Using Irony for a medium/large sized project with a 10MB cdb, I noticed it was taking a long time to open new files within an already open project.  I am using the standard Irony configuration, including the hook `(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)`.  The emacs profiler reported that most of the time loading files is spent in on the call to this hook.  Around half the time is spent calling `(json-read-file)`, the other half is spent calling `(irony-cdb-json--transform-compile-command)`.

**Comment by Sarcasm** [comment]
Hi,

Yeah there are a few issues with the compilation database implementation.

@Hylen has started some work on it, on hold for now: #188

This makes the loading faster for source file that appears directly in the compilation database (order of magnitude faster I believe) but there are still issues on how to make it faster for other files (i.e: headers/new files).

Once a good method has been found I would be tempted to do some caching of the compilation database if that appears still necessary.

Right now I would say yes it is inefficient. I would be interested in PR to fix this but I'm not working on it actively.

**Comment by Sarcasm** [comment]
FYI, #212 made the loading faster for files that are directly in the compilation database.

As said earlier, it doesn't solve the issue with headers/new files.

**Comment by miabrahams** [comment]
I tried it out and it's awesome.  Great update.
