### ISSUE TITLE
Any way to reload file?

### ISSUE THREAD

**Issue by hotpxl** [Sarcasm/irony-mode#219]
Hi,

First I opened a file `main.cpp`, but there is not `.clang_complete` file in the directory. So `irony-mode` shows me a lot errors. Then I added a `.clang_complete` file. How can I tell `irony-mode` to reload and recompile in this scenario?

**Comment by Sarcasm** [comment]
You can call `irony-cdb-autosetup-compile-options` manually.

**Comment by hotpxl** [comment]
Great. That works. Also is there any way to force `irony` to recompile and pass new results to `flycheck`. For example I have two files, I changed something in the first file, and then I switch to buffer with the second file. Things are not updated automatically. I guess I have to invoke something that `ForceRecompile` to update cache. Is there anything like this?

**Comment by Sarcasm** [comment]
Hum I see,

I think there is a command in flycheck to force this, or if you are lazy like me you can use `C-x C-v` to reopen the buffer.

**Comment by hotpxl** [comment]
Thanks. The flycheck command is <kbd>C-c ! c</kbd>. Seems irony is passive to flycheck, so invoking flycheck recheck would force irony to recompile the file.
