### ISSUE TITLE
Serializing data?

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#220]
I work with a large project at work. Irony will start when I want it too (I personally only have it start up when I press f11 because I want to be in control of when I get completions - this is for all company modes I use). 

So, with this large project I wait a maximum of 8/10 seconds for a completion. Then, after that it is quick - and that is fine ( I tried with Semantic for half a year and I like the guys that work on it and contributed to bug issues but the fact is - it is not quick enough when dealing with a large project). 

But there is still my question as to how intellisense is so quick. I have noticed that when I load a big solution - in the background intellisense scans all the files and it must store all of this information in some database or something - or perhaps caches it in memory while the computer is not restarted.

Can irony not do the same thing? Can it - in the background parse all the files and store all the results in some database that will be lightening quick (like intellisense) when I want a completion.

I was working on something at home to do with parsing, and I kept an hash map of all the files' md5. If one of the md5s change then we know that it may be wise to update the completions database. This could be done in the background.

It is just a suggestion; that - in summary - is it possible to have a DB of completions so that we get super quick completions?

Cheers.

**Comment by Sarcasm** [comment]
That is too difficult to implement IMHO, too difficult to get right. I would be interested to integrate somehow with an indexer like http://www.kythe.io/ or https://srclib.org/ but even with these tools there is a lot of work to do I think, and not even sure that will help with completion.
