### ISSUE TITLE
Question on non .clang_complete includes

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#221]
How does irony know about STL completions? I have never needed to supply -I/path/to/includes and yet Irony knows about these. We use windows at work, so the includes I will be using for STL such things are in the VS12 directory. I also have mingw/msys, so they exist in /usr/include - but I cannot seem to successfully grep for this in the git clone.

I can only think Irony knows the location of all system includes from the environment? Eg, how does it know the system includes for VS on Windows? Windows is always a little more tricky than GNU/Linux where your system includes are /usr/include
Cheers

**Comment by Sarcasm** [comment]
irony doesn't know, Clang does:

- https://github.com/llvm-mirror/clang/blob/2abbec88f288baf3c2dc2c2f67a63f6cba3a41e7/lib/Driver/MSVCToolChain.cpp#L431-L493
- https://github.com/llvm-mirror/clang/blob/2abbec88f288baf3c2dc2c2f67a63f6cba3a41e7/lib/Driver/CrossWindowsToolChain.cpp
- https://github.com/llvm-mirror/clang/blob/2abbec88f288baf3c2dc2c2f67a63f6cba3a41e7/lib/Driver/ToolChains.cpp
- ...

It is quite complex. On Windows it is also a little bit more difficult even though clang supports it (`clang-cl`), with libclang it's not always clear to me how to get things working, libclang can understand the windows flag (`/Something`) but it is not easy the last time I tried, I have some notes/experimentation on my Windows partition.
