### ISSUE TITLE
irony server build failure after package upgrade

### ISSUE THREAD

**Issue by johnchunwai** [Sarcasm/irony-mode#224]
This is related to issue:
https://github.com/Sarcasm/irony-mode/issues/173

I'm still having the issue on windows. What I found was that the cmake cache files were written to the temp directory instead of temp/irony-build-[server-version] directory. This can be solved by adding the trailing slash like "irony-build-[server-version]/".

Not sure if it is windows cmake or emacs default-directory ignoring the last trailing directory if it misses a trailing slash.

**Comment by Sarcasm** [comment]
Thanks, should be fixed now.

**Comment by johnchunwai** [comment]
Thank you very much!
