### ISSUE TITLE
std::problems

### ISSUE THREAD

**Issue by happycorsair** [Sarcasm/irony-mode#231]
Hello, @Sarcasm and other developers!
Thank you for irony-mode, it's a great tool!

Just a small issue with autocompletion: Irony doesn't see at all some std features, such as std::tie or std::unique_ptr (the ones I found).

My environment:
Arch Linux, Emacs 24.5.1, Clang 3.6.2, JSON Compilation Database

**Comment by 3246251196** [comment]
I can confirm this issue to.

It can be fixed by defining the necessary macro before #include <memory>

So, an example:
    #define __cplusplus 201103L
    #include <memory>
    int main() {
        //std::uniq SHOWS
        return 0;
    }

Evidentally, the condition in memory:

    #if __cplusplus >= 201103L
    #  include <exception>        	  // std::exception
    #  include <typeinfo>         	  // std::type_info in get_deleter
    #  include <iosfwd>           	  // std::basic_ostream
    #  include <ext/atomicity.h>
    #  include <ext/concurrence.h>
    #  include <bits/functexcept.h>
    #  include <bits/stl_function.h>  // std::less
    #  include <bits/uses_allocator.h>
    #  include <type_traits>
    #  include <functional>
    #  include <debug/debug.h>
    #  include <bits/unique_ptr.h>
    #  include <bits/shared_ptr.h>
    #  if _GLIBCXX_USE_DEPRECATED
    #    include <backward/auto_ptr.h>
    #  endif
    #else
    #  include <backward/auto_ptr.h>
    #endif

is not on our side.

**Comment by 3246251196** [comment]
I was going to add that you should enable to the c++11 flag to the compiler options (via .clang_complete - for example) - but now, all of a sudden I get the completions coming up with the first snipped of code and without any compiler options. Odd.

**Comment by Sarcasm** [comment]
You should have proper compile options setup, for example `-std=c++11` if you want unique_ptr and friends to be available.

What is the command line used to compile the file? You should have similar flags in the compilation database: https://github.com/Sarcasm/irony-mode/tree/3d7fe7cd43a070a57527d7a8fd1b98bc086848b8#compilation-database

Manually defining `__cplusplus` or such is not a solution, more like asking for trouble.

**Comment by happycorsair** [comment]
Hello, guys!
I'm very sorry for such a long absence, I was abroad and had no good Internet connection.

@3246251196, thanks for your answer. Your solution works like a charm, but it will be much better to find another solution which doesn't need source code modification. Anyway, you helped me a bit to improve my C++ knowledge, I didn't know about __cplusplus macro.

@Sarcasm, nice to see you here. Your Emacs stuff is great :-)
I use JSON compilation database, which is provided by CMake.
CMakeLists.txt:
```
cmake_minimum_required (VERSION 2.6)
project (hello)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
add_executable(hello hello.cpp)
```
compile_commands.json:
```
{
  "directory": "/home/user/workspace/test/build",
  "command": "/usr/bin/c++     -std=c++11   -o CMakeFiles/hello.dir/hello.cpp.o -c /home/user/workspace/test/hello.cpp",
  "file": "/home/user/workspace/test/hello.cpp"
}
```
Trying to add .clang with -std=c++11 flags also seems to be useless. Where is my mistake?
Do you have any ideas?
Thank you!

**Comment by Sarcasm** [comment]
Do you see proper compile options in `irony-cdb-menu` ?

**Comment by happycorsair** [comment]
Huh, `irony-cdb-menu` is empty at the very beginning.
If I run `irony-cdb-json-add-compile-commands-path` with argument showing my build directory with compile_commands.json inside `irony-cdb-menu` continues to stay empty. Is this the proper way to deal with json-file?
But if i run `irony-cdb-autosetup-compile-options`, it successfully adds --std=c++11 flag.

**Comment by Sarcasm** [comment]
The idea is:

1. add the compilation database a first time so that irony knows the project. This is done with `irony-cdb-json-add-compile-commands-path`. Once this has been done, irony will remember it, it stores the path in `~/.emacs.d/irony/cdb-json-projects`.

2. run `irony-cdb-autosetup-compile-options` to load the compile options from compile_commands,json, .clang_complete, ... This is better done in a hook, as shown in the configuration here: https://github.com/Sarcasm/irony-mode/tree/3d7fe7cd43a070a57527d7a8fd1b98bc086848b8#configuration

**Comment by happycorsair** [comment]
Yes!!! It works perfect.
Thanks a lot! And I'm sorry for spending your time, the proper way of using it was not clear for me after reading readme.

**Comment by Sarcasm** [comment]
No problem.
