### ISSUE TITLE
Time out response when irony-server still running

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#233]
Company: Back-end company-irony async timeout with args (candidates someSymbol)

In the case where one is using a large code base and completion takes - initially - a number of seconds, the message shown above from company will appear even though I can see that the irony-server process is still busy.

**Comment by Sarcasm** [comment]
Well, company has implemented a timeout to be more robust to some backend I believe, it had to choose an arbitrary limit. You could set the limit to a higher value I guess but otherwise you can just safely ignore this message, it usually only happens at the first parse.

**Comment by 3246251196** [comment]
Thanks,

can be achieved by increasing the value for company-async-timeout
