### ISSUE TITLE
Request: better support for cmake out-of-tree build directories

### ISSUE THREAD

**Issue by MikeSanMichel2** [Sarcasm/irony-mode#234]
Hi,

Irony has been great, but I had some trouble getting it to work. Here's one
suggestion/request for a better out-of-the-box experience.

- Many popular OSS projects use cmake and I use it for my own as well.
- The norm in CMake is that you use a seperate build directory instead of building in-tree.
- CMake will generate `compile_commands.json`, if you enable `CMAKE_EXPORT_COMPILE_COMMANDS` on the commandline or in `CMakeLists.txt`.
- The cdb ends up in the build directory.
- Often (though not always) the build directory is named `build` under the project's root
directory.

Irony currently only searches parent directories (recursively) for the cdb, so I've had to
place a symlink in the project root. Since CMake is so common and there's a convention
on where the build directory lives, would it be possible to have irony check for `build/compile_commands.json` as it traverses through parent directories? that would
eliminate one step in getting irony setup.

Thanks again for making the package available!

**Comment by aport** [comment]
Hi there,

A while back I added support to the wonderful cpputils-cmake package (https://github.com/redguardtoo/cpputils-cmake) which looks in build/ for compile_commands.json and passes it to irony.

If you install that package then this will automagically work.

**Comment by Sarcasm** [comment]
Hello, thank you for you feedback, I am well aware of the out-of-source build with CMake, which is how irony-server is built itself.

Right now the user has to specify the directory manually by calling `irony-cdb-json-add-compile-commands-path`. I thought about a user configurable list of sub-path to look at, such as `build/` which I sometime use, some other times I use something else. I agree with the idea, I haven't tried to implement it yet (should be trivial, contributions welcomed!).

**Comment by MikeSanMichel2** [comment]
@aport , thanks, but I actually do use it already. I can't recall if I installed it because of this very issue
or whether I still had problem after. I'll check and open an issue over there if I need to.

**Comment by MikeSanMichel2** [comment]
Ok, aside from having irony find it automatically, I don't manuall adding a json file which
isn't found through parent directory search works either. separate issue: #236

**Comment by MikeSanMichel2** [comment]
closed by #237
