### ISSUE TITLE
irony-cdb-json-add-compile-commands-path doesn't work

### ISSUE THREAD

**Issue by MikeSanMichel2** [Sarcasm/irony-mode#236]
#234 was about finding `build/compile_commands.json` automatically, but
after more testing I think irony doesn't actually use a cdb if autosetup can't find it.

Using `irony-cdb-json-add-compile-commands-path`  to add  `build/compile_commands.json` doesn't work. it updates `irony-cdb-json--project-alist`, and it shows up in `~/.emacs.d/irony/cdb-json-projects` but the completion doesn't show members, and flycheck-irony complains about headers (missing `-I`).

Irony provides some completion even without  a cdb, which makes it seem like it's
working, but so far the only thing that actually works is putting a symlink to `compile_commands.json`
in the project root and running `autosetup`. a few seconds after that the flycheck errors
go away and completion finds class members.

`cpputils-cmake` makes no difference. if the cdb is in the root irony works, otherwise it doesn't.

`irony-20150831.144/`

**Comment by MikeSanMichel2** [comment]
Looks like #193 reported same.
And #190 too.

**Comment by MikeSanMichel2** [comment]
Looks like I was fooled by the UI, and used the build directory as project root.
So not a bug, but my mistake. Will follow up with a PR to perhaps simplify things
and eliminate the chance of error.

**Comment by Sarcasm** [comment]
Thanks ;)
