### ISSUE TITLE
osx failed to autocomplete

### ISSUE THREAD

**Issue by senarukana** [Sarcasm/irony-mode#238]
Hi,
 I have a problem to set up irony mode for autocomplete. I can manually use completion-at-point to get the desire autocomplete for the input, but it doesn't appear in the buffer automatically. 
I follow the tutorial from this [post](http://cachestocaches.com/2015/8/c-completion-emacs/#further-reading). 
System is osx, and my configuration is as followed:
```
(use-package irony
  :ensure t
  :defer t
  :init
  (add-hook 'c++-mode-hook 'irony-mode)
  (add-hook 'c-mode-hook 'irony-mode)
  (add-hook 'objc-mode-hook 'irony-mode)
  :config
  ;; replace the `completion-at-point' and `complete-symbol' bindings in
  ;; irony-mode's buffers by irony-mode's function
  (defun my-irony-mode-hook ()
    (define-key irony-mode-map [remap completion-at-point]
      'irony-completion-at-point-async)
    (define-key irony-mode-map [remap complete-symbol]
      'irony-completion-at-point-async))
  (add-hook 'irony-mode-hook 'my-irony-mode-hook)
  (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
  )
(use-package company
    :ensure t
    :defer t
    :init (add-hook 'after-init-hook 'global-company-mode)
    :config
    (use-package company-irony :ensure t :defer t)
    (setq company-idle-delay          0.08
      company-minimum-prefix-length   2
      company-show-numbers            t
      company-tooltip-limit           20
      company-dabbrev-downcase        nil
      company-backends                '((company-irony company-gtags))
      )
    :bind ("C-;" . company-complete-common)
)
```
Thank you for your help.

**Comment by Sarcasm** [comment]
a quick look at the configuration looks fine.

which one of `completion-at-point` amd `irony-completion-at-point-async` is working?
do you have a minimal example to reproduce the issue?
do you have the proper compile options setup? `irony-cdb-menu` will tell you.
can you try to run `irony-server` manually like this:

```
$ ~/.emacs.d/irony/bin/irony-server -i
complete /tmp/irony-issue-238.cpp 10 15
-std=c++11
...
```

Not sure the last last is clear enough but I do not have enough information about the issue.

**Comment by senarukana** [comment]
1. irony-completion-at-point-async is working.
2. irony-cdb-menu show nothing
3. ~/.emacs.d/irony/bin/irony-server -i
complete /tmp/irony-issue-238.cpp 10 15
-std=c++11
this command can get the desire input.

**Comment by Sarcasm** [comment]
So it's a company/company-irony issue.

What is the value of `company-backends`? `C-h v company-backends`.
What minimal test code do you have to reproduce the issue?

**Comment by senarukana** [comment]
Problem solved, thank you Sacasm. It was due to the custom-set-variables which set company-backends manually at the end, then company-backends contains no company-irony.

**Comment by Sarcasm** [comment]
Great!
