### ISSUE TITLE
Irony crash when user misses type of template completion

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#240]
ironyserver crashes with this issue error: R6025 - pure virtual function call

When something like

    SomeTemplateClass:: // crashed here

is typed.

It should really be

    SomeTemplateClass<SomeType>:: // works fine.

It should be handled differently?

**Comment by Sarcasm** [comment]
Interesting. Minimal code + compile flags would be nice. Does it happens only with irony and not clang?
