### ISSUE TITLE
Irony Server Crash Useful Information

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#242]
Unfortunately we need to change machines at work which means the usual half-a-year setting EVERYTHING back up again.

For me this involves setting up a new irony server on emacs.

So, why not switch to the latest CLANG version and Irony etc.

1. First problem I find: there is no longer a irony-completion-mode variable - and need to set this to t manually. Not sure why...

2. I am also trying to find out why now it says in log file that string is not a member of std. I don't recall needing to tell Clang on my older machine about the location of the VC-includes. I guess I can try telling clang to include the VC/includes, but this is weird.

3. Also, I am getting crashes for certain completions and all that appears is a box saying: "A problem caused the program to stop working correctly. Please close the program" - no useful information at all. Even the log file does not tell me the error code or anything.

**Comment by 3246251196** [comment]
I can answer 1. Which is the variable has been taken out of the new version... I guess I can add a hook to set it again, but this must have been done for a reason...

**Comment by Sarcasm** [comment]
> I am also trying to find out why now it says in log file that string is not a member of std. I don't recall needing to tell Clang on my older machine about the location of the VC-includes. I guess I can try telling clang to include the VC/includes, but this is weird.

I'm not super-familiar with the Windows environment, on your older PC, was Emacs running in a vcvars environnement? In this case I think Clang is able to find all the relevant informations.

**Comment by 3246251196** [comment]
The main problem is the fact that I am not getting any useful indication of why Irony Server is crashing. There is no way to find out what the problem is unless I go in and hack about with the server.

I might revert back to older ironyserver, company-irony and even revert to clang3.5 to see if the same thing happens

**Comment by 3246251196** [comment]
Problem has been solved by downgrading to CLANG 3.5, I have not the time to figure out why. I can give some snippets of the log file later.

**Comment by Sarcasm** [comment]
> The main problem is the fact that I am not getting any useful indication of why Irony Server is crashing. There is no way to find out what the problem is unless I go in and hack about with the server.

Exactly.

> Problem has been solved by downgrading to CLANG 3.5, I have not the time to figure out why. I can give some snippets of the log file later.

Please, it may be of interest to the Clang folk if irony is not at fault. And if irony does something shady that no longer works I would be glad to know.
