### ISSUE TITLE
How could i call my function after the 'irony-compile-options' being filled?

### ISSUE THREAD

**Issue by ShineSong** [Sarcasm/irony-mode#244]
I'm a newbeing emacser,recently I try to config my own ide.I found that cedet is not accuracy so I turn to use irony-mode.But...emm,maybe my project contain's alot of template headers or what.It's a little...slow.About 4-8 second to solve the completition in simple object member of a simple struct in my own project.
So,I want to combine cedet-semantic and irony clang completing for both efficienty & accuracy.
I write a little function to fetch including path from irony-compile-options (I like this featrue!) and add to semantic-system-include-path.like this.

```el
(defun sxs-add-irony-include-to-semantic()
		     (setq semantic-dependency-system-include-path nil)
		     (mapc (lambda (dir)
			     (let(idx)
			       (setq idx (string-match "-I" dir))
			       (when idx
				 (when (= idx 0)
				   (semantic-add-system-include (cl-subseq dir 2) 'c++-mode)
				   (semantic-add-system-include (cl-subseq dir 2) 'c-mode))))
			     irony--compile-options)))
```

And add to irongy-mode-hook.But when i run this.emacs show "wrong number of arg mapc 1),and i noticed irony-compile-options is nil.I think it might be filled after call hook.Is there any way to call may code after read cdb?

**Comment by ShineSong** [comment]
emmm.I found I made some mistake.When use M-x c++-mode manually ,the exception occured,but when I restart emacs,and open a file normally,the var is correct.I not very clear what happened.

**Comment by Sarcasm** [comment]
You have an issue with the parenthesis, you didn't close the lambda properly, try:


```el

(defun sxs-add-irony-include-to-semantic()
  (setq semantic-dependency-system-include-path nil)
  (mapc (lambda (dir)
          (let(idx)
            (setq idx (string-match "-I" dir))
            (when idx
              (when (= idx 0)
                (semantic-add-system-include (cl-subseq dir 2) 'c++-mode)
                (semantic-add-system-include (cl-subseq dir 2) 'c-mode)))))
        irony--compile-options))
```

**Comment by ShineSong** [comment]
o my,what a stupid mistake.I fix it and work well now.Thanks for your great work :+1:

**Comment by Sarcasm** [comment]
Great!
