### ISSUE TITLE
providing global .clang_complete file?

### ISSUE THREAD

**Issue by agauniyal** [Sarcasm/irony-mode#245]
For general completion when not using cmake as build system, or small 1-2 files autocompletion. YCM does this by providing a flag accepting location for global ycm_config file.

**Comment by agauniyal** [comment]
YCM has these for global conf which makes it a bit easier.

```
flags = [
'-Wall',
'-Wextra',
'-Werror',
'-Wno-long-long',
'-Wno-variadic-macros',
'-fexceptions',
'-DNDEBUG',
'-std=c++14',
'-x',
'c++',
'-isystem',
'../BoostParts',
'-isystem',
'/System/Library/Frameworks/Python.framework/Headers',
'-isystem',
'../llvm/include',
'-isystem',
'../llvm/tools/clang/include',
'-I',
'.',
'-I',
'./ClangCompleter',
'-isystem',
'./tests/gmock/gtest',
'-isystem',
'./tests/gmock/gtest/include',
'-isystem',
'./tests/gmock',
'-isystem',
'./tests/gmock/include',
'/usr/lib/libXbgi.a',
'-lX11',
'-lm'
]
```

**Comment by Sarcasm** [comment]
You have 2 options:

Either create a .clang_complete file in your home directory for example, it will end up being used as a fallback. This may be a little hacky.

Another good solution is to write a custom compilation database for this, it should be fairly straightforward, see documentation at https://github.com/Sarcasm/irony-mode/blob/3e9d37cb9a7b6feca2606ba6919b267deebe3531/irony-cdb.el#L50-L78

It's on my todo list to have something nice to do it but I haven't get to do it yet.

**Comment by agauniyal** [comment]
Can you add a function for specifying global .clang_complete file? I'm fairly new to emacs and don't know a thing about lisp so I guess I would have to do it with home-directory method :/
