### ISSUE TITLE
`irony-cdb-search-directory-list` only looks for directories in the project path

### ISSUE THREAD

**Issue by atilaneves** [Sarcasm/irony-mode#247]
I just tried setting `irony-cdb-search-directory-list` to `'("/build/myproject")`, where the compilation DB is, but instead it appended that to where the source file was and couldn't find the DB.

**Comment by agauniyal** [comment]
ping @Sarcasm

**Comment by Sarcasm** [comment]
Sorry about the silence, thanks for the ping.

In this case, where the compilation database cannot be found by looking at a relative path you can call `irony-cdb-json-add-compile-commands-path` to add a compilation database for the given project.

Putting an absolute path in `irony-cdb-search-directory-list` make little sense I believe unless you have one compilation database for all of your projects but if that the case, I don't think putting this path in `irony-cdb-search-directory-list` is the best way to express this.

**Comment by atilaneves** [comment]
Absolute file paths always make sense in any filesystem. The use case, however, would be to specify a path to the compilation database that resides in an unrelated path.

At work, I usually have the source files under my home directory and the build dirs under `/build`. This is why I filed the bug.

**Comment by Sarcasm** [comment]
> The use case, however, would be to specify a path to the compilation database that resides in an unrelated path.

That's what `irony-cdb-json-add-compile-commands-path` is for.
Did you try: `M-x irony-cdb-json-add-compile-commands-path RET`?

**Comment by atilaneves** [comment]
Ah, I see. I wasn't aware of that function. Things work perfectly now so I'll close the issue. Thanks!
