### ISSUE TITLE
Request of flycheck-irony behaviour on startup of source file

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#249]
I like flycheck-irony, but the code base at work means that I need to wait for about 10seconds for the Irony process to "do things" before I get completions. Since - when you change a source file - flycheck will kick in, the irony server takes along time to parse and this causes crashes and just general bad behaviour.

Basically, I cannot use flycheck. BUT, the reason for this ticket is that I want to run the irony server on the first file I open that is a c++ file. As it stands, ironyserver will not start up until you issue a symbol eg:

myClass->[IRONY STARTS HERE]

However, with flycheck, Irony server starts when you LOAD up the file which makes sense. But, I cannot use flycheck, but I still want irony server to start up straight away. I do not have enough elisp knowledge to find out how flycheck starts the server straight away - but is it not a simple function call or hook function?

I have tried this before by manually calling "irony-server-start" (or something like that) HOWEVER, when I then do 

myClass-> - ANOTHER irony server starts.

This ticket is to request the option (which could default to false) that irony server starts on the entry of a new source file.

Cheers.

**Comment by Sarcasm** [comment]
Ok, make sense, it would be easy to do an initial parse (there was one a while back) as an irony-mode hook.

One thing to be aware of is that when you do a lot of file modifications using for example `dired-do-query-replace-regexp` (https://www.gnu.org/software/emacs/manual/html_node/efaq/Replacing-text-across-multiple-files.html), many files are open at once and the server cannot keep up in this situation.

Running the hook only after a short idle time spent on the buffer should be ok, I think that's what flycheck does.

You could call `irony--parse-buffer-async` to trigger the initial parsing in an idle timer (example here I think: http://stackoverflow.com/a/24009529/951426).

**Comment by 3246251196** [comment]
Hi, I will try that out. Just been testing with that function. Looks like I can just pass in an empty lambda function as the callback function to satisfy the arguments.

I cannot try this out until at work, but I will let you know what happens with it. I have a feeling other people may want this, so I could try adding something to irony.el as a patch - but I should NOT be trusted. I will have a go though.

**Comment by 3246251196** [comment]
Hi, 

so I have tried this out at work and it does work exactly as it should - it parses the buffer automatically and I just satisfy the callback function with an empty lambda taking one argument.

However, it only parses the current buffer (which seems correct).

Is there anyway to tell it to parse the includes files too?

Cheers.

**Comment by Sarcasm** [comment]
Could you post your code?

> Is there anyway to tell it to parse the includes files too?

Not to my knowledge. Are they opened by Emacs?
How to know which ones to parse? All of them?

**Comment by 3246251196** [comment]
The only was I can get the behaviour I want is to basically do this hack:
(defun rjd-irony-start-irony-run ()
  (insert "a->")
  (irony-completion-at-point-async)
  (move-beginning-of-line nil)
  (delete-char 3)
  (save-buffer))

So, when I load up a source file, run this function. It does not matter that the variable a is stupid - because irony goes ahead and parses all the files (nearly). This means that by the time I go to the place in the file where I want intelligent completion, the server has asynchronously parsed the large majority of what I need. So instead of waiting 15 second, I only have to wait something like 3 and then things speed up.

This is a horrible hack I know, but it does what I want it to.

**Comment by Sarcasm** [comment]
> The only was I can get the behaviour I want is to basically do this hack:
> ```el
>     (defun rjd-irony-start-irony-run ()
>       (insert "a->")
>       (irony-completion-at-point-async)
>       (move-beginning-of-line nil)
>       (delete-char 3)
>       (save-buffer))
> ```

Why insert "a->"? Did you try without?
Why move to the beginning of line? It's dangerous, there is a something in Emacs called `save-place`, that will restore the last point position when the buffer is opened. Meaning your initial point can well be in the middle of a string.
Moreover, inserting something that does not compile at the beginning of the file might be less efficient than at the end (I would recommend to call `(end-of-buffer)` if inserting some content is necessary) because libclang cache the preamble of the file (usually some `#includes`) and does not recompute it if the preamble did not change. Here you are computing a temporary preamble so libclang will have to recompute.

Anyway, I think you are aware this is a hack. IMHO we can do elegantly without a hack without at the same level of difficulty.


> I am trying to get this to work though, here are two scenarios:
> 
> I open a c++ file and then I M-: (rjd-irony-start-irony-run) . This does what I want But the second scenario does not work:
> I add something like this: (add-hook 'irony-mode-hook 'rjd-irony-start-irony-run) . This also does run irony and it starts to parse but the quickly finishes. Basically, for some reason it does not parse much and is as good as useless. I do not know if it is because on hook it is getting called too early or something. I could try messing around with a timer function.


Interesting.
I don't know why it does not work in the second scenario but I don't think this is the proper way to proceed anyway because:

1. An idle timer will be better so that we can parse the buffer only if it is used cf what I said about `dired-do-query-replace-regexp` (https://github.com/Sarcasm/irony-mode/issues/249#issuecomment-153834852).
2. For some reasons irony-mode-hook is probably run twice because the c++ mode hooks run twice. This can cause issue if the minor mode is restarted in between the first request (I don't know).

I invite you to take a look at "emacs idle timer" so that you can find a more elegant, correct solution I believe.

**Comment by 3246251196** [comment]
Here is some progress I have made:
    ;;;;;;;;;;;;;;;;
    ;; DEFUN: Only do this when we are looking at the huge SOMETHING code base
    (setq hack-counter 0)
    (defun rjd-my-irony-start-irony-run ()
      (when (string-match "SOMETHING" buffer-file-name)
        (setq hack-counter (+ hack-counter 1))
        (when (= (% hack-counter 2) 0)
          (save-excursion
            (goto-char (point-max))
            (irony-completion-at-point-async)))))

Since this is only a problem for huge code bases, I only run when I know I am in my huge code base. Since the hooks are called twice (and as you say, they interfere) I only run on a even counts of the global counter. So long as I run `irony-completion-at-point-async` at the end of the buffer then everything gets parsed.

Hooked by:

    (add-hook 'irony-mode-hook
              '(lambda()
                 (run-with-timer 1.5 nil 'rjd-my-irony-start-irony-run)))

Personally, I only want to run this on start up and once. But, there is more work to be done and I like the idea of an idle timer - with the idle timer I would like to perhaps kill irony-mode and refresh it. I need to look into how irony is behaving for me personally before making those decisions.

So far, this is working well and there are no lock ups when I enter a file. So, as I said before, by the time I actually want to make a change, or access an instance of a class' members, the parsing has either already completed or is 90% of the way there.

Cheers.
