### ISSUE TITLE
compile_commands.json not being parsed

### ISSUE THREAD

**Issue by silgon** [Sarcasm/irony-mode#250]
I'm trying to use `irony-cdb-json-add-compile-commands-path` with the `compile_commands.json` generated by `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`. I copy the important part of that file next: 

```
[
{
  "directory": "/home/username/ros/indigo/catkin_ws/src/optitrack/optitrack_person",
  "command": "/usr/bin/c++ -std=c++11  -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\\\"optitrack_person\\\" -I/home/username/ros/indigo/catkin_ws/src/optitrack/optitrack_person/devel/include -I/home/username/ros/indigo/catkin_ws/src/optitrack/optitrack_person/include -I/home/username/ros/indigo/spencer_ws/devel/include -I/opt/ros/indigo/include    -o CMakeFiles/optitrack_person_node.dir/src/optitrack_person_node.cpp.o -c /home/username/ros/indigo/catkin_ws/src/optitrack/optitrack_person/src/optitrack_person_node.cpp",
  "file": "/home/username/ros/indigo/catkin_ws/src/optitrack/optitrack_person/src/optitrack_person_node.cpp"
}
]
```

So, I try to add that file with `irony-cdb-json-add-compile-commands-path` but it doesn't load. Am I doing something wrong?

*Side comment*: I also noticed something else. I have a `.clang_complete` file in some parent folder of the project, if or when I delete that file the message `irony process stopped` appears and then I cannot do anything, emacs then works at 100% of one of my CPUs and then I have to kill it.

**Comment by Sarcasm** [comment]
What is the output of `irony-cdb-menu`? I think there are some issues with `compile_commands.json` already, it may be a known bug.

Does the content of `cat .emacs.d/irony/cdb-json-projects` look correct?
I think the issue is about the tilde character not being expanded some times, so if you have ~/blah instead of /home/foo/blah you may want to try to edit manually.

**Comment by silgon** [comment]
It's being expanded. I thinks this is correct but I'm not sure so I copy it here:

```
(("/home/username/ros/indigo/catkin_ws/src/optitrack/optitrack_person/" . "/home/username/ros/indigo/catkin_ws/src/optitrack/optitrack_person/compile_commands.json"))
```

And as for the `irony-cdb-menu`, it tells me that no compilation database is been used.

**Comment by Sarcasm** [comment]
Do you call `irony-cdb-autosetup-compile-options` as shown here: https://github.com/Sarcasm/irony-mode/tree/3e9d37cb9a7b6feca2606ba6919b267deebe3531#configuration ?

**Comment by silgon** [comment]
Yes. But it always takes the  clang database `Compilation Database: irony-cdb-clang-complete`. And if I don't have the clang_complete file, emacs freezes with the message `irony process stopped` as I explained before. *This last behavior is happening only with the newest version of the melpa repositories.*

**Comment by silgon** [comment]
Somehow solved with one of the last updates from melpa. =)
