### ISSUE TITLE
Emacs 25.1.50.1 on OSX 10.11 freezes opening c++ file when server is not installed.

### ISSUE THREAD

**Issue by jwintz** [Sarcasm/irony-mode#255]
Whenever irony-server is built every thing works fine (completion, flychecking, etc). The command `M-x install-irony-server` works as well when invoked from a major mode that irony doesn't support.

However, when the server is not installed, opening a c/c++/objc file prompts a message to invite the user to install the server. This is where the freezing happens.

**Comment by guoxiao** [comment]
Same here. I have to disable irony in `.emacs` first and run command `M-x irony-install-server`.

**Comment by Sarcasm** [comment]
I do not have Emacs 25 yet, would be nice if you could provide a stacktrace. `M-x toggle-debug-on-quit RET` may be handy.

**Comment by jojojames** [comment]
Seeing the same thing on 24.5.1.

GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0, Carbon Version 157 AppKit 1404.34)
 of 2016-02-11 on jamesmac.local

Using project listed here.
https://github.com/jojojames/DummyXcode

Steps taken.
1. Remove irony folder from elpa
2. Start emacs (irony installs)
3. Enter project using projectile (server not yet installed)
4. Hangs until Ctrl+g

** compile_commands.json in root of project
Debugger entered--Lisp error: (quit)
  byte-code("\301\302\303!\207" [quit-flag t eval (ignore nil)] 2)
  irony--send-request-sync("get-compile-options" "/Users/james/Developer/DummyXcode/" "/Users/james/Developer/DummyXcode/DummyXcode/ViewController.m")
  irony-cdb-libclang--server-exact-flags("/Users/james/Developer/DummyXcode/compile_commands.json")
  irony-cdb-libclang--get-compile-options()
  irony-cdb-libclang(get-compile-options)
  byte-code("\302!\211\203\303\304	\211@@\262	\211@A\262E\"\210)\302\207" [compilation-database it get-compile-options throw found] 7)
  byte-code("\303\211\205\n@\304\305\306\217\210\nA\211\204\303*\207" [irony-cdb-compilation-databases compilation-database --dolist-tail-- nil err (byte-code "\302!\211\203\303\304	\211@@\262	\211@A\262E\"\210)\302\207" [compilation-database it get-compile-options throw found] 7) (((debug error) (message "Irony CDB: error in compilation database: %S" err)))] 4)
  irony-cdb--autodetect-compile-options()
  irony-cdb-autosetup-compile-options()
  run-hooks(irony-mode-hook irony-mode-on-hook)
  irony-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook objc-mode-hook objc-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook c-mode-common-hook objc-mode-hook objc-mode-hook))
  run-mode-hooks(objc-mode-hook)
  objc-mode()
  set-auto-mode-0(objc-mode nil)
  set-auto-mode()
  #[0 "\300 \207" [set-auto-mode] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [set-auto-mode] 1 "\n\n(fn)"])
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer ViewController.m> "~/Developer/DummyXcode/DummyXcode/ViewController.m" nil nil "~/Developer/DummyXcode/DummyXcode/ViewController.m" (46473130 16777224))
  find-file-noselect("/Users/james/Developer/DummyXcode/DummyXcode/ViewController.m" nil nil nil)
  find-file("/Users/james/Developer/DummyXcode/DummyXcode/ViewController.m")
  projectile-find-file()
  projectile-switch-project-by-name("~/Developer/DummyXcode/" nil)
  projectile-switch-project(nil)
  call-interactively(projectile-switch-project nil nil)
  command-execute(projectile-switch-project)

** compile_commands.json removed from project
works.

irony configuration
(use-package irony
  :config
  (add-hook 'objc-mode-hook 'irony-mode)
  ;; replace the `completion-at-point' and `complete-symbol' bindings in
  ;; irony-mode's buffers by irony-mode's function
  (defun my-irony-mode-hook ()
    (define-key irony-mode-map [remap completion-at-point]
      'irony-completion-at-point-async)
    (define-key irony-mode-map [remap complete-symbol]
      'irony-completion-at-point-async))
  (add-hook 'irony-mode-hook 'my-irony-mode-hook)
  (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))

**Comment by Sarcasm** [comment]
Could you try to evaluate this function (e.g: in `*scratch*` buffer):

```el
(defun irony--send-request-sync (request &rest args)
  "Send a request to irony-server and wait for the result."
  (let* ((id irony--sync-id)
         (callback (list #'irony--sync-request-callback id)))
    (setq irony--sync-id (1+ irony--sync-id))
    (with-local-quit
      (let ((process (irony--get-server-process-create)))
        (when process
          (apply 'irony--send-request request callback args)
          (while (not (= id (car irony--sync-result)))
            (accept-process-output process))
          (cdr irony--sync-result))))))
```

**Comment by jojojames** [comment]
Steps
1. Remove irony folder from elpa
2. Run emacs installing irony
3. Evaluate above function.

Returns -> irony--send-request-sync
Open file in *xcode dummy project*, file opens as expected.
==
Peace of mind test.
Open Emacs again and open iOS file from *xcode dummy project* (no evaluation of above function), Emacs hangs.

**Comment by Sarcasm** [comment]
Not sure to understand, so the patch worked?

**Comment by jojojames** [comment]
Yes, it looks like it.

**Comment by Sarcasm** [comment]
Ok, thank you for testing it, I will commit it then.

**Comment by Sarcasm** [comment]
Closing.
