### ISSUE TITLE
irony-mode  in Windows OS

### ISSUE THREAD

**Issue by juvasquezg** [Sarcasm/irony-mode#260]
I'm interested to use irony-mode in Windows, do you have a more detailed tutorial? please. Thank you.

I try with MinWG and the Guide [Wiki](https://github.com/Sarcasm/irony-mode/wiki/Setting-up-irony-mode-on-Windows-using-Msys2-and-Mingw-Packages)

But I get message..

```
"Standard library doesn't support C++11!"
```

Thank You So Much.

**Comment by Sarcasm** [comment]
What is your compiler?

There is nothing more than the README (https://github.com/Sarcasm/irony-mode/tree/8a4b1019a36c08a2158a83af3ec29dcae63f699f#windows-considerations) and the wiki for Windows.

Eventually some issues but I think you are the first one to stumble upon this one.

**Comment by juvasquezg** [comment]
Thank you so Much.

I use gcc with MinGW.

```
git clone https://github.com/Sarcasm/irony-mode.git
cd irony-mode/server
mkdir build
cmake -DLIBCLANG_LIBRARY="C:/Program Files/LLVM/bin/clang.dll" -G "MinGW Makefiles" ..
```
clang.dll is in C:/Program Files/LLVM/bin/clang.dll but I get

```bash
-- Detecting libclang builtin headers directory -- fail
````

And the Full log:

```bash
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified
-- Performing Test HAS_STDCXX11
-- Performing Test HAS_STDCXX11 - Success
-- Performing Test HAS_CXX11_STDLIB
-- Performing Test HAS_CXX11_STDLIB - Success
-- C++11 compiler option(s): -std=c++11
-- Found LibClang: C:/Program Files/LLVM/lib/libclang.lib
-- Detecting libclang builtin headers directory
-- Detecting libclang builtin headers directory -- fail
CMake Warning at cmake/CheckLibClangBuiltinHeadersDir.cmake:82 (message):
  CheckLibClangBuiltinHeadersDir: failed to compile checker, please report.

	Compile output:
	  Change Dir: C:/home/.emacs.d/irony-mode/server/build/CMakeFiles/CMakeTmp



  Run Build Command:"C:/MinGW/bin/mingw32-make.exe" "cmTC_e5e92/fast"

  C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_e5e92.dir\build.make
  CMakeFiles/cmTC_e5e92.dir/build

  mingw32-make.exe[1]: Entering directory
  `C:/home/.emacs.d/irony-mode/server/build/CMakeFiles/CMakeTmp'

  Building CXX object
  CMakeFiles/cmTC_e5e92.dir/LibClangDiagnosticsChecker.cpp.obj

  C:\MinGW\bin\g++.exe @CMakeFiles/cmTC_e5e92.dir/includes_CXX.rsp
  -fno-exceptions -o
  CMakeFiles\cmTC_e5e92.dir\LibClangDiagnosticsChecker.cpp.obj -c
  C:\home\.emacs.d\irony-mode\server\build\CMakeFiles\CMakeTmp\LibClangDiagnosticsChecker.cpp


  Linking CXX executable cmTC_e5e92.exe

  "C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_link_script
  CMakeFiles\cmTC_e5e92.dir\link.txt --verbose=1

  "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f
  CMakeFiles\cmTC_e5e92.dir/objects.a

  C:\MinGW\bin\ar.exe cr CMakeFiles\cmTC_e5e92.dir/objects.a
  @CMakeFiles\cmTC_e5e92.dir\objects1.rsp

  C:\MinGW\bin\g++.exe -fno-exceptions -Wl,--whole-archive
  CMakeFiles\cmTC_e5e92.dir/objects.a -Wl,--no-whole-archive -o
  cmTC_e5e92.exe -Wl,--out-implib,libcmTC_e5e92.dll.a
  -Wl,--major-image-version,0,--minor-image-version,0
  @CMakeFiles\cmTC_e5e92.dir\linklibs.rsp


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x6c):
  undefined reference to `clang_createIndex'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0xb0):
  undefined reference to `clang_parseTranslationUnit'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0xfc):
  undefined reference to `clang_getNumDiagnostics'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x121):
  undefined reference to `clang_getDiagnostic'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x12a):
  undefined reference to `clang_defaultDiagnosticDisplayOptions'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x13a):
  undefined reference to `clang_formatDiagnostic'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x156):
  undefined reference to `clang_getCString'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x186):
  undefined reference to `clang_disposeString'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x192):
  undefined reference to `clang_disposeDiagnostic'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x1b1):
  undefined reference to `clang_disposeTranslationUnit'


  CMakeFiles\cmTC_e5e92.dir/objects.a(LibClangDiagnosticsChecker.cpp.obj):LibClangDiagnosticsChecker.cpp:(.text+0x1bd):
  undefined reference to `clang_disposeIndex'

  collect2.exe: error: ld returned 1 exit status

  mingw32-make.exe[1]: *** [cmTC_e5e92.exe] Error 1

  mingw32-make.exe[1]: Leaving directory
  `C:/home/.emacs.d/irony-mode/server/build/CMakeFiles/CMakeTmp'

  mingw32-make.exe: *** [cmTC_e5e92/fast] Error 2



Call Stack (most recent call first):
  src/CMakeLists.txt:8 (check_libclang_builtin_headers_dir)


-- Irony package version is '0.2.0-cvs4'
-- Found emacs: C:/emacs-24.5/bin/emacs.exe
-- Configuring done
-- Generating done
-- Build files have been written to: C:/home/.emacs.d/irony-mode/server/build
```

TKS :)

**Comment by juvasquezg** [comment]
Excuse me a Typo

```bash
cmake -DLIBCLANG_LIBRARY="C:/Program Files/LLVM/bin/libclang.dll" -G "MinGW Makefiles" ..
```

But not found libclang...

**Comment by Sarcasm** [comment]
You should not need to specify LIBCLANG_LIBRARY if you have a standard installation.
Anyway, it seems irony picked it up itself:

```
...
 -- Found LibClang: C:/Program Files/LLVM/lib/libclang.lib
```

Taking the `.lib` is not right howewer I think.
You could try to edit the cache manually by calling `cmake-gui .` in the build directory.

For irony server to work you will need to have libclang.dll is available your PATH (or at least in emacs's `exec-path`) but I don't think this is the error here.

In server/cmake/modules/FindLibClang.cmake I have the following piece of code:

```cmake

# On Windows with MSVC, the import library uses the ".imp" file extension
# instead of the comon ".lib"
if (MSVC)
  find_file(LIBCLANG_LIBRARY libclang.imp
    PATH_SUFFIXES LLVM/lib
    DOC "The file that corresponds to the libclang library.")
endif()
```

Maybe something should be done for MinGW too, I invite you to put some debug in the file and experimente with the CMake cache with `cmake-gui` or equivalent.

**Comment by juvasquezg** [comment]
Thank you!!

cmake-gui with Visual Studio 2013 is ready. Now I get 

```bash
(void-function irony-cdb-autosetup-compile-options)
```
in emacs.

Thank you so much!!!

**Comment by Sarcasm** [comment]
You installed irony-mode manually? that is not using a package manager and MELPA?
If that's the case you may want to write the autoload yourselves, or even add `(require 'irony)` to your `.emacs` or equivalent.

**Comment by juvasquezg** [comment]
From Melpa... I compile with cmake-gui and Visual Studio 2013 but not work :(

**Comment by Sarcasm** [comment]
MELPA should provide the autoload, do you get anything if you type:

`M-x irony-[TAB]`.

Did `(require 'irony)` returned an error? You can type that in the scratch buffer.

BTW, any reason to use mingw over the windows compile `cl` or `clang-cl`?

**Comment by juvasquezg** [comment]
mmm I don't know :( 

Now I get 

```bash
 symbol's value as variable is void: irony-completion-mode
```

**Comment by 3246251196** [comment]
I can possibly help here since I run irony-mode at work on windows.

The error you posted about variable is `void: irony-completion-mode` is due to your version of company-irony I believe. A few months ago that variable was removed. 

Also, I never use MELPA so I don't do any of this using the package manager. I think the thing to do to sort that problem out is go to: https://github.com/Sarcasm/company-irony and download the latest zip, extract it to your emacs.d and have that one load up. I have little experience with MELPA, so you may need to remove it (the older version or - perhaps you do not have it at all - of comapny-irony) from your melpa startup folder and make sure you load the new version.

As Sarcasm said you should make sure you have hooks set up when you load c/cpp/objc files so that irony-mode kicks in.

Cheers.

**Comment by Sarcasm** [comment]
Ok, and otherwise regarding the use of MELPA, it should work if you make sure to use MELPA stable everywhere or nowhere, but do not mix both "MELPA" and "MELPA stable".

If you want the latest for irony, do not use MELPA stable, it has been quite some time since a release has been made.

**Comment by juvasquezg** [comment]
Thank you,

mmm I included from github (downloaded the latest zip) (https://github.com/Sarcasm/company-irony) and (https://github.com/Sarcasm/irony-mode) but not work.  :(

```bash
cannot complete at point
```

mmm I don't know :(

How do I know if irony-server is really installed?

**Comment by juvasquezg** [comment]
In .el files Company is great. I Attach picture.  (https://www.dropbox.com/s/qfetukczoyy69db/CompanyMode.png?dl=0)

**Comment by 3246251196** [comment]
cd ~/.emacs.d/irony/bin/
    ./irony-server.exe --version

Firstly, can you do that?

If you can, good.

Have you got a simple c++ project? If so, go to it in the root directory. For example, I might have a helloworld project in windows.

   cd helloworld

in here, remember that you MUST have a .clang_complete (as far as I am concerned, I have never used this JSON stuff). That must have the flags that clang compiler will use.

So in helloword I might have: ls -a
main.cpp
.clang_complete (this file contains the compiler flags that you ought to supply)

Then, when I C-x C-f to open up main.cpp in a buffer I would run C-h v minor-mode-alist : I would ensure that I can see irony-mode in there somewhere (it should say irony somewhere on the normal bar, but I have a custom one). This means irony is enabled.

If all found so far good. Then, in main.cpp I would do something like:

    #include <vector>
    int main()
    {
       std::***
       return 0;
    }

*** - put the cursor here and run M-x company-complete

Then see what happens.

**Comment by juvasquezg** [comment]
Thanks you for your patience.

I did the steps that you indicate me in a main.c file. Then I made 
```bash
Mx company-complete  
```
I see the next image (https://www.dropbox.com/s/mwwb1dwg1748t90/CompanyComplete.png?dl=0) . I think it work. I need to Customize.

Fantastic.

**Comment by 3246251196** [comment]
Good stuff. Yes, you probably need to set company-backends to include company-irony. That way when you run company-complete it should pick up that you want to use company-irony for the mode you are in.

THat is up to you to hack with, I have something like:

;;;;;
;; MODE :
(require 'company)
(setq company-backends '(company-c-headers
                         company-elisp
                         company-irony
                         company-jedi
                         company-capf
                         (company-dabbrev-code
                          company-gtags
                          company-etags
                          company-keywords)
                         company-files
                         company-dabbrev))

And
;; PREF: Use this for gui autocompletion (F10 is used for options along the top of emacs window)
(define-key global-map [f11] 'company-complete)

For you, if you want a quick fix you could do something like:
(define-key global-map [f11] 'company-irony)

Actually, I also configure my setup so I do not get popups automatically, i must press a button - so this may not work.

Anyway, good luck.

**Comment by juvasquezg** [comment]
Good Morning, return ;)

I saw a tutorial on youtube showing the "docstring" in one side within the code block, as shown in this photo. (https://www.dropbox.com/s/us45ayg5trczgej/TutoOfInternet.png?dl=0)

But in my Windows show the "docstring" in the bottom of the buffer as show in this picture (https://www.dropbox.com/s/nawfi24wu63v3ee/MyPCEmacs.png?dl=0)  it is for Windows?

The docstring say:

```bash
Adds a and b, return the results.
```

Thank you So much.

**Comment by 3246251196** [comment]
Hi,

I believe this is the difference between AutoComplete and Company.

With company I get docstrings (where appropriate) in the minibuffer (as in your 2nd example). I think with AutoComplete using Irony you can get docstring along side. I do not use AC so I cannot help. I am also not sure if company can do the same thing as you request.

**Comment by Sarcasm** [comment]
Great if you were able to get it working.

Yes, this is how company works. There might be some other way to display this information, I'm not sure, but you should ask the company folks about that, company-irony just cares about providing the information.

**Comment by juvasquezg** [comment]
Perfect, I am very thankful. Answered me all my questions.

Ready for learn.

Thank you.
