### ISSUE TITLE
Request for Makefile GNU/Linux x64, GCC

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#262]
Sarcasm, can I please request a Makefile so I can start hacking around with the source code please?

I am so lost in CMake - so much templated/generalised junk I cannot believe. If you can just let me know the the simple modules I can create a simple Makefile and type make!! This CMake is crazy and I have not the time to learn it.

I am requesting simple Makefile for a GNU/Linux x64 / gcc. Cheers (don't worry about knowing where my particular libclang is, I can solve that myself), I just want something like

irony-server:
    g++ -lclang -I.... blah blah -o irony-server

Thank you.

**Comment by 3246251196** [comment]
Actually, I have just hacked one up and it seems to work having tested out the binary using command line (that is, I get the same completions using this hacked binary with the completions from emacs using the official binary).

    cat Makefile 
    all:
    	g++ --std=c++11 -I/home/rjd/Downloads/irony-mode-master/server/src/support -I/usr/lib/llvm-3.7/include Command.cpp Irony.cpp main.cpp TUManager.cpp support/CommandLineParser.cpp support/TemporaryFile.cpp -lclang-3.7 -o bin/irony-server
    
    clean:
    	rm bin/irony-server

It just means I can work on somethings like perhaps serializing TU objects for large objects etc!

If I am missing anything, let me know.

**Comment by Sarcasm** [comment]
You are missing 2 things I believe.

In my command line I also have the following things which were set by CMake:

```
-DCLANG_BUILTIN_HEADERS_DIR=\"/usr/lib/clang/3.5.1/include\"
-DIRONY_PACKAGE_VERSION=\"0.2.0-cvs5\"
```

**Comment by 3246251196** [comment]
Ahh yes. I just #defined package version in main.cpp and I guess I will put in this extra -DCLANG_....

Though so far I have not needed it.

Cheers for the help. I can close this now.
