### ISSUE TITLE
missing new line for unsaved file content

### ISSUE THREAD

**Issue by edvorg** [Sarcasm/irony-mode#265]
Hi. Trying to use irony, but completion doesn't work.
Server process stops with error in logs:

```
missing new line for unsaved file content
```

I use latest irony from unstable melpa.
My Clang version is:

```
3.6.2-1
```

Emacs version:

```
24.5.1
```

**Comment by edvorg** [comment]
Completio frontend - `company`

**Comment by edvorg** [comment]
If it does matter, I start emacs under docker container via ssh session

**Comment by 3246251196** [comment]
#58 

Are these related?

**Comment by edvorg** [comment]
Hmm. No I don't think so, because I start emacs in ssh session, I don't use tramp here.

**Comment by 3246251196** [comment]
Okay. What happens when you run `file thefile` on the file (thefile) you are trying to get completions on.

**Comment by edvorg** [comment]
Sorry for the delay. It's `C source, ASCII text`

**Comment by edvorg** [comment]
File has cc extension

**Comment by Sarcasm** [comment]
> If it does matter, I start emacs under docker container via ssh session

I'm not sure to understand your setup, any chance I can reproduce it with a minimal setup?

**Comment by edvorg** [comment]
The setup is following. I have an arch Linux VM, where I run docker
container with ububtu image containing my dev environment and enacs. I
share my host X server socket with that container to launch x applications
like clion and emacs under docker. So this shouldn't be different if I just
run it under ububtu system without docker. I try to use irony with my mixed
c/c++ project. It has cmake root project and several subproject's. So I
tried to use completion in one of the subproject's files by it just say
process exited and put the line I said before to the log file. I can't
share the code but I could try to create simple project reproducing this
bug if it would help.
