### ISSUE TITLE
Failed to make irony-mode to work

### ISSUE THREAD

**Issue by leopoldfreeman** [Sarcasm/irony-mode#267]
I downloaded the snapshot zip file from master branch,  extracted to folder ~/.emacs.d/lisp/irony-mode.

Here is my configurations:
```lisp
(add-to-list 'load-path "~/.emacs.d/lisp/irony-mode")

(require 'irony)
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
```

I can 'M+x irony-install-server' successfully.
But when I open a cpp file, I got this error:
>File mode specification error: (void-function irony-cdb-autosetup-compile-options)

And M+x irony-TAB only shows 5 commands (No irony-cdb command):
irony-completion-at-point-async
irony-install-server
irony-mode
irony-server-kill
irony-version

irony version is: 0.2.0-cvs4
Emacs version is: 24.3.1

**Comment by Sarcasm** [comment]
If you install manually you have to require irony or generate the autoloads manually. 

The quick fix should be to put `(require 'irony)`, you may do the same for company-irony and flycheck-irony

**Comment by Sarcasm** [comment]
Note, if you install with a package manager, e.g from MELPA, then you don't need to do this.

**Comment by leopoldfreeman** [comment]
You may overlooked it, I already put (require 'irony) at the 3rd line of my configuration. I tried installing from MELPA, it finally worked (M+complete-at-point). But ac-irony failed to work, I'll look into it tomorrow. I think I must read some lisp doc or I can be shot by anyone...
