### ISSUE TITLE
Fails when the compiler is prefixed with `ccache`

### ISSUE THREAD

**Issue by atilaneves** [Sarcasm/irony-mode#272]
One way to use ccache with cmake is to list it before the compiler name when calling CMake:

    CC='ccache clang' CXX='ccache clang++' cmake ...

That means that the commands in the compilation database start with `ccache clang++`. When reading it Irony correcly takes out the compiler (the first parameter) in order to get the options. But if ccache is preceding it, it ends up passing the compiler itself as part of `compile_options` in `irony--send-parse-request`. As a result, the compilation fails and no autocompletion happens.

**Comment by arximboldi** [comment]
@Sarcasm @atilaneves This issue was not completely fixed: the merged change only worked for the `libclang` database. I just opened a new pull request that fixes it for `json` #311
