### ISSUE TITLE
tuning irony-mode to coexist with other modes

### ISSUE THREAD

**Issue by mambolevis** [Sarcasm/irony-mode#275]
Hi, 
1.)  after downloading  (company-irony, ac-irony and irony-mode) using el-get, I installed the server and tested the auto completion, great. In the case of the local includes, I tried both .clang_complete and (setq irony-libclang-additional-flags (append '("-I" "inc") irony-libclang-additional-flags)) but without success. It is necessary to setup other package, if yes, how to do it?

2.) When I use irony-mode, other packages stooped to work e.g (auto-complete-c-headers, flymake-google-cpplint, google-c-style). I can't obtain auto completion when typing #include <string> , (I used windows VC headers). How can I solve the problem, and make these modes coexist? 

Platform: Windows 10.

Thanks,
Levis

**Comment by mambolevis** [comment]
I found the following problem today: File mode specification error: (void-function irony-cdb-autosetup-compile-options).

**Comment by mambolevis** [comment]
I solve problems 2 and 3. The problem  2 is more a conceptual problem (auto-complete) and company are two different worlds and probably (not sure 'cause I'm just just starting with emacs) . The 3rd problem was solved with a better coordination between el-get and elpa. There was a problem in one dependency. 

Question: I would like to have all necessary packages to improve to achieved a tuned company based C++ IDE (intellisense, debugging)  , what packages should I installed and which dependencies should I consider? Until now I have:
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; company  (completion framework for Emacs)
(load "~/emacs/config/config-company.el")
(load "~/emacs/config/config-company-irony.el")
(load "~/emacs/config/config-ac-irony.el")
(load "~/emacs/config/config-irony-mode.el")
(load "~/emacs/config/config-flycheck-irony.el")

**Comment by Sarcasm** [comment]
> 1.) after downloading (company-irony, ac-irony and irony-mode) using el-get, I installed the server and tested the auto completion, great. In the case of the local includes, I tried both .clang_complete and (setq irony-libclang-additional-flags (append '("-I" "inc") irony-libclang-additional-flags)) but without success. It is necessary to setup other package, if yes, how to do it?

I am not well versed in non-trivial Windows setup. You may need the vcvars available in your Emacs environment, 

> 2.) When I use irony-mode, other packages stooped to work e.g (auto-complete-c-headers, flymake-google-cpplint, google-c-style). I can't obtain auto completion when typing #include , (I used windows VC headers). How can I solve the problem, and make these modes coexist?

irony does not support include completion, but a third party package exists for that purpose, see http://melpa.org/#/company-irony-c-headers


> Question: I would like to have all necessary packages to achieve a tuned company based C++ IDE (intellisense, debugging) , what packages should I installed and which dependencies should I consider? Until now I have:

I cited company-irony-c-headers above.
I would remove ac-irony, which is inferior to company-irony, I don't see a reason to use it for now.

Personally I only use irony mode stuff but there are some other popular packages such as:

* https://github.com/atilaneves/cmake-ide
* https://github.com/Andersbakken/rtags
* https://github.com/abingham/emacs-ycmd

**Comment by mambolevis** [comment]
Thanks a lot!
