### ISSUE TITLE
irony yields error with the same settings that are able to build the project

### ISSUE THREAD

**Issue by blaenk** [Sarcasm/irony-mode#276]
I'm getting errors in irony flycheck that I don't get when I build my project, in fact I get _no_ errors when I build my project. I'm trying to figure out where the discrepancy lies. From what I can tell, it seems like irony is correctly picking up the compilation flags/settings, so I'm not sure what is causing this to occur.

I think it was a recent irony update, but I'm not sure.

build/compile_commands.json:
``` json
{
  "directory": "/home/blaenk/code/cpp/puzzles/build/source",
  "command": "/usr/bin/clang++    -I/home/blaenk/code/cpp/puzzles/googletest/googletest/include -I/home/blaenk/code/cpp/puzzles/googletest/googletest -I/home/blaenk/code/cpp/puzzles/googletest/googlemock/include -I/home/blaenk/code/cpp/puzzles/googletest/googlemock  -Wall -Wextra -Werror -pedantic -g3   -std=gnu++14 -o CMakeFiles/puzzles.dir/main.cc.o -c /home/blaenk/code/cpp/puzzles/source/main.cc",
  "file": "/home/blaenk/code/cpp/puzzles/source/main.cc"
},
```

irony-cdb-menu:
```
-I/home/blaenk/code/cpp/puzzles/googletest/googletest/include -I/home/blaenk/code/cpp/puzzles/googletest/googletest  -I/home/blaenk/code/cpp/puzzles/googletest/googlemock/include -I/home/blaenk/code/cpp/puzzles/googletest/googlemock -Wall -Wextra -Werror -pedantic -g3 -std=gnu++14
```

The error I'm getting probably doesn't matter, but it is:

```
no matching constructor for initialization of '::testing::internal::CodeLocation
```

It's applied to a macro invocation of `TEST` (googletest) that looks like this:

``` cpp
TEST(Lol, Heh) {
  EXPECT_EQ(1, 1);
}
```

Of course, everything was working perfectly fine about a week or two ago. I just got back to working on this and noticed that irony is complaining. I guess there was also a clang release since then (3.7.1?). I'm not sure what else to investigate.

**Comment by Sarcasm** [comment]
If you do `~/.emacs.d/bin/irony-server --version` you will also see which version of libclang irony is using.
Check that your `clang++ --version` matches this.


If the version is the same and you have no errors when doing what follows, then I'm a bit clueless :

    clang++ -fsyntax-only -I/home/blaenk/code/cpp/puzzles/googletest/googletest/include -I/home/blaenk/code/cpp/puzzles/googletest/googletest  -I/home/blaenk/code/cpp/puzzles/googletest/googlemock/include -I/home/blaenk/code/cpp/puzzles/googletest/googlemock -Wall -Wextra -Werror -pedantic -g3 -std=gnu++14 /home/blaenk/code/cpp/puzzles/source/main.cc

I

**Comment by blaenk** [comment]
Did your message get cut off?

Yeah that line works fine without any errors at all. This is why I'm confused as to where the discrepancy lies.

Here's the output:

```
λ ~/code/cpp/puzzles → master# ∷ +3
» ~/.emacs.d/cache/irony/bin/irony-server --version
irony-server version 0.2.0-cvs4
clang version 3.7.1 (tags/RELEASE_371/final)

λ ~/code/cpp/puzzles → master# ∷ +3
» clang++ --version
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

I'll try rebuilding it anyways.

For whatever it's worth, I have `irony-user-dir` set to `"/home/blaenk/.emacs.d/cache/irony"`. But I don't remember that being a problem previously. I don't get any errors about the server not being found or needing to be built or anything.

I'm going to try rebuilding it. I'm simply running `irony-install-server`. I ran `irony-server-kill` and then `rm`'ed the server binary. The install command it shows is:

```
cmake -DCMAKE_INSTALL_PREFIX\=/home/blaenk/.emacs.d/cache/irony /home/blaenk/.emacs.d/elpa/irony-20160123.1307/server && cmake --build . --use-stderr --config Release --target instal
```

It looks correct to me.

**Comment by blaenk** [comment]
Here's the `irony-install-server` output:

```
-*- mode: compilation; default-directory: "/tmp/build-irony-server-0.2.0-cvs4/" -*-
Compilation started at Wed Jan 27 13:24:50

cmake -DCMAKE_INSTALL_PREFIX\=/home/blaenk/.emacs.d/cache/irony /home/blaenk/.emacs.d/elpa/irony-20160123.1307/server && cmake --build . --use-stderr --config Release --target install
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified
-- Performing Test HAS_STDCXX11
-- Performing Test HAS_STDCXX11 - Success
-- Performing Test HAS_CXX11_STDLIB
-- Performing Test HAS_CXX11_STDLIB - Success
-- C++11 compiler option(s): -std=c++11
-- Found LibClang: /usr/lib64/libclang.so  
-- Detecting libclang builtin headers directory
-- Detecting libclang builtin headers directory -- success
-- Irony package version is '0.2.0-cvs4'
-- Found emacs: /usr/bin/emacs
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build-irony-server-0.2.0-cvs4
Scanning dependencies of target irony-server
[ 14%] Building CXX object src/CMakeFiles/irony-server.dir/support/CommandLineParser.cpp.o
[ 28%] Building CXX object src/CMakeFiles/irony-server.dir/support/TemporaryFile.cpp.o
[ 42%] Building CXX object src/CMakeFiles/irony-server.dir/Command.cpp.o
[ 57%] Building CXX object src/CMakeFiles/irony-server.dir/Irony.cpp.o
[ 71%] Building CXX object src/CMakeFiles/irony-server.dir/TUManager.cpp.o
[ 85%] Building CXX object src/CMakeFiles/irony-server.dir/main.cpp.o
[100%] Linking CXX executable ../bin/irony-server
[100%] Built target irony-server
Install the project...
-- Install configuration: "Release"
-- Installing: /home/blaenk/.emacs.d/cache/irony/bin/irony-server

Compilation finished at Wed Jan 27 13:24:57
```

**Comment by blaenk** [comment]
Rebuilding the server seems to have fixed it, even though it said that it was using the correct clang version.

**Comment by Sarcasm** [comment]
One hypothesis.
Irony is able to find the new libclang at runtime because the .so is in the ld search path.
But irony is not able to find the Clang builtin includes because they changed directory, moving from `/lib/clang/3.7.0/include` to `/lib/clang/3.7.1/include` for example. Irony-mode find this path at CMake generation time.

**Comment by blaenk** [comment]
That does sound plausible. Thanks. From now on if I run into a problem like this where I didn't change anything other than perhaps a new libclang version being released, I'll try rebuilding it first.

Is there a recommended process for this? Currently I kill the server, disable irony mode, then rm the binary and then run the install server command to rebuild it. I'm not sure if any of these is unnecessary. It would be nice perhaps if there were an `M-x irony-rebuild-server` or something that automated this.

**Comment by Sarcasm** [comment]
Just `irony-install-server` I think.
It already kills irony-server.
Install should automatically override the old version.
No need to disable irony-mode, at the next request, it will see that it has no irony-server running so it will start a new one.

**Comment by blaenk** [comment]
Ah, beautiful then! Thanks!
