### ISSUE TITLE
no C-struct member name completion in newer style initialisation

### ISSUE THREAD

**Issue by Dickby** [Sarcasm/irony-mode#284]
In newer C standards it's possible to initialize a struct like this:

```
struct foo{
int aaa;
int bbb;
int ccc;
};

struct foo bar ={
.aaa = 1,
.bbb = 2,
.ccc = 3
};
```

irony won't complete the struct member-names in the initialisation-block.
Feel free to close this issue if it's not possible to complete the member-names due to clang.

**Comment by Sarcasm** [comment]
if irony-mode does not complete on this when called explicitely with `M-x company-irony RET` then it's a libclang missing feature indeed.

**Comment by Dickby** [comment]
It seems to be a clang thing.
I close this issue.
Thanks for the fast response.
