### ISSUE TITLE
Completion placeholders without yasnippet

### ISSUE THREAD

**Issue by aport** [Sarcasm/irony-mode#295]
company-go and company-rtags (and possibly more) fill in function argument placeholders without using yasnippet. 

They appear to use the function company-template-c-like-templatify.

Would it be possible for irony to use the same mechanism and thus eliminate a dependency?

**Comment by Sarcasm** [comment]
This is something I would like to have yes. Should not be too difficult (contribution welcome). :)

**Comment by aport** [comment]
Should the change go in irony-completion.el or in company-irony? The latter calls into irony-completion (irony-completion-post-complete).

My elisp is pretty weak but the following worked for me:

(defun irony-completion-post-complete (candidate)
  (let ((str (irony-completion-post-comp-str candidate)))
    (insert str)
    (company-template-c-like-templatify str)))

**Comment by Sarcasm** [comment]
Seems to work resonably well. Redefining `irony-completion-post-complete` is not the right solution to include in company-irony though.

**Comment by aport** [comment]
Okay, thank you. I'll make the modification in irony-completion. Should I remove irony-snippet in the same pull request?

**Comment by Sarcasm** [comment]
I want `company-template-c-like-templatify` to appear in company-irony only.
I would check in company-irony the result of `irony-snippet-available-p`, if it exists use the current method, otherwise fallback to company built-in snippet mechanism.

**Comment by aport** [comment]
Ok, closing this and moving to company-irony repository.
