### ISSUE TITLE
error when #include

### ISSUE THREAD

**Issue by mambolevis** [Sarcasm/irony-mode#298]
Hi Sarcasm,

When including a header file `#include` on top of previous existing headers, the following problem 
appears.

![image](https://cloud.githubusercontent.com/assets/13024208/14353083/d8b12e40-fcd7-11e5-80c5-1b2fa5829825.png)

Regards.

**Comment by 3246251196** [comment]
https://github.com/Sarcasm/irony-mode/wiki/Setting-up-irony-mode-on-Windows-using-MSVC#i-am-getting-a-gosh-darn-assertion

A quick workaround would be this, perhaps?

**Comment by mambolevis** [comment]
Hi @3246251196 

yes, it works. I changed the version of irony and forgot to patch it. Now both versions: `irony 0.2.0 (20160317.1527 from Melpa)` and `irony-0.2.0-cvs4` have the suggested work around and the problem is solved, thanks!
Questions:

1. What is the difference between `versions 0.2.0 and 0.2.0-cvs4` ?
2. Is there any plan to release a new version?

Gruss,

**Comment by Sarcasm** [comment]
> 1. What is the difference between versions 0.2.0 and 0.2.0-cvs4 ?

It depends, but 0.2.0 is more recent than 0.2.0-cvs4. When 0.2.0 was in developement it was named 0.2.0-cvs1, ..., 0.2.0-cvs4. Then when the version was ready it has been named 0.2.0.

> 2. Is there any plan to release a new version?

If you have 0.2.0 you are up-to-date, to this day there is no new commit in irony-mode.
It is expected that new versions will appear in the future.
