### ISSUE TITLE
parsing failed for files opened with (helm-)projectile-find-file

### ISSUE THREAD

**Issue by vasw** [Sarcasm/irony-mode#309]
Hi,

I'm using irony, company-irony, flycheck-irony.

Everything works as expected for files opened with find-files or helm-find-files.

For files opened with projectile-find-file or helm-projectile-find-file I get the error: "Error from syntax checker irony: parsing failed".

Parsing from command line works (via ~/.emacs.d/irony/bin/irony-server -d -i).

Any idea?
Thanks.

Versions: GNU Emacs 24.5.1, irony 20160511.708,  projectile 20160522.919

**Comment by vasw** [comment]
Sometimes I'm getting the error also with find-files.

Looking at the irony log file, I've observed that when the parsing fails, the cpp file name is included at the end of flags array.

Log line when parsing fails:

`execute: Command{action=Command::Parse, file='/home/v/Projects/r/l/s/g/i/font.cpp', dir='', line=0, column=0, flags=['-x', 'c++', '-working-directory', '/home/v/projects/r/l/build/debug/s/g/i', '-DBOOST_ALL_DYN_LINK', '-I/home/v/projects/r/l/s', '-I/usr/sys/api/inc', '-std=c++11', '-Wall', '-Wextra', '-Wunused', '-Wuninitialized', '-Winit-self', '-Woverloaded-virtual', '-Wnon-virtual-dtor', '-Wsign-promo', '-Wpointer-arith', '-g', '-O0', '--coverage', '-fprofile-arcs', '-ftest-coverage', '/home/v/projects/r/l/s/g/i/font.cpp'], unsavedFiles.count=1, opt=off}
`

Log line when parsing works:

`execute: Command{action=Command::Parse, file='/home/v/projects/r/l/s/g/i/size.cpp', dir='', line=0, column=0, flags=['-x', 'c++', '-working-directory', '/home/v/projects/r/l/build/debug/s/g/i', '-DBOOST_ALL_DYN_LINK', '-I/home/v/projects/r/l/s', '-I/usr/sys/api/inc', '-std=c++11', '-Wall', '-Wextra', '-Wunused', '-Wuninitialized', '-Winit-self', '-Woverloaded-virtual', '-Wnon-virtual-dtor', '-Wsign-promo', '-Wpointer-arith', '-g', '-O0', '--coverage', '-fprofile-arcs', '-ftest-coverage'], unsavedFiles.count=1, opt=off}`

**Comment by vasw** [comment]
So, the problem was that /home/v/projects was a symlink to /home/v/Projects .

Deleting the symlink solved the issue.

**Comment by SteVwonder** [comment]
I am also having issues with opening files via a symlink.  Any thoughts/ideas as to what is happening?  Running irony-server directly from the command line, it seems that it returns the same thing regardless of how the file is accessed (symlink or not).

**Comment by vasw** [comment]
If the compile_commands.json contains the target paths of the source
files and a source file is opened in Emacs using the symlink path,
Irony handle the symlink as a compilation flag.

I think that makes the clang parse to fail.

You can try to open the source file in emacs using the same path as
it is appears in the compilation database and see if it fails or not.
