### ISSUE TITLE
No completion on protected data members

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#310]
I am surprised I have never came across this issue yet:

**one.h:**
```
#ifndef _ONE_
#define _ONE_

class One
{
protected:
   int _one;
   int _two;
   void oneMethod();
};
#endif
```
**two.h**
```
#ifndef _TWO_
#define _TWO_
#include "one.h"

class Two : public One
{
protected:
   int someFunction();
};
#endif
```
**two.cpp**
```
#include "two.h"

int
Two::someFunction()
{
   // I should be able to see access to PROTECTED data here!
   return 1;
}
```
**main.cpp**
```
int main()
{
   Two two;
   return 0;
}
```

I believe this issue has been raised before, and I guess I have to believe that it has yet to be corrected...

Is this an issue you were aware of.

Thanks.

**Comment by Sarcasm** [comment]
Yeah, it's a know issue (recently noticed), cf: https://github.com/Sarcasm/company-irony/issues/22

**Comment by 3246251196** [comment]
I guess I could take a look at the clang source. I meant to.say that I belive this is an issue with clang..just surprised  no one has corrected it

**Comment by Sarcasm** [comment]
If you feel like it take a look at Clang, it's an interesting codebase and the community is welcoming.
I'm slightly too, to be honest, seeing the numbers of IDEs or such using libclang.
People don't necessarily participate upstream I think.
