### ISSUE TITLE
failed to build irony-server on windows

### ISSUE THREAD

**Issue by Ninlives** [Sarcasm/irony-mode#318]
OS: Windows 10
LLVM: 3.8.0
CMake: 3.6.0

The origin build command reported 53 errors. I tried to add 2 options so I ran 
`cmake -DLIBCLANG_LIBRARY="c:\\Program Files\\LLVM\\lib\\libclang.lib" -DLIBCLANG_INCLUDE_DIR="c:\\Program File\\LLVM\\include\\" -DCMAKE_INSTALL_PREFIX="c:\\Users\\Eleven\\.emacs.d\\irony" C:\Users\Eleven\.emacs.d\elpa\irony-20160628.1329\server && cmake --build . --use-stderr --config Release --target install`
now it report 3 errors, all about `can't open include file:“clang-c/Index.h”: No such file or directory`
Have any one met this?

**Comment by justinjk007** [comment]
Did you fix this error?
