### ISSUE TITLE
Config Irony-mode for OS X 10.11

### ISSUE THREAD

**Issue by rebocato** [Sarcasm/irony-mode#319]
Hi, recently i installed the irony tool for emacs 24.5 following the instructions the repository show, 
and really I follow the instructions like a recipe but i can't get it works, i tried many configurations, and i try installing old versions and uninstalled and coming back with the new version and i can't figure out what's wrong, this is my emacs config file:

=======================================================================
; ONE
; Start package.ex with Emacs.
(require 'package)
; Add MELPA to repository list
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
  ; Initialize package.el
(package-initialize)

; TWO
; Start auto-complete every time Emacs is Open
(require 'auto-complete)
; Do Default config for auto-complete
(require 'auto-complete-config)
(ac-config-default)

; THREE
; Start Yasnippet every time Emacs is Open
(require 'yasnippet)
(yas-global-mode 1)

; FOUR
; Define a function which initializes: "auto-complete-c-headers" and gets called for c/c++ hooks
(defun my:ac-c-header-init()
  (require 'auto-complete-c-headers)
  (add-to-list 'ac-sources 'ac-source-c-headers)
  (add-to-list 'achead:include-directories '"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include"))
; Now let's call this function from c/c++ hooks
(add-hook 'c++-mode-hook 'my:ac-c-header-init)
(add-hook 'c-mode-hook 'my:ac-c-header-init)

; FIVE
; TO ACTIVATE THIS OPTION USE "C-c ;" to DEACTIVATE PRESS AGAIN "C-c ;"
; Fix iedit bug in Mac
(define-key global-map (kbd "C-c ;") 'iedit-mode)

; SIX
; start flymake-google-cpplint-load
; let's define a function for flymake initialization
(defun my:flymake-google-init ()
  (require 'flymake-google-cpplint)
  (custom-set-variables
   '(flymake-google-cpplint-command "/Library/Python/2.7/site-packages/cpplint.py"))
  (flymake-google-cpplint-load)
)
(add-hook 'c-mode-hook 'my:flymake-google-init)
(add-hook 'c++-mode-hook 'my:flymake-google-init)

; SEVEN
; Start google-c-style with Emacs
(require 'google-c-style)
(add-hook 'c-mode-common-hook 'google-set-c-style)
(add-hook 'c++-mode-common-hook 'google-make-newline-indent)

; EIGHT
; Turn On Semantic
(semantic-mode 1)

; NINE
; Let's def9je a function which adds semantic as a suggestion backend to auto complete
; and hook this function to c-mode-common-hook
(defun my:add-semantic-to-autocomplete()
  (add-to-list 'ac-sources 'ac-source-semantic)
)
(add-hook 'c-mode-common-hook 'my:add-semantic-to-autocomplete)

; TEN
; Turn on ede mode
(global-ede-mode 1)

; TEN PARCIAL [change this for each project you'll manage in Emacs c/c++]
;Create a project
; You can use system-include-path for setting up the system header file locations.
(ede-cpp-root-project "my project" :file "/Users/luiseduardo/Downloads/Cpp-Demo-Project-For-Emacs-master/src/main.cpp"
		      :include-path '("/../my_inc"))

; ELEVEN
; Turn On Automatic Reparsing Of Open Buffers in Semantic
(global-semantic-idle-scheduler-mode 1)

; TWELVE
;; CONFIGURATIONS FOR IRONY

=======================================================================

----------------------------- CONFIGURATIONS FOR IRONY-MODE-------------------------------

--------------------------------------------------------------------------------------------------
I tried with many configurations the most recently with the first VERSION of irony-version is this:
--------------------------------------------------------------------------------------------------
; set LD_LIBRARY_PATH
(setenv "LD_LIBRARY_PATH" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/")
; load irony-mode
( add-to-list 'load-path (expand-file-name "~/.emacs.d/irony-mode/elisp/"))
(require 'irony)
; also enable ac plugin
(irony-enable 'ac)
; define a function to start irony mode for c/c++ modes
(defun my:irony-enable()
  (when (member major-mode irony-known-modes)
    (irony-mode 1)))
(add-hook 'c++-mode-hook 'my:irony-enable)
(add-hook 'c-mode-hook 'my:irony-enable)

--------------------------------------------------------------------------------------------------
And after that i made a lot a modifications to the emacs config file trying to adapt to the newer version without results.
And of course the official: 
--------------------------------------------------------------------------------------------------
add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

--------------------------------------------------------------------------------------------------

I have installed: clib, clang, llvm, and all the package irony-mode require, also i tried to install in a ubuntu 12.4.5 and nothing.

I hope somebody can help me what wrong or missing.

Thanks.

**Comment by Sarcasm** [comment]
I would recommend not to use auto-complete, and use company-mode instead. Does`M-x irony-completion-at-point-async` work?

If nothing works in emacs it may be better to try irony-server in the terminal first.
