### ISSUE TITLE
No completions for header files (Qt) showing up

### ISSUE THREAD

**Issue by sonictk** [Sarcasm/irony-mode#320]
Hi all:

I'm trying to setup company-irony and company-irony-c-headers to work on C++ in Emacs. Currently, I managed to get company-irony-c- headers working with my Qt header libraries using the following .clang_complete file:

```
-std=c++14
-Wall
-Wextra
-pthread
-Iinclude/**
-Ic:/Qt/4.8.5/include/**
```

However, when I try to get completions for any Qt related classes or objects, company-irony shows me only completions from standard libraries. It also will not let me navigate to the source header file (even though the completions come through from company-irony-c-headers fine).

When I check ``irony-cdb-menu``, the information there seems to be correct (working directory is my sources root, and the compile options have every option from my .clang_complete listed). What else am I missing here in order to get completions working for Qt libraries?

I would appreciate any advice anyone has to offer on this!

**Comment by Sarcasm** [comment]
> -Iinclude/**
> -Ic:/Qt/4.8.5/include/**

This does not look right.
There is no globbing going on in .clang_complete.

> It also will not let me navigate to the source header file (even though the completions come through from company-irony-c-headers fine).

IIUC, this is not a company-irony feature and I don't know about `company-irony-c-headers`.

**Comment by sonictk** [comment]
That was it exactly, thanks so much!
