### ISSUE TITLE
.clang_complete escaping

### ISSUE THREAD

**Issue by acowley** [Sarcasm/irony-mode#329]
Here is a `.clang_complete` file I am using,

```
-idirafter /nix/store/azk91xpsi6xiy5jv88k7jg05q73n1kvn-Libsystem-osx-10.9.5/include
-isystem /nix/store/phi4sdwx24pb371kwriyl8incbds9ifd-opencv-3.1.0/include
-F/nix/store/aq8s76v3lqf0sihprh77qlrq0n87lnzm-CF-osx-10.9.5/Library/Frameworks
-isystem /nix/store/sbqkkbwfwccqmxdrkv8crmxvlvmg7c4h-libc++-3.7.1/include
-isystem /nix/store/sbqkkbwfwccqmxdrkv8crmxvlvmg7c4h-libc++-3.7.1/include/c++/v1
-std=c++11
-arch x86_64
-mmacosx-version-min=10.7
```

If I turn that into a single line and enter it manually into an `irony-server -i` session after a `parse test.cpp` command, things work properly. However, `irony-mode` in emacs escapes things which causes trouble. Specifically, if I change the `irony--send-parse-request` function from,

``` lisp
(combine-and-quote-strings compile-options)
```

to

``` lisp
(mapconcat #'identity compile-options " ")
```

Then things work properly. For reference, the escaped `compile-options` include things like

```
"-isystem /nix/store/sbqkkbwfwccqmxdrkv8crmxvlvmg7c4h-libc++-3.7.1/include"
```

While the simply concatenated `compile-options` do not include the extra double quotes.

I can make a PR with this change, but I do not know if the shell escaping is critical in other scenarios.
## Secondary Question

In order to debug this, I added interactive `irony-parse` and `irony-diagnostics` functions that I found very helpful. Would you be open to a PR adding them?

**Comment by Sarcasm** [comment]
Why can't you put one command line argument per line? That's what irony-server expect, you just have to change this:

    -idirafter /nix/store/azk91xpsi6xiy5jv88k7jg05q73n1kvn-Libsystem-osx-10.9.5/include

to this:

    -idirafter
    /nix/store/azk91xpsi6xiy5jv88k7jg05q73n1kvn-Libsystem-osx-10.9.5/include

Regarding you second point, it could be interesting, you can submit a PR so that I understand better what it does exactly.

**Comment by acowley** [comment]
I can do that, yes, but it seems then that the [linked](https://github.com/Rip-Rip/clang_complete/blob/c8673142759b87316265eb0edd1f620196ec1fba/doc/clang_complete.txt#L55) example `.clang_complete` file wouldn't be handled correctly (the `-include ../config.h` line). This is why I opened an issue rather than a PR, as I'm not sure if the shell escaping is worth diverging from the ostensible format. If the shell escaping is necessary, perhaps the right fix is to amend the README to note this detail.

**Comment by Sarcasm** [comment]
Oh right, I thought the "specification" required one argument per line.
And actually it was the cause of a few issue in this bug tracker but I thought it was somewhat reasonable as it allow one to have compile options with spaces in it.

I think the fix should be in `irony-cdb-clang-complete--load-db`, when the file is read, not in `irony--send-parse-request`.
