### ISSUE TITLE
Irony-mode is not working 

### ISSUE THREAD

**Issue by fabriziojpiva** [Sarcasm/irony-mode#331]
Hi everyone, I would appreciate if you can help me with this. I'm on Debian Jessie 8.5, GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5). I have all the dependencies irony-mode requires, and I installed it by typing `M-x package-install RET irony RET`. After that, I configured my ~/.emacs file like this:

```
;; irony-mode
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
```
So, I downloaded this little c++ project: [cpp-demo-project](https://github.com/byuksel/Cpp-Demo-Project-For-Emacs), and I opened the main.cpp file. Now Irony-mode looked enabled for me, so I typed ` M-x irony-install-server RET `, and it compiled perfectly (here you have two screenshots which confirm this: [compilation1](https://k60.kn3.net/4F8B0A0BB.png) and [compilation2](https://k61.kn3.net/4144D4BC9.png)). So, the last thing I had to do was to type `M-x irony-cdb-autosetup-compile-options RET` but it didn't show anything to me. Furthermore, when I tried the command `M-x irony-cdb-menu RET` I got 

> "No compilation database in use"

 message coming from minibuffer. Of course, in the file main.cpp, when I tried to type `h. TAB` after the line Helper h; there is no autocompletion for me. 
So, I will be glad if you can help me with this, thanks to everyone!

**Comment by Sarcasm** [comment]
Looks like you don't have any compilation database, is that right? https://github.com/byuksel/Cpp-Demo-Project-For-Emacs does not have a `.clang_complete` and it's not a CMake project or anything like that.

What happens if you add a `.clang_complete` in the project's root:

```
cat <<EOF > .clang_complete
-Imy_inc
EOF
```

**Comment by fabriziojpiva** [comment]
Hi @Sarcasm , thanks for replying, I created that `.clang_complete` in the project's root, containing:
`-Imy_inc` or `-I./my_inc` but it still not working. Now, when I type `M-x irony-cdb-menu RET` I get the following: [screenshot](https://k60.kn3.net/B8EB68125.png). Anyway, when I write `h. TAB` or `add_obj. TAB` nothing appears. In addition, according to the final part of this video [irony-mode tutorial](https://www.youtube.com/watch?v=NjTCjqSZOAU), he didn't need that `.clang_complete` file to autocomplete the "Helper" example object. He needed it when tried to autocomplete the "MyAdd" object.

**Comment by Sarcasm** [comment]
Do you use `company-irony`? https://github.com/Sarcasm/company-irony
If not, you should. The `ac` backend is not really maintained, I only use company-mode.

Also, theorically you can use `M-x irony-completion-at-point RET` to see if that works.

It's possible that irony-server does not launch properly, for example if it cannot find libclang.so at runtime.

Can you try to type this:

```
~/.emacs.d/irony/bin/irony-server --version
```

**Comment by fabriziojpiva** [comment]
I have `company-irony` installed and this is my `~/.emacs` for both:

`;; irony-mode

    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'objc-mode-hook 'irony-mode)

    ;; replace the `completion-at-point' and `complete-symbol' bindings in
    ;; irony-mode's buffers by irony-mode's asynchronous function
    (defun my-irony-mode-hook ()
      (define-key irony-mode-map [remap completion-at-point]
        'irony-completion-at-point-async)
      (define-key irony-mode-map [remap complete-symbol]
        'irony-completion-at-point-async))
    (add-hook 'irony-mode-hook 'my-irony-mode-hook)

;; company-irony

(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))
`
When I type `M-x irony-completion-at-point RET` it shows this buffer: [screenshot](https://k60.kn3.net/8/F/F/C/E/3/9A5.png). But nothing happens when I press TAB trying to call a function of that "h" Helper object (according with my screenshot).
This is the output of `~/.emacs.d/irony/bin/irony-server --version`:

`irony-server version 0.2.0
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)`

Thanks for replying.

**Comment by Sarcasm** [comment]
Is company-irony bound to `TAB`?

Invoking `M-x company-irony RET` explicitly does not work either?

**Comment by fabriziojpiva** [comment]
I invoked `M-x company-irony RET` when typing `h.` and it worked! Look at this: [screenshot](https://k60.kn3.net/2/A/4/7/B/6/B83.png) But it does not work with TAB key. How do I configure `company-irony` to work with TAB key?

**Comment by Sarcasm** [comment]
Personally I have company bound to `M-RET`:

```el
(global-set-key (kbd "M-RET") 'company-complete)
```

You can take a look here for `TAB` which I think require more work as it is usually bound to something like indent, or people have more specific expectations about the completion behavior, a non-exhaustive list of links regarding this subject:

* https://www.emacswiki.org/emacs/CompanyMode#toc10
* https://github.com/company-mode/company-mode/issues/94#issuecomment-40884387
* https://github.com/company-mode/company-mode/wiki/Switching-from-AC
* https://github.com/company-mode/company-mode/issues/526

**Comment by fabriziojpiva** [comment]
I added that line to my `~/.emacs` file, but it does not work. This is almost my entire `~/.emacs` file:


```
(package-initialize)
;; Activa auto-complete con el inicio de Emacs
(require 'auto-complete)
(require 'auto-complete-config)
(ac-config-default)
;; Activa yasnippet con el inicio de Emacs
(require 'yasnippet)
(yas-global-mode 1)

(defun my:ac-c-header-init()
  (require 'auto-complete-c-headers)
  (add-to-list 'ac-sources 'ac-source-c-headers)
  (add-to-list 'achead:include-directories '"/usr/lib/gcc/x86_64-linux-gnu/4.9/include"))
					;now let's call this function from c/c++ hooks
(add-hook 'c++-mode-hook 'my:ac-c-header-init)
(add-hook 'c-mode-hook 'my:ac-c-header-init)

;; irony-mode

    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'objc-mode-hook 'irony-mode)

    ;; replace the `completion-at-point' and `complete-symbol' bindings in
    ;; irony-mode's buffers by irony-mode's asynchronous function
    (defun my-irony-mode-hook ()
      (define-key irony-mode-map [remap completion-at-point]
        'irony-completion-at-point-async)
      (define-key irony-mode-map [remap complete-symbol]
        'irony-completion-at-point-async))
    (add-hook 'irony-mode-hook 'my-irony-mode-hook)

;; company-irony

(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))
(global-set-key (kbd "M-RET") 'company-complete)
```
When I start emacs, and I type `M-x company-irony RET` the buffer says:

>  "Company not enabled"

**Comment by Sarcasm** [comment]
You need to install and configure company-mode:

* http://company-mode.github.io/

  Looks like you only need:

      (add-hook 'after-init-hook 'global-company-mode)


If you don't use ac/auto-complete, I would suggest you remove it as it may want to control your tab key, and usually you want either company or auto-complete but not both.

**Comment by fabriziojpiva** [comment]
Now it's working :D . I'm so glad for your help. You have a really good support by the way.

**Comment by Sarcasm** [comment]
Great, I'm closing then.

And thank you for the kind comment.
