### ISSUE TITLE
std::shared_ptr doesn't auto-pop-up

### ISSUE THREAD

**Issue by zhihuiFan** [Sarcasm/irony-mode#337]
I'm working on ubuntu 14 and my gcc version is 4.8.4 and clang version is 3.8,

after I included \<memory\> file,  I can get the std::auto_ptr auto-pop-up,  but I can't get std::shared_ptr pop-up. 

is there anything I can do for this? 

Thanks

**Comment by Sarcasm** [comment]
maybe you need to add `-std=c++11` compile options?

**Comment by zhihuiFan** [comment]
thanks @Sarcasm  for your reply.  I have added -std=c++11 option, but still no lucky.  you can see the photo for details. 

<img width="567" alt="screen shot 2016-10-03 at 10 12 19 pm" src="https://cloud.githubusercontent.com/assets/3489747/19040432/9e8493b2-89b6-11e6-96be-01799d390141.png">

**Comment by zhihuiFan** [comment]
added (setq irony-additional-clang-options '("-std=c++11"))  works.
