### ISSUE TITLE
irony-mode in chroot environment

### ISSUE THREAD

**Issue by ANDRON94** [Sarcasm/irony-mode#342]
Hi, my project is located in chroot environment and when I generate 'compile_commands.json' and work **outside chroot** - Irony, irony-company and irony-flycheck is not properly working. I try to replace '/usr/include/' with '/<CHROOT_PATH>/usr/include' but it doesn't help.
So how to work with chroot projects outside from environment?

**Comment by Sarcasm** [comment]
Would you have some sample `compile_commands.json` bits? With sensitive information removed if any.

I guess the absolute paths in the database have to be rewritten so that they are re-rooted to the chroot root?

**Comment by ANDRON94** [comment]
Sorry, markdown "eat" my description of solution:
I try to replace "/usr/include/" with "/CHROOT_PATH/usr/include" but it doesn't help.
Ok, I edit and send example of my *compile_commands.json*

**Comment by ANDRON94** [comment]
Hi, I found and changed all absolute paths(files, libraries, etc.) and then Irony started to work properly.
Thanks for a such great plugin!
