### ISSUE TITLE
clang autocomplete issue

### ISSUE THREAD

**Issue by rcastill** [Sarcasm/irony-mode#347]
Hi,
First, let me thank you for this amazing tool.

Now the problem:
I have a project that uses cmake which lets me generate  `compile_commands.json`. I can check emacs loads it correctly by running `irony-cdb-menu`, which shows the expected include paths and flags. Thing is, when I try to use completion function (for example by typing . or -> using company) it only works with definitions in system include directories, or exact paths given with ""; e.g.: `#include "../include/SomeClass.h"`, but when using include statements, for headers not in same location as .cpp/.c counterpart; e.g. `#include <SomeClass.h>` it does not work, nevertheless `-Ipath/to/include/SomeClass.h` is correctly defined in `compile_commands.json`.

It actually fails with this error:
```
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:36:10 -
```
with `:36:10` being the `line:column` in the file where it tried to complete code.

After some tests I realized that error was also triggered when symbols or its headers did actually not exist.

I do not know if I'm doing something wrong, or there is a bug.

Thanks in advance,
Regards!

**Comment by Sarcasm** [comment]
Hello,

You are not using [company-irony[(https://github.com/Sarcasm/company-irony) but `company-clang` it seems.

Make sure you have company-irony installed and configured.

**Comment by rcastill** [comment]
I do not have any `company-clang` installed, but actually neither I had `company-irony`. I installed it and configured it by adding it to company's backends.

This time I do not get any error and it does no longer complete even with definitions in same file.

`M-x company-irony RET` yields "Cannot complete at point"

Regards!

**Comment by rcastill** [comment]
I discovered I actually have installed `company-clang` as it comes bundled with `company`. I tried deleting it from backends and now, normal completions work again, but I'm still lacking of auto-completion on external sources; in fact, normal completion is slower, I presume it is indexing (a progress log would be nice). I'll keep trying, and update on news!

Here is the modification I issued to my `.emacs` file:

```
; Load company backends
(eval-after-load "company"
  (when (boundp 'company-backends)
    (make-local-variable 'company-backends)
    (setq company-backends (delete 'company-clang company-backends))
    '(add-to-list 'company-backends 'company-anaconda)
    '(add-to-list 'company-backends 'company-irony)))
```

**Comment by Sarcasm** [comment]
I don't see what's wrong in your configuration but mine is not that complicated.

```el
(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))
```

company-irony will do nothing if irony-mode is not enabled, so you don't need to make company-backends a local variable.
The add to list call should put company-irony before company-clang, I don't know why it does not for you.

You should not have to check "bound".

However, I now see something weird, your eval-after-load uses a string and not a quoted symbol.

**Comment by rcastill** [comment]
Respecting to the complicated configuration, I realized it does not make sense making it local, I now tried the approach of defining `(set (make-local-variable 'company-backends) '(company-irony))` in `c++-mode-hook` in order to make sure is the only backend in that mode. No luck again.

I also realized about the string; I changed it to quoted symbol and nothing changes, they are equivalent when it comes to strings.

Keep trying...

**Comment by rcastill** [comment]
IT WORKS.. And it is so beautiful c':

I made so much attempts that it seems I forgot to re-generate `compile_commands.json`; I realized, some of its content was strange, comparing it with a barebone project that I created to traceback this issue.

Anyways, my config is as recommended and it works flawlessly.

Thanks for helping me,
Keep on!

**Comment by Sarcasm** [comment]
Great!
