### ISSUE TITLE
Irony emits incorrect completions

### ISSUE THREAD

**Issue by stephenry** [Sarcasm/irony-mode#348]
I've been attempting to get irony-mode to work on the LLVM codebase for the last couple of hours but without success. Completion takes place, but regardless of the point on which I invoke the completion, I receive the same completion list:

ARG_MAX
ATOMIC_BOOK_LOCK_FREE
ATOMIC_CHAR16_T_LOCK_FREE
ATOMIC_CHAR32_T_LOCK_FREE
....

In each case, the completion list derived is completely wrong and contains no correct completions.

I encountered some issues enabling irony to see my compile_commands.json file and I was eventually able to get *something* working on the CDB menu command, but this states:

"Complation Database: irony-cdb-libclang"

Which suggests to me that it is looking at another database somewhere. Even so, I cannot explain the incorrect completions.

The tool looks like a great effort so I'm investing quite a lot of time trying to figure out how to get it to work but without success. So, I'm reaching out.

**Comment by Sarcasm** [comment]
Can you show more details about the `irony-cdb-menu`?
Is there any compile options in it?

`irony-cdb-libclang` means the compilation database was found and parsed with libclang's compilation database facility (this is the fastest method for big databases).

**Comment by stephenry** [comment]
Yes, there appear to be valid compile options:

<img width="1365" alt="screen shot 2016-12-02 at 8 04 32 pm" src="https://cloud.githubusercontent.com/assets/691529/20848590/9dd08b0e-b8ca-11e6-8c1c-3223e5809176.png">

**Comment by Sarcasm** [comment]
I tried to compile the same point as you and it worked (just making sure).

How does it work on a minimal example with no system headers?
How does it work with a minimal example with a system header?

It's possible that the builtin C headers such as stddef.h are not found.

**Comment by Sarcasm** [comment]
My result:

![image](https://cloud.githubusercontent.com/assets/424046/20849040/23f033c4-b8d5-11e6-8050-4879017062b8.png)

**Comment by stephenry** [comment]
I added the line and it works!!!!

(eval-after-load 'company
'(add-to-list 'company-backends 'company-irony))

Previously I had encountered the "clang error 1" failure. I can only surmise that the completion was being carried out by company-clang and silently failing. 

Very impressive work, and thanks for your help.

**Comment by Sarcasm** [comment]
Interesting, very few people encountered this error for years and today 2 people have the same error.

- https://github.com/Sarcasm/irony-mode/issues/347

Anyway, great to hear.

**Comment by astoeckley** [comment]
I've looked at this ticket and #347 and am getting similar problems with gibberish in the completion menu. Mine looks like this:

<img width="396" alt="screen shot 2017-03-26 at 18 43 59" src="https://cloud.githubusercontent.com/assets/4611759/24333247/d96c41d8-1254-11e7-86c1-e7b34d4e70ed.png">

My config looks like this:

```
(load "/usr/local/opt/llvm/share/clang/clang-format.el")
(require 'clang-format)

(add-hook 'c++-mode-hook 'electric-pair-mode)

;; irony autocompletion
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c++-mode-hook 'company-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)
;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))

(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
```

other tidbits:

> ~/.emacs.d/irony/bin ./irony-server --version
> irony-server version 0.2.1
> clang version 4.0.0 (tags/RELEASE_400/final)

irony-cdb-menu finds stuff ok, i think:

<img width="957" alt="screen shot 2017-03-26 at 18 50 45" src="https://cloud.githubusercontent.com/assets/4611759/24333265/30d9ad2a-1255-11e7-84c2-d4f84d652f7b.png">

Whether I try to get completion on the STL, like std::vector, or a simple struct of my own, I just get the same nonsense in the popup, without any legit items.

**Comment by astoeckley** [comment]
As I am on OSX I also attempted to follow these instructions, which installed fine but made no difference:

https://gist.github.com/soonhokong/7c2bf6e8b72dbc71c93b#gistcomment-1414945

**Comment by astoeckley** [comment]
Well, very strangely, some projects it is working fine and others not, despite that these are personal projects with identical cmake, build and emacs settings. Even within the same projects, I will sometimes get proper autocompletion and then opening the same project later, I will get the flood of nonsense completions in my above screenshot. Weird. I guess I will live without autocompletion for now.
