### ISSUE TITLE
Current directory isn't included in header search directory.

### ISSUE THREAD

**Issue by kangjianbin** [Sarcasm/irony-mode#350]
Hi All,

My enironment is msys2 (clang was installed in msys2, and irony-server was built with mingw).
I find that current directory isn't included in complete. For example:
~/tmp/test/def.h
```c
#ifndef __MY_DEF_H
#define __MY_DEF_H
struct S1 {
	int	s1_a;
	int	s1_b;
	int	s1_c;
};
#endif
```
```c
#include "def.h"
int main(int argc, char *argv[])
{
	struct S1 s;
	s.s1_a = 0;
	return 0;
}
```

When editing `a.c`, `flycheck-irony` reports `'def.h' file not found` and `company` failed to complete when typeing `s.`.
However, if I add `-I.` in .clang_complete, both `flycheck` and `company` work well.
I only observed this issue on windows with msys2. No problem on linux.

**Comment by Sarcasm** [comment]
What's in your .clang_complete? Was it empty before you added the `-I.`?

I'm not sure `-working-directory` is working as I would like to on Windows, if it does not work, irony can have some issues.

**Comment by kangjianbin** [comment]
I didn't create a `.clang_complete` until the error was reported.

**Comment by kangjianbin** [comment]
Switch to 'tdm-gcc', it worked. Thanks!
