### ISSUE TITLE
Can company-irony cache its completion results?

### ISSUE THREAD

**Issue by dmalyuta** [Sarcasm/irony-mode#358]
In my current project (which is not big at all, only about 800 lines but includes heavy headers from Boost and PCL as well as some ROS headers) completion at point with company-irony can take up to 10 seconds. I'm fine if this happens the first time that I invoke a new completion, but the problem is that I may attempt to do a completion at one point and even just 5 seconds later, doing the exact same completion takes again up to 10 seconds! I would have thought that there is some sort of caching - i.e. if I completed a symbol once, it is kept in memory for some time so that similar completions can happen quickly. Is there any option for this?

I am using Emacs 25.1 on Ubuntu 14.04. Here is the part of my `init.el` relevant to completion:

```
(use-package company
    ;; complete anything
    :ensure t
    :bind
    (("<S-SPC>" . company-complete)
     ("C-x C-n" . company-select-next)
     ("C-x C-p" . company-select-previous))
    :init
    ;;(add-hook 'after-init-hook 'global-company-mode)
    (add-hook 'c-mode-common-hook 'company-mode)
    (add-hook 'emacs-lisp-mode-hook 'company-mode)
    :config
    (setq company-backends (delete 'company-semantic company-backends))
    ;; use C++11 by default
    (require 'cc-mode)
    (set 'company-clang-arguments (list "-std=c++11")))

  (use-package irony
    ;; asynchronous capabilities (improces C/C++ editing experience)
    ;; Linux Mint:
    ;;  sudo apt-get install g++ clang libclang-dev
    ;;  M-x irony-install-server # when in c-mode or c++-mode
    :ensure t
    :defer t
    :init
    (add-hook 'c-mode-common-hook 'irony-mode)
    :config
    ;; replace completion-at-point and complete-symbol by irony-mode's asynchronous functions
    (defun my-irony-mode-hook ()
      (define-key irony-mode-map [remap completion-at-point]
	'irony-completion-at-point-async)
      (define-key irony-mode-map [remap complete-symbol]
	'irony-completion-at-point-async))
    (add-hook 'irony-mode-hook 'my-irony-mode-hook)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
    (setq irony-additional-clang-options '(;; use C++11
					   "-std=c++11"))
    ;; additional include paths
    ;;					 "-I/home/danylo/catkin_ws/devel/include/"
    ;;					 "-I/opt/ros/kinetic/include/"))
    ;; asynchronous code linting
    (use-package flycheck-irony
      :ensure t
      :config
      ;; Enable Irony for Flycheck
      (eval-after-load 'flycheck '(add-hook 'flycheck-mode-hook #'flycheck-irony-setup)))
    ;; asynchronous completion
    (use-package company-irony
      :ensure t
      :init
      (add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)
      (eval-after-load 'company '(add-to-list 'company-backends 'company-irony))
      :config
      (setq company-idle-delay 0.05)
      (setq company-async-timeout 10) ;; set timeout to 10 seconds
      )
    ;; enable C/C++ header completion
    (use-package company-irony-c-headers
      :ensure t
      :config
      (eval-after-load 'company '(add-to-list 'company-backends '(company-irony-c-headers company-irony)))))
```

**Comment by Sarcasm** [comment]
Could you test this example and tell if you have abnormal times?

- https://github.com/Sarcasm/irony-mode/issues/131#issuecomment-60008803

**Comment by dmalyuta** [comment]
Should I set `process-adaptive-read-buffering` to `nil`?

**Comment by Sarcasm** [comment]
Sorry, no the only thing that matter is the sample code.

**Comment by dmalyuta** [comment]
I just tested it. Completion is very fast - I would say <0.1 seconds (the completions show up pretty much instantaneously when typing `boost::`). Note that since my original post, I've commented out `(setq company-backends (delete 'company-semantic company-backends))` in my `init.el` which seems to improve things (the completion with PCL and ROS headers included is still much slower than on your test code, but once one completion is done after >5 seconds waiting, similar completions take less time).

**Comment by Sarcasm** [comment]
Regarding your config:

If you just use irony-mode for C++, you don need the `:config` section of company:

```el
    :config
    (setq company-backends (delete 'company-semantic company-backends))
    ;; use C++11 by default
    (require 'cc-mode)
    (set 'company-clang-arguments (list "-std=c++11")))
```

However these values should not hurt.

In company-irony configuration, the following variables are probably better set in company configuration, or made local in irony-mode buffers.
`company-idle-delay` is quite low but it should not be an issue.
Did you try commenting it just in case?

```el
      (setq company-idle-delay 0.05)
      (setq company-async-timeout 10) ;; set timeout to 10 seconds
```


The config looks ok to me.

When you are using PCL and ROS, do you know if you have any compilation warnings?
If Clang is unable to find some headers for example, the completion will be dodgy.

**Comment by dmalyuta** [comment]
Do I understand correctly that your suggestions are for the `company` config to be like this:

```
  (use-package company
    ;; complete anything
    :ensure t
    :bind
    (("<S-SPC>" . company-complete)
     ("C-x C-n" . company-select-next)
     ("C-x C-p" . company-select-previous))
    :init
    ;;(add-hook 'after-init-hook 'global-company-mode)
    (add-hook 'c-mode-common-hook 'company-mode)
    (add-hook 'emacs-lisp-mode-hook 'company-mode)
    :config
    (setq company-async-timeout 10) ;; set timeout to 10 seconds
    ;;(setq company-backends (delete 'company-semantic company-backends))
    ;; use C++11 by default
    ;; (require 'cc-mode)
    ;; (set 'company-clang-arguments (list "-std=c++11"))
    )
```

and to comment out `(setq company-idle-delay 0.05)`?

I've compiled the ROS package successfully with Cmake (the package includes the PCL header `#include <pcl_ros/point_cloud.h>`) without any warnings during compilation (I use `catkin tools` with the settings that we dicussed before on [Emacs stackexchange](http://emacs.stackexchange.com/questions/28026/add-include-paths-to-flycheck-and-to-company-irony/28507)).

Is there any more advice you can give? Would you recommend that I set `process-adaptive-read-buffering` to `nil` (and if so, in which config?)?

**Comment by Sarcasm** [comment]
I meant `company-idle-delay` and `company-async-timeout` are company settings, and should probably belong in the company section. I don't know use package but it looks ok to me that way.

CMake can be capable of building your project but irony is slightly different.
Notably, it uses some built-in header search directories, which may not be found when Clang is updated for example, in the case Clang will try to provide completion as much as possible but since it is unable to find some built-in headers he does not produce a successful cache.

If you want to know if you have compilation errors you may need to add the "-d" flags to irony-server, see procedure here:

- https://github.com/Sarcasm/irony-mode/issues/218#issuecomment-175875093


> Would you recommend that I set process-adaptive-read-buffering to nil (and if so, in which config?)?

Please forget about process-adaptive-read-buffering, it should not be related to your issue.

**Comment by dmalyuta** [comment]
I added the `-d` flag to `irony.el` so that it looks like this now:
```
(setq process
            (start-process-shell-command
             "Irony"                    ;process name
             irony--server-buffer       ;buffer
             (format "%s -d -i 2> %s"      ;command
                     (shell-quote-argument irony--server-executable)
                     (expand-file-name
                      (format-time-string "irony.%Y-%m-%d_%Hh-%Mm-%Ss.log")
                      temporary-file-directory))))
```
Where should I be seeing these compilation errors, if any exist? Do I need to restart the server? It would be great if you could tell me the exact set of commands. I really appreciate your help, thank you!

**Comment by Sarcasm** [comment]
haha, sorry I'm forgot a few things...

You should be able to see the compilation errors in a log file in /tmp/

For example on my computer (Linux distribution), the file is: /tmp/irony.2017-02-06_20h-02m-40s.log
You need to restart irony-server, `irony-server-kill`. Also, make sure you evaluated the definition of the function.

**Comment by dmalyuta** [comment]
I can see the logs, what its showing is the copy of the file in which I attempted autocompletion on a symbol and below:

```
----
debug: complete: 1 diagnostic(s)
<DIRECTORY>.h:4:10: fatal error: 'sstream' file not found
```

**Comment by dmalyuta** [comment]
I think I figured out why this error is being thrown though: it seems irony is treating the `.h` header as a C header. But in fact, it is a C++ header. How would I remedy this? Do I need to name C++ headers explicitly with `.hpp` extensions?

**Comment by Sarcasm** [comment]
You need to have c++-mode enabled in your buffer.
For example, you can do:

```el
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
```

**Comment by dmalyuta** [comment]
Thanks. It seems to be working better now, but I'm not sure if the speed increase I'm seeing (especially caching) is permanent and not by luck. Perhaps we keep the issue open for a few days and I close it once it seems like everything still works well?

For reference, here is the `company`-related config in my init.el now:

```
  (use-package company
    ;; complete anything
    :ensure t
    :bind
    (("<S-SPC>" . company-complete)
     ("C-x C-n" . company-select-next)
     ("C-x C-p" . company-select-previous))
    :init
    ;;(add-hook 'after-init-hook 'global-company-mode)
    (add-hook 'c-mode-common-hook 'company-mode)
    (add-hook 'emacs-lisp-mode-hook 'company-mode)
    :config
    (setq company-async-timeout 10) ;; set timeout to 10 seconds
    ;;(setq company-backends (delete 'company-semantic company-backends))
    ;; use C++11 by default
    ;; (require 'cc-mode)
    ;; (set 'company-clang-arguments (list "-std=c++11"))
    )

  (use-package irony
    ;; asynchronous capabilities (improces C/C++ editing experience)
    ;; Linux Mint:
    ;;  sudo apt-get install g++ clang libclang-dev
    ;;  M-x irony-install-server # when in c-mode or c++-mode
    :ensure t
    :defer t
    :init
    (add-hook 'c-mode-common-hook 'irony-mode)
    :config
    ;; replace completion-at-point and complete-symbol by irony-mode's asynchronous functions
    (defun my-irony-mode-hook ()
      (define-key irony-mode-map [remap completion-at-point]
	'irony-completion-at-point-async)
      (define-key irony-mode-map [remap complete-symbol]
	'irony-completion-at-point-async))
    (add-hook 'irony-mode-hook 'my-irony-mode-hook)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
    (setq irony-additional-clang-options '(;; use C++11
					   "-std=c++11"))
    ;; additional include paths
    ;;					 "-I/home/danylo/catkin_ws/devel/include/"
    ;;					 "-I/opt/ros/kinetic/include/"))
    ;; asynchronous code linting
    (use-package flycheck-irony
      :ensure t
      :config
      ;; Enable Irony for Flycheck
      (eval-after-load 'flycheck '(add-hook 'flycheck-mode-hook #'flycheck-irony-setup)))
    ;; asynchronous completion
    (use-package company-irony
      :ensure t
      :init
      (add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)
      (eval-after-load 'company '(add-to-list 'company-backends 'company-irony))
      ;; :config
      ;; (setq company-idle-delay 0.05)
      )
    ;; enable C/C++ header completion
    (use-package company-irony-c-headers
      :ensure t
      :config
      (eval-after-load 'company '(add-to-list 'company-backends '(company-irony-c-headers company-irony)))))
```

**Comment by Sarcasm** [comment]
Ok, great, let me know.

I suppose you also have the `auto-mode-alist` somewhere?

**Comment by dmalyuta** [comment]
Yes, I forgot to include that one (I put it down at the bottom of my `init.el`)

**Comment by dmalyuta** [comment]
As an update, I've switched to using [CLion](https://www.jetbrains.com/clion/) where I find the auto-completion to be faster. Thanks for your efforts, though - Irony is a great package.
