### ISSUE TITLE
not found on melpa

### ISSUE THREAD

**Issue by mehdipourfar** [Sarcasm/irony-mode#360]
I cannot get irony mode from melpa.
I enter the command _M-x package-install RET irony RET_ and get this error:
https://melpa.org/packages/irony-20161106.830.tar: Not found

**Comment by Sarcasm** [comment]
Use `M-x package-list-packages RET` or `M-x packages-refresh-contents RET` to refresh the list, then install.

**Comment by mehdipourfar** [comment]
thanks a lot.

**Comment by Sarcasm** [comment]
No problem!
