### ISSUE TITLE
Error from syntax checker irony: parsing failed 

### ISSUE THREAD

**Issue by Dickby** [Sarcasm/irony-mode#361]
I started a new C-Project.
The mentioned error message appears if i open some files, for others irony is working.
If i now create any new ".c" file in the project directory, i get that error.
Is there any way to check where the parsing fails?
irony version: 0.2.2-cvs
GNU Emacs 25.0.50.4

**Comment by Sarcasm** [comment]
Parsing failed is a generic clang error, when clang crashes I think.
I don't know how to check where the parsing fails except from reducing the file as much as possible to identify the issue.

**Comment by Dickby** [comment]
It was a problem in the Makefile.
Thanks.
