### ISSUE TITLE
Type and global function completion - What is the expected behavior?

### ISSUE THREAD

**Issue by nicolasmiller** [Sarcasm/irony-mode#362]
I'm using a standard company-irony setup as given in the documentation. I'm going to use the following example to pose a couple of questions about expected behavior:
```c++
#include <iostream>
#include <cstdint>

typedef struct {
    double x;
    double y;
} Point;

float foo() {
    return 42.0f;
}

int main() {
    std::cout << "foo" << std::endl;
    Point x;
    uint8_t x; 
}
```
Typing `uint8_t` in this example does not produce any suggestions even though `cstdint` is included. Names under `std` will as well as the fields on `Point` complete as expected. Is this correct? 

Also, the function `foo` will complete but not immediately after it has been defined. It seems to be available only on a subsequent Irony session. If some definition somewhere is changed, when is Irony supposed to become aware of it? Is there a way to force Irony to examine a particular file again to find the latest definitions? This example is just a single file; I'm not using a compilation database.

It would be useful if the README explained in simple terms what the possible completions are and what the basic expected behavior is. As it stands, it's difficult to figure out if a particular installation is functioning correctly.

**Comment by Sarcasm** [comment]
> Typing uint8_t in this example does not produce any suggestions even though cstdint is included. Names under std will as well as the fields on Point complete as expected. Is this correct?

This is correct if you haven't set your compile options.
`cstdint` is a C++11 feature, if you try to compile with clang without specifying the standard, you get this:

```
$ clang++ test.cpp 
In file included from test.cpp:2:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/cstdint:35:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../include/c++/6.3.1/bits/c++0x_warning.h:32:2: error: This
      file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the
      -std=c++11 or -std=gnu++11 compiler options.
#error This file requires compiler and library support \
 ^
test.cpp:16:5: error: unknown type name 'uint8_t'
    uint8_t x;
    ^
2 errors generated.
```

If you compile with `-std=c++11`, you get this:

```
$ clang++ -std=c++11 test.cpp
test.cpp:16:13: error: redefinition of 'x' with a different type: 'uint8_t' (aka 'unsigned char') vs 'Point'
    uint8_t x;
            ^
test.cpp:15:11: note: previous definition is here
    Point x;
          ^
```


> Also, the function foo will complete but not immediately after it has been defined. It seems to be available only on a subsequent Irony session.

I cannot reproduce this.

> If some definition somewhere is changed, when is Irony supposed to become aware of it? Is there a way to force Irony to examine a particular file again to find the latest definitions?

Irony should picked up modifications when the file is saved.
For example if you have a header that you modify to add a function, and a source file that depend on it, the source file should notice the change when the buffer is saved (you may have to edit the source file to retrigger a check).

> This example is just a single file; I'm not using a compilation database.

You need one (at least a `.clang_complete`), with the `-std=c++11` flag.

> It would be useful if the README explained in simple terms what the possible completions are and what the basic expected behavior is. As it stands, it's difficult to figure out if a particular installation is functioning correctly.

I should probably emphasis on the importance of the compile options, and offer a way to diagnose issues other than with flycheck-irony (which does not show some categories of issues).

**Comment by nicolasmiller** [comment]
Thanks for the detailed explanation! Sorry about the typo with the redefinition of x; that wasn't meant to be significant in the example.
