### ISSUE TITLE
Not sure if libclang is correctly working

### ISSUE THREAD

**Issue by Red-Portal** [Sarcasm/irony-mode#365]
Hi,
I'm currently having a problem with completion

![image](https://cloud.githubusercontent.com/assets/18320033/23498800/9519d2de-ff6c-11e6-9db9-55d29eaa1ca9.png)

Using company-irony outputs these messages

![image](https://cloud.githubusercontent.com/assets/18320033/23498817/abd723a0-ff6c-11e6-8319-df4f054f7b4b.png)

This is the irony-server commands.
Is it natural for the diagnostics command to output nothing?

![image](https://cloud.githubusercontent.com/assets/18320033/23498825/b99ebf3e-ff6c-11e6-9e69-dc1491910ace.png)

This is the file I'm testing everything.
Flycheck works like a charm but company doesn't work.

Is it just a problem of speed?

**Comment by Sarcasm** [comment]
For completion, the errors you have are from `company-clang`, not `company-irony`.
What happens if you invoke `M-x company-irony RET` directly?

**Comment by Red-Portal** [comment]
Oh that was the problem. Works like a charm now
Thanks!
