### ISSUE TITLE
Protected Members

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#367]
[allVisible.txt](https://github.com/Sarcasm/irony-mode/files/851187/allVisible.txt)

References: https://github.com/Sarcasm/company-irony/issues/22
References: https://github.com/Sarcasm/irony-mode/pull/369
References (clang): https://bugs.llvm.org//show_bug.cgi?id=24329

@Sarcasm 

I think it is more important that candidates are shown that will cause compilation errors than leaving candidates out. I think that even private members should be shown: let the compiler complain if the user is accessing a private/protected member when she should not be.

I have applied a patch that I personally use. It may go against coding guidelines etc.. and the fact that the message is put out into the "brief" section is not ideal. But it is something I use.

Also, I have checked out clang and built it. I am debugging why this happens in the clang libs.

Cheers.

**Comment by 3246251196** [comment]
@Sarcasm 

The good news is that I have found the bug in Clang which causes the issue. I will submit a patch and it means there is no need for any hacks to allow InAccessibles through. I will update this thread when the patch is applied: IF it is applied.

**Comment by Sarcasm** [comment]
Ok, great, can you link to the patch in question for my curiosity?
I'm wondering if I should apply your initial patch and make a version check for when you upstream patch is integrated. People on older version will have access to too many members, people with more recent version will have only what is accessible.

**Comment by 3246251196** [comment]
@Sarcasm 
I was a little gun-ho. My fix did not consider the access privileges of inheritance.

For example,

`struct A { protected: void myProt() { return; }; };`
`struct B : private A { };`
`struct C : public B { void someMethod() { this->myProt(); }; };`


The fix allows you to do this. Since B has private inheritance to A - C should not know anything about A.

I think the best thing to do, and what I will do, is to modify Irony.cpp to simply allow Inaccessibles and put up a warning in my minibuffer via the brief string.

In the mean time I can work on coming up with a solution or, at least, a partial solution that is better than previous versions of clang.

The guys over there are understandable being defensive: i.e. it is better to NOT allow access at all than allow access when it may not be allowed!

For your information, the location of the "bug" was:

_SemaAccess.cpp:826_
`switch (IsDerivedFromInclusive(InstanceContext, ECRecord)) {`

The arguments to the method, in my opinion, were the wrong way around. When they are switched you now ask: so long as the execution context's class (_struct C_) is a derivative of the target's (_struct A_ - since the target is the _myProt()_ method when Irony is requesting completions) then the completion is allowed. However, there is no consideration of inheritance access.

Cheers.

**Comment by Sarcasm** [comment]
Yes please submit a PR.
Regarding the different style for inaccessible candidates, I feel like this could be a good idea. It would be necessary to return the information to elisp instead of process it in irony-server.

Whatever you decide is fine by me, your current patch is fine by me as it doesn't prevent to improve later.

**Comment by 3246251196** [comment]
A work around for this is now in irony-mode master.
https://github.com/Sarcasm/irony-mode/pull/369
