### ISSUE TITLE
Globals and macros

### ISSUE THREAD

**Issue by Hjorthen** [Sarcasm/irony-mode#372]
Hi! 
I have a project which includes OpenCV and therefor also boost. Unfortunately, those frameworks adds a lot of C++ macro definitions, which clutters up the auto-completion list making it impossible to locate the member functions that should belongs to the object. Is there a way to disable macro indexing or another fix for this?

I've added an image of the issue:
![image](https://cloud.githubusercontent.com/assets/11670799/24587797/40c7526a-17bd-11e7-966c-718a76c182d1.png)

EDIT: It seems like it is only globals that are showing up..

**Comment by Sarcasm** [comment]
This should not happen, your compile options are probably not properly set.
If you access an object macros aren't supposed to be shown, unless the code does not compile, in this case it fallbacks to things like that.

**Comment by Hjorthen** [comment]
I got it to lists the correct possibilities using C-M-i, but the drop-down list still displays globals(as seen in the picture)

**Comment by Hjorthen** [comment]
I'm an idiot. For some reason a .emacs file had snuck into my home directory, shadowing my ~/.emacs.d/init.el which then weren't loaded. It was only when I had to use some of my other settings I noticed this. Sorry for the inconvenience. This package is awesome :+1:
