### ISSUE TITLE
iotask: request for testing

### ISSUE THREAD

**Issue by Sarcasm** [Sarcasm/irony-mode#376]
I have been working on refactoring the irony-mode internals for a while now, it started 2 years ago and was halted for a long time because I was stuck on some bugs. Thanks to recent contributions from @3246251196 I got motivated back to work on irony-mode and finally debug the remaining issues.

I would probably need to make a proper change log but the highlight is:

- new internal API to make it easier to add new commands or new variants of commands
- speed up big query results (e.g. when there are many completion candidates)
- improve error reporting
- tasks can be run synchronously or asynchronously
- support for more than one unsaved buffer

I have been stuck with some bugs for a while, but now it seems like I have finally been able to fix them.
I would like to get some more testing before putting this on the master branch.

The idea is to check there is no regression on current features.

The 2 affected projects have a branch named `iotask-engine`:

- https://github.com/Sarcasm/irony-mode/tree/iotask-engine
- https://github.com/Sarcasm/company-irony/tree/iotask-engine

To test, make sure to have a git clone:

    git clone git@github.com:Sarcasm/irony-mode.git
    git clone git@github.com:Sarcasm/company-irony.git

And fetch the `iotask-engine` branch:

    git fetch origin
    git checkout iotask-engine

I was thinking maybe some of you could test and let me know if you detect any obvious issues.

TODO:

- [x] tag irony-mode and company-irony
- [x] update company-irony version requirement on irony-mode
- [x] release notes should mention the API change and what's new in this release (summarized above and in the merge commit)
- [x] document broken API: https://github.com/Sarcasm/irony-mode/issues/378
- [x] document that `  (define-key irony-mode-map [remap completion-at-point] 'irony-completion-at-point-async)` is no longer necessary in config

**Comment by Sarcasm** [comment]
@3246251196: thinking about you for testing for now, since you have been the most recurrent active person for now, also I think you are on Windows and I haven't tested the new branches much on this OS

**Comment by Sarcasm** [comment]
Ping @abo-abo!

It's possible that this breaks `counsel-irony`:

- https://oremacs.com/2017/03/28/emacs-cpp-ide/

`counsel-irony-callback` would need to take the candidates as parameter.

**Comment by abo-abo** [comment]
Is the change already in master?

**Comment by Sarcasm** [comment]
Nope, it's on a branch, I would prefer some early testing, but it will appear on master branch if no negative feedback. And if everything ok, I will make a new tag for MELPA stable.

**Comment by abo-abo** [comment]
> Feel free to test when it's on master.

Will do, thanks.

**Comment by 3246251196** [comment]
@Sarcasm 
I have pulled down the branch and just diff-ing to look at the changes. Anyway, I will test this at work since it is there that I use windows.

- Is this the chance to consider serialising translation units? 
- On my work machine I publicised irony-parse and added it to irony-mode-hook since in big projects + boost templates the initial request takes longer than if you ask to parse the TU on load. Would you consider publicising irony-parse?

**Comment by Sarcasm** [comment]
> Is this the chance to consider serialising translation units?

It's a possibility, don't know if it was blocking earlier.
What would be the purpose you have in mind? Latency, memory, both, something else?

> Would you consider publicising irony-parse?

No problem with that.
You aren't using flycheck?

**Comment by Sarcasm** [comment]
Change has been merged to master: https://github.com/Sarcasm/irony-mode/commit/d0748c9f808a23dbdb6e026d1660509a0ba59f51
I will wait a bit for feedback before pushing this to MELPA stable.

**Comment by abo-abo** [comment]
@Sarcasm Thanks, `counsel-irony` works now with irony-20170425.1135.

Most of completions work fine. However, this doesn't work:

    std::ifstream fin (fname);
    fin.|

I don't know if it worked before. The completion works for `std::vector` objects, but not for `std::ifstream`.

**Comment by Sarcasm** [comment]
I have uploaded 2 new changes, let me know if that works better.
I think it worked somewhat but was too noisy due to the inaccessible candidates showing up.

**Comment by Sarcasm** [comment]
Note: apparently I have changed another function you were relying on:

- `irony-completion--at-point-annotate` -> `irony-completion--capf-annotate`


Also, with a quick try I failed, but when the completion is candidate is inserted, there is an interesting function to call: `irony-completion-post-complete`. I thought I could add it to `ivy-read`'s `:action` but I failed. For example, if the candidate is a function, `irony-completion-post-complete` will insert the opening parenthesis of the function call.

**Comment by abo-abo** [comment]
Thanks for the pointer, I knew something looked strange:)

You can define obsolete aliases in Elisp:

```elisp
(define-obsolete-function-alias
    'irony-completion--at-point-annotate
    'irony-completion--capf-annotate
  "0.3.0")
```

I usually do this when I remove/rename a function. This way, both names exist, but the user is warned each time he uses the obsolete one.
And come version `"0.4.0"`, it's easy to remove the obsolete name, because all users were warned.

One more thing; with this:

    std::get|

the candidates are everything in `std::`, it's not narrowed to things that match `get`. The narrowing works for objects, not for namespaces.

**Comment by Sarcasm** [comment]
This is weird indeed.
I get a prompt weird prompt:

    490    code:

I don't know where this `490` comes from.
Do you have an idea?
Because the same completion works fine with `M-x completion-at-point RET`, so I'm thinking maybe it's coming from `ivy-read` or something like that?

Regarding the deprecation, I agree, I did not manage this correctly and did not want to make the effort afterward. Not nice, I know!

I have modified `counsel-irony` locally, you might be interested:

- rely only `irony-completion-at-point`, which unlike the weird previous version is now synchronous
- it gets the annotation-function from `irony-completion-at-point` results, it's no longer needed to rely on the capf annotate explicitely

```el
;;** `counsel-irony'                                                                                                                                                                                                 
;;;###autoload                                                                                                                                                                                                       
(defun counsel-irony ()                                                                                                                                                                                              
  "Inline C/C++ completion using Irony."                                                                                                                                                                             
  (interactive)                                                                                                                                                                                                      
  (let* ((coll (irony-completion-at-point))                                                                                                                                                                          
         (annotation-function (plist-get (nthcdr 3 coll) :annotation-function)))                                                                                                                                     
    (when coll                                                                                                                                                                                                       
      (setq ivy-completion-beg (nth 0 coll))                                                                                                                                                                         
      (setq ivy-completion-end (nth 1 coll))                                                                                                                                                                         
      (ivy-read "code: "                                                                                                                                                                                             
                (mapcar (lambda (x)                                                                                                                                                                                  
                          (counsel-irony-annotate x annotation-function))                                                                                                                                            
                        (nth 2 coll))                                                                                                                                                                                
                :caller 'counsel-irony                                                                                                                                                                               
                :action 'ivy-completion-in-region-action))))                                                                                                                                                         
                                                                                                                                                                                                                     
(defun counsel-irony-annotate (x &optional annotation-function)                                                                                                                                                      
  (cons                                                                                                                                                                                                              
   (concat x (and annotation-function (funcall annotation-function x)))                                                                                                                                              
   x))                                                                                                                                                                                                               
                                                                                                                                                                                                                     
(add-to-list 'ivy-display-functions-alist                                                                                                                                                                            
             '(counsel-irony . ivy-display-function-overlay))                                                                                                                                                        
                                                                                                                                                                                                                     
(declare-function irony-completion-at-point "ext:irony-completion")                                                                                                                                                  
```

Some questions:

- Do you think counsel could respect `:exit-function`? I'm thinking filling it for irony-completion at point.
  https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-Variables.html
- Is there already something in ivy/counsel that just serves as a fronted for completion at point? I'm wondering if `irony-completion-at-point` is specific in any way or if `ivy/cousel` could just support `:annotation-function` (and `:exit-function`) and be happy with it? I see this issue https://github.com/abo-abo/swiper/issues/331 with `counsel-at-point` in the title but I don't think it exists.

**Comment by Sarcasm** [comment]
New version released, closing.

**Comment by abo-abo** [comment]
Sorry for not getting back to you on this, got lost in the notifications.

> Is there already something in ivy/counsel that just serves as a fronted for completion at point?

Yes, `completion-at-point-functions` always works. So if a user does:

```elisp
(add-to-list 'completion-at-point-functions 'irony-completion-at-point)
```

ivy will be used for completion with `ivy-mode` on; and helm will be used with `helm-mode` on.

The only condition is that `irony-completion-at-point` has to conform to the interface, that is return all the candidates in a sync way. The reason why `counsel-irony` exists instead of just using `ivy-mode` is that irony's completion isn't sync. I don't know if it's reasonable to make it sync.  I'd say it's OK if it takes < 0.2s to return all the candidates. Otherwise, both helm and ivy have ways to handle async completion, something can be adapted there.

**Comment by Sarcasm** [comment]
Regarding the `std::get` issue, I have the following patch which fixes the issue:

```diff
From 2f6273c21fc6fa893416d0d147f5af5ca16d456c Mon Sep 17 00:00:00 2001
From: Guillaume Papin <guillaume.papin@epitech.eu>
Date: Thu, 18 May 2017 23:21:37 +0200
Subject: [PATCH] counsel-irony: use candidates provided to the async callback

---
 counsel.el | 34 ++++++++++++++++------------------
 1 file changed, 16 insertions(+), 18 deletions(-)

diff --git a/counsel.el b/counsel.el
index 0fc5f1e..867c81a 100644
--- a/counsel.el
+++ b/counsel.el
@@ -3596,31 +3596,29 @@ candidate."
   (interactive)
   (irony-completion-candidates-async 'counsel-irony-callback))
 
-(defun counsel-irony-callback (&optional _cands)
+(defun counsel-irony-callback (candidates)
   (interactive)
-  (let ((coll (irony-completion-at-point)))
-    (when coll
-      (setq ivy-completion-beg (nth 0 coll))
-      (setq ivy-completion-end (nth 1 coll))
-      (ivy-read "code: " (mapcar #'counsel-irony-annotate
-                                 (nth 2 coll))
-                :caller 'counsel-irony
-                :action 'ivy-completion-in-region-action))))
+  (let* ((symbol-bounds (irony-completion-symbol-bounds))
+         (beg (car symbol-bounds))
+         (end (cdr symbol-bounds))
+         (prefix (buffer-substring-no-properties beg end)))
+  (setq ivy-completion-beg beg
+        ivy-completion-end end)
+    (ivy-read "code: " (mapcar #'counsel-irony-annotate candidates)
+              :predicate (lambda (candidate)
+                           (string-prefix-p prefix (car candidate)))
+              :caller 'counsel-irony
+              :action 'ivy-completion-in-region-action)))
 
 (defun counsel-irony-annotate (x)
-  (cons
-   (condition-case nil
-       (concat
-        x " "
-        (irony-completion--capf-annotate x))
-     (error x))
-   x))
+  (cons (concat (car x) (irony-completion-annotation x))
+        (car x)))
 
 (add-to-list 'ivy-display-functions-alist '(counsel-irony . ivy-display-function-overlay))
 
 (declare-function irony-completion-candidates-async "ext:irony-completion")
-(declare-function irony-completion-at-point "ext:irony-completion")
-(declare-function irony-completion--capf-annotate "ext:irony-completion")
+(declare-function irony-completion-symbol-bounds "ext:irony-completion")
+(declare-function irony-completion-annotation "ext:irony-completion")
 
 ;;** `counsel-mode'
 (defvar counsel-mode-map
-- 
2.10.0

```

I'm not 100% sure that it's the expected behavior to filter the prefix with `:predicate`, but it works.
