### ISSUE TITLE
irony doesn't restart the server if it dies

### ISSUE THREAD

**Issue by ikirill** [Sarcasm/irony-mode#383]
If the server dies for some reason (say, because I attach a debugger to it), irony-mode keeps giving the error

    (irony-iotask-error "Process ain't running!")

and the error repeats because `irony--server-process` doesn't get reset to nil, so any attempt to interact with irony generates the error without restarting the process. When the process dies, it should probably work as if `irony-server-kill` got called (which runs `(setq irony--server-process nil)`). Calling `(setq irony--server-process nil)` restarts the server as expected.

**Comment by Sarcasm** [comment]
Thanks for making the issue, I saw it too but wasn't inspired for a fix at the time.
Should be fixed now, let me know if you still see something wrong.
