### ISSUE TITLE
Can not get irony to work with compile_commands.json from CMake/Ninja project.

### ISSUE THREAD

**Issue by Martinsos** [Sarcasm/irony-mode#386]
Hi @Sarcasm, first of all thanks a lot for creating this package!
I have been using Emacs for a few years, but have only now decided to make it a full-fledged C++ IDE, since I started working on a bigger C++ project where this would help a lot.

I have set up the irony-mode, company-irony and flycheck-irony and that seems to be ok, however I am stuck on correctly providing the irony with compilation database.

This is my irony setup:
```elisp
(req-package company-irony
  :config
  (progn
    (eval-after-load 'company '(add-to-list 'company-backends 'company-irony))))

(req-package flycheck-irony
  :config
  (progn
    (eval-after-load 'flycheck '(add-hook 'flycheck-mode-hook #'flycheck-irony-setup))))

;; Makes emacs an awesome IDE for C/C++.
(req-package irony
  :config
  (progn
    (unless (irony--find-server-executable) (call-interactively #'irony-install-server))
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'objc-mode-hook 'irony-mode)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)))
```

My C++ project looks like this:
```
- myproject/
  - core/ -> this is git repo, and all code is here
  - build/ -> this is out of source build, I run cmake from within it.
```

I build it by running `cmake -GNinja -c ../core/cmakeProfiles/myprofile.cmake ../core` from `build/` directory, and then `ninja`.

At first, irony-cdb-autosetup was picking up `.clang_complete` file that was present in `core/`, however that file is an outdated file that does not correctly define compiler flags, so auto-complete worked only partially (but from this, I can confirm that it did work) - flycheck reported that it could not find some of the header files included like `#include<myheader.h>`, and I confirmed that autocomplete also did not detect code from them, obviously because the compile flags were not set correctly.

I removed bad `.clang_complete` file, after which no cdb was detected (irony-cdb-menu says no dbs were detected).
I decided to generate `compile_commands.json`. I run `cmake` with needed flag, like this: `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja -c ../core/cmakeProfiles/myprofile.cmake ../core`, which generated `compile_commands.json`. I checked it out, it looked good, I run Emacs, but then I get an error: 

```
Error from syntax checker irony: Irony-Mode server error: parse-error, "failed to parse file", "/home/myname/git/myproject/core/MyprojectLib/Source/Myproject.cpp"
```

It generated following output in `/tmp/irony.*.log`:
```

execute: Command{action=Command::GetCompileOptions, file='/home/myname/git/myproject/core/MyprojectLib/Source/Myproject.cpp', unsavedFile='', dir='/home/myname/git/myproject/build/', line=0, column=0, flags=[], opt=off}
execute: Command{action=Command::GetCompileOptions, file='/home/myname/git/myproject/core/MyprojectLib/Source/Myproject.cpp', unsavedFile='', dir='/home/myname/git/myproject/build/', line=0, column=0, flags=[], opt=off}
execute: Command{action=Command::Parse, file='/home/myname/git/myproject/core/MyprojectLib/Source/Myproject.cpp', unsavedFile='', dir='', line=0, column=0, flags=['-x', 'c++', '-working-directory', '/home/myname/git/myproject/build', '-DBOOST_NO_CXX11_THREAD_LOCAL', '-DIMSHOW', '-DLOG_LEVEL=2', '-DMB_NOEXCEPT_EXCEPT_BADALLOC=TNUN_NOEXCEPT_EXCEPT_BADALLOC', '-DTNUN_MALLOC_OVERCOMMIT=TNUN_OVERCOMMIT_Partial', '-DTNUN_NOEXCEPT_EXCEPT_BADALLOC=', '-DTNUN_OVERCOMMIT_Disabled=0', '-DTNUN_OVERCOMMIT_Full=2', '-DTNUN_OVERCOMMIT_Partial=1', '-D_GLIBCXX_USE_CXX11_ABI=0', '-D__CURRENT_SRC_PATH__="/home/myname/git/myproject/core/MyprojectLib/.."', '-D__STDC_FORMAT_MACROS', '-I/home/myname/git/myproject/core/MyprojectLib/Source', '-isystem', '/home/myname/git/myproject/core/myproject-engine-bin/include', '-isystem', '/home/myname/git/myproject/core/myproject-engine-bin/include/utf8', '-I/home/myname/git/myproject/core/MyprojectUtils/Source', '-O3', '-DNDEBUG', '-fstrict-aliasing', '-fstrict-enums', '-fvisibility=hidden', '-fvisibility-inlines-hidden', '-fPIC', '-fdiagnostics-color', '-m64', '-std=gnu++14', '-fexceptions', '-fno-rtti', '-fomit-frame-pointer', '-ffunction-sections', '-fmerge-all-constants', '-fno-stack-protector', '-g', '-DALLOW_ASSERT_IN_RELEASE', '-DBOOST_ENABLE_ASSERT_HANDLER', '-UNDEBUG', '-Os', '-ffast-math', '-fno-finite-math-only', '-ffp-contract=fast', '-Wall', '-Wextra', '-Wstrict-aliasing', '-Werror', '-Wno-error=cpp', '-fno-omit-frame-pointer', '-std=gnu++14', '-include', '/home/myname/git/myproject/build/MyprojectLib-pch/CommonHeaders.h', '-Winvalid-pch'], opt=off}
```

I tried another approach, generating compile_commands.json using `bear ninja` command, but I again got the same error.

Finally, I also tried moving `build/` directory into `core` directory (I run cmake and everything from scratch ofcourse), but again I get the same error.

I have no idea what to do next and would appreciate any help! I am not sure what to debug next - I have a feeling that irony-server is failing because of the flags it is passed, but have no idea how to debug that.

One more question: how can I tell irony to use `compile_commands.json` instead of `.clang_complete`, without deleting/moving `.clang_complete` (somebody else put it in git repo and I would rather avoid dealing with it)?

**Comment by Sarcasm** [comment]
> One more question: how can I tell irony to use compile_commands.json instead of .clang_complete, without deleting/moving .clang_complete (somebody else put it in git repo and I would rather avoid dealing with it)?

You can customize the databases order: <kbd>M-x customize-variable RET irony-cdb-compilation-databases RET</kbd>. Chose this order for example:

- '(irony-cdb-libclang irony-cdb-clang-complete)

I customize this variable in my config for example: https://github.com/Sarcasm/.emacs.d/blob/811d883116eac3a5fad7c02275be4445ad1cd9f5/init.d/cc.el#L81-L83


Regarding the more important issue about the compile options, at a glance they look fine.
Some compile options are visible in <kbd>irony-cdb-menu</kbd>, right?

Does `clang++ -fsyntax-only ` complains if you use these options on the command line?

    clang++ -fsyntax-only -DBOOST_NO_CXX11_THREAD_LOCAL -DIMSHOW ... -std=gnu++14 -include /home/myname/git/myproject/build/MyprojectLib-pch/CommonHeaders.h -Winvalid-pch foo.cpp

**Comment by Martinsos** [comment]
Thanks for super-quick response!

Awesome, I added configuration as you described. What is the difference between `irony-cdb-libclang` and `irony-cdb-json`?

Yes, compile options are visible in `irony-cdb-menu`. I would copy-paste them, however it seems there is no way to do it hm. But they are consistent with compile_commands.json (however much shorter, it is just `Compilation Database: ...` `Working Directory: ...` and `Compile Options: ...`, with something in place of `...`. I guess it is just for the current buffer?

I am not sure what should I put instead of `foo.cpp`, something specific? I replaced `foo.cpp` with `/home/myname/git/myproject/core/MyprojectLib/Source/Myproject.cpp`.
I got an error: `no such file or directory: '...'`.
That seems to be `...` after `-DIMSHOW`. I removed `...` and run it again, and got:
```
error: input is not a PCH file:
      '/home/myname/git/myproject/build/MyProjectLib-pch/CommonHeaders.h.gch'
fatal error: file '/home/myname/git/myproject/build/MyprojectLib-pch/CommonHeaders.h.gch' is not a
      valid precompiled PCH file
2 errors generated.
```

**Comment by Martinsos** [comment]
Also: I see that you have `;; needs to declare irony-cdb for autoloads to work
  :config (use-package irony-cdb)` in your config, is that something I should also have? It seems to me that is not needed?

**Comment by Sarcasm** [comment]
> Awesome, I added configuration as you described. What is the difference between irony-cdb-libclang and irony-cdb-json?

json is an Elisp implementation, slower, the other ask libclang to do the parsing, it's faster.



> Yes, compile options are visible in irony-cdb-menu. I would copy-paste them, however it seems there is no way to do it hm

It's a bit tracky I have to admit.
You can if you do <kbd>M-x switch-buffer RET *Irony CDB[TAB] RET</kbd> (`TAB` is to get autocompletion).

> I am not sure what should I put instead of foo.cpp, something specific? I replaced foo.cpp with /home/myname/git/myproject/core/MyprojectLib/Source/Myproject.cpp.

You did the right thing, but the `...` were meant to be your actual compile options.

> Also: I see that you have
> 
> ;; needs to declare irony-cdb for autoloads to work
>   :config (use-package irony-cdb)
> in your config, is that something I should also have? It seems to me that is not needed?

Don't pay attention to my config, I just wanted to highlight the `setq` on the compilation databases list.

**Comment by Martinsos** [comment]
Got it!
Ok thanks, I managed to get the Irony CDB menu output, here it is:

```
Compilation Database: irony-cdb-json

Working Directory: /home/myname/git/myproject/build

Compile Options:   -DBOOST_NO_CXX11_THREAD_LOCAL -DIMSHOW -DLOG_LEVEL=2 -DMB_NOEXCEPT_EXCEPT_BADALLOC=TNUN_NOEXCEPT_EXCEPT_BADALLOC -DTNUN_MALLOC_OVERCOMMIT=TNUN_OVERCOMMIT_Partial -DTNUN_NOEXCEPT_EXCEPT_BADALLOC= -DTNUN_OVERCOMMIT_Disabled=0 -DTNUN_OVERCOMMIT_Full=2 -DTNUN_OVERCOMMIT_Partial=1 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CURRENT_SRC_PATH__="/home/myname/git/myproject/core/MyprojectLib/.." -D__STDC_FORMAT_MACROS -I/home/myname/git/myproject/core/MyprojectLib/Source -isystem /home/myname/git/myproject/core/myproject-engine-bin/include -isystem /home/myname/git/myproject/core/myproject-engine-bin/include/utf8 -I/home/myname/git/myproject/core/MyprojectUtils/Source -O3 -DNDEBUG -fstrict-aliasing -fstrict-enums -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -fdiagnostics-color -m64 -std=gnu++14 -fexceptions -fno-rtti -fomit-frame-pointer -ffunction-sections -fmerge-all-constants -fno-stack-protector -g -DALLOW_ASSERT_IN_RELEASE -DBOOST_ENABLE_ASSERT_HANDLER -UNDEBUG -Os -ffast-math -fno-finite-math-only -ffp-contract=fast -Wall -Wextra -Wstrict-aliasing -Werror -Wno-error=cpp -fno-omit-frame-pointer -std=gnu++14 -include /home/myname/git/myproject/build/MyprojectLib-pch/CommonHeaders.h -Winvalid-pch
```

I run `clang++ -fsyntax-only` with those compile parameters on that file, and got

```
error: unknown warning option '-Werror=cpp' [-Werror,-Wunknown-warning-option]
```

Then, I removed `-Wno-error=cpp` from compile options and run it again, but now I get:
```
error: input is not a PCH file: '/home/martin/git/photomath/build/PhotoMathLib-pch/CommonHeaders.h.gch'
fatal error: file '/home/martin/git/photomath/build/PhotoMathLib-pch/CommonHeaders.h.gch' is not a valid precompiled PCH
      file
2 errors generated.
```

I am guessing that this is something that works well with `c++` but now with `clang++`?

**Comment by Sarcasm** [comment]
Yeah, I'm not sure but I think PCH file format is different for each compilers. 
It would be best to generate a compilation database with Clang, or to do without the PCH

**Comment by Martinsos** [comment]
Ok thanks - sorry for spending your time on smt that turned out to be error specific for my setup.
Since using clang for compiling the project is not an option for me (I do not own a project!), and I can also not change the situation with PCH, I guess the best options is to go with .clang_complete.

**Comment by Martinsos** [comment]
Good news - I actually managed to use clang for the compiling of the whole project, it is not a problem it appears, so now it works great!
The only thing that seems not to work is header files hm. I guess cmake does not generate any entries for them? What do you advise regarding that?

**Comment by Sarcasm** [comment]
I'm working on https://github.com/Sarcasm/compdb to solve the header problem, but this is not very stable at the moment.

**Comment by Martinsos** [comment]
Awesome, looking forward to future versions of it!
I will try with `bear -a ninja`, and I will also try providing a `.clang-complete` file for header files to fall back to.
Thanks for all the help.
