### ISSUE TITLE
How can I installed irony-server by automatically?

### ISSUE THREAD

**Issue by YuanPres** [Sarcasm/irony-mode#391]
Hello :

I am creating an emacs configuration. 
I want to use your `irony-mode` to support c-c++ auto-complete.
But it's needs to install `irony-server`. 
So how can this service be installed automatically at the first startup?

Thank you very much.

**Comment by alexmurray** [comment]
I use the following:

```
(use-package irony
  :ensure t
  :init (unless (irony--find-server-executable)
          (call-interactively #'irony-install-server))
```

**Comment by YuanPres** [comment]
Thanks.
But my configuration project may not be compatible with the `use-package`.
Is it useful to use `add-hook`?
