### ISSUE TITLE
How to do to eliminate the error message displayed on the mini buffer

### ISSUE THREAD

**Issue by YuanPres** [Sarcasm/irony-mode#393]
Hello, I'm sorry to ask you a hand of a party problem ..........

I do not want the error message to be displayed on the macOS version ...I want to explain this thing in my README file. because they usually do not have CMake to install the server.

So do you provide an interface to ignore this error? I am sorry that my ability is limited, so I did not find it myself.

**Comment by Sarcasm** [comment]
I'm sorry but I'm not sure which message you are talking about.
Is it the one that ask to install irony-server?
If so, what do you propose to work around this?
Why use irony-mode if irony-server is not available?

**Comment by YuanPres** [comment]
So if I'm not sure if I can install irony-server, I might as well direct disable irony on macOS?

I have already maintained a configuration for my own use, but this configuration is used on multiple computers. Which has a limited software installation (need to pass the authentication) mac, it is not installed CMake, so can not install the server,
So every time you start emacs, C source code will always prompt to install the server ...

**Comment by Sarcasm** [comment]
Well, if you don't use irony-server, you might as well uninstall irony.
There could be some uses without in the future, but right now irony-mode without the server is not so useful.

I think CMake can easily be installed in a user directory, so this is an alternative.

**Comment by YuanPres** [comment]
Well, I'm going to add a judgment that makes irony disabled on macOS.

You know, sometimes the software can not be installed, not necessarily "technical" reasons. There may also be people who deliberately limit the installation for some purpose.

Thanks for your help.
