### ISSUE TITLE
About hook options

### ISSUE THREAD

**Issue by YuanPres** [Sarcasm/irony-mode#394]
Hello, sorry for taking your time.

When I use the `after-load`or some other conditions before `(add-hook 'c-mode-hook 'irony-mode-hook)`, it becomes unstable. Automatic completion will become a bit strange. 
e.g. 
In the same place, sometimes it outputs `printf (`, 
but sometimes it outputs `printf(const char *restrict __format, ...)`
My `irony` is latest version, and my `irony-server` is normal.
  
But I suspect that I was wrong. Here are some of the wording I've tried: 
1
```emacs-lisp
(after-load 'irony
(add-hook ‘c-mode-hook 'irony-mode))
```
2
```emacs-lisp
(after-load 'irony-mode
(add-hook 'c-mode-hook 'irony-mode))
```
3
```emacs-lisp
(when (package-installed-p 'irony)
(add-hook 'c-mode-hook 'irony-mode))
```

**Which is right ?**
  

Because there may be cases where the package is not installed, so I have to (should ? because I do not know much about `add-hook`) using some judgment mechanism to avoid the implementation of non-existent hooks.

Then... Is the `irony-cdb-autosetup-compile-options` only useful on installation `irony-server`? Does it affect the work of irony itself? I put this code into a different place, they seem to have different manifestations

Sorry for my English. And thank you very much.

**Comment by Sarcasm** [comment]
`after-load` does not exist.
There is `eval-after-load` and `with-eval-after-load`.

Anyway, I don't know how you installed irony-mode but the following should be ok:

```el
(when (package-installed-p 'irony)
  (add-hook 'c-mode-hook 'irony-mode))
```

**Comment by YuanPres** [comment]
Thank you very much.

Your way is right. it's normal now.

and...Is the irony-cdb-autosetup-compile-options only useful on installation irony-server?

**Comment by Sarcasm** [comment]
No, irony-cdb-autosetup-compile-options is useful when you use irony-mode

**Comment by YuanPres** [comment]
SO...Should I put it after `package-installed-p` ?
OR 
Or should I place it alone?

**Comment by Sarcasm** [comment]
If you want to configure irony-mode, only if it is installed, then you can take the instructions from the README:
- https://github.com/Sarcasm/irony-mode/tree/db29f5851cb75f30e0bd1840f60a9d7d0e0b6dc1#configuration

```el
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
```

But wrap them in:

```el
(when (package-installed-p 'irony)
  ...)
```

Which gives:

```el
(when (package-installed-p 'irony)
  (add-hook 'c++-mode-hook 'irony-mode)
  (add-hook 'c-mode-hook 'irony-mode)
  (add-hook 'objc-mode-hook 'irony-mode)

  (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))
```

**Comment by YuanPres** [comment]
Thanks.
