### ISSUE TITLE
irony-server exited with status 1

### ISSUE THREAD

**Issue by hisnawi** [Sarcasm/irony-mode#396]
I built llvm with clang and then the irony-server was built successfully.
However, when viewing a C file I get this error message:

Error while checking syntax automatically: (irony-server-error "irony-server is broken! /home/hisnawi/emacs.d/irony/bin/irony-server exited with status 1")

What did I do wrong?

**Comment by Sarcasm** [comment]
What happens if you run this command in a terminal?

    /home/hisnawi/emacs.d/irony/bin/irony-server

**Comment by hisnawi** [comment]
Interesting..this is what it shows:

```
/home/hisnawi/emacs.d/irony/bin/irony-server: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/hisnawi/emacs.d/irony/bin/irony-server)
/home/hisnawi/emacs.d/irony/bin/irony-server: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/hisnawi/emacs.d/irony/bin/irony-server)

```
I work on the company servers so have no root permissions and we have mostly outdated packages, so I tried to build everything needed for llvm/clang from scratch. I did include all the right flags (I believe) to build the server, this is the command I used:

```
cmake
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON
-DLIBCLANG_LIBRARY=/home/hisnawi/llvm_make/lib/libclang.so
-DLIBCLANG_INCLUDE_DIR=/home/hisnawi/llvm-3.7.0.src/tools/clang/include
-DCMAKE_CXX_COMPILER=/home/hisnawi/gcc_4.8/bin/g++
-DCMAKE_C_COMPILER=/home/hisnawi/gcc_4.8/bin/gcc
-DCMAKE_PREFIX_PATH=/home/hisnawi/llvm_make
-DCMAKE_INSTALL_PREFIX\=/home/hisnawi/emacs.d/irony/
/home/hisnawi/emacs.d/elpa/irony-20170523.618/server && cmake
--build . --use-stderr --config Release --target install

```

And it built successfully. Have I missed something?

**Comment by alexmurray** [comment]
You might need to set LD_LIBRARY_PATH to include the location of your updated libstdc++ to ensure this is used instead of the system version (which is old).

**Comment by hisnawi** [comment]
Thank you so much alexmurray. exporting LD_LIBRARY_PATH worked.
