### ISSUE TITLE
Fuzzy completion supported?

### ISSUE THREAD

**Issue by thisEric** [Sarcasm/irony-mode#398]
I've setup irony mode and it works perfectly except I cannot enable fuzzy completion with irony yet. I know it maybe an old topic, I googled but didn't get the answer I need. I am not very familiar with lisp programming: two questions:
1. Is fuzzy completion a backend's feature or feature in company-mode itself?
2. If it's backend's feature, doesn't irony have such support?

I googled there is something like company-flx looks support such feature, but in the document it said only support company-capf backend. How can I make irony to support fuzzy completion just like ycmd(I didn't try with ycmd, just googled)? thanks

**Comment by Sarcasm** [comment]
> Is fuzzy completion a backend's feature or feature in company-mode itself?

A backend feature I believe.

> If it's backend's feature, doesn't irony have such support?

Irony has no such support.

> How can I make irony to support fuzzy completion just like ycmd(I didn't try with ycmd, just googled)?

If I had to implement it, which I already thought about but never did, I would do it irony-server side.
I would add a command that takes a prefix string and return the candidates.
Naturally the company-irony or maybe a new backend, would call this new server command.

There is nothing special about implementing it I think, just write some Elisp and C++, and mostly have the time and envy to do it seriously.

**Comment by thisEric** [comment]
thanks, then I closed this issue, hope it will be supported someday.
