### ISSUE TITLE
-include doesn't work

### ISSUE THREAD

**Issue by kangjianbin** [Sarcasm/irony-mode#401]
I found that -include doesn't work. I created 3 files: a.c, inc.h and .clang_complete

a.c:
```c
int main(int argc, char *argv[])
{
	printf("hello world\n");
	return 0;
}
```

inc.h
```c
#include <stdio.h>
```
.clang_complete
```
-include inc.h
```

Flycheck reported the warning:
```
implicitly declaring library function 'printf' with type 'int (const char *, ...)'
```

My Irony version is:
```elisp
;; Author: Guillaume Papin <guillaume.papin@epitech.eu>
;; Version: 0.2.2-cvs
```

**Comment by Sarcasm** [comment]
As it is for the moment, the `.clang_complete` file should contain one compile option per line.

That is:

    -include
    inc.h

**Comment by kangjianbin** [comment]
Thanks, it works.
