### ISSUE TITLE
Cannot import std headers

### ISSUE THREAD

**Issue by nico202** [Sarcasm/irony-mode#402]
Hi, I'm using irony with compile_commands.json generated by meson/ninja.
irony can find project headers, but complains #include -ing things like:
iostream, vector, string, unistd.h....
clang itself *is* able to compile those though.

Thanks a lot for this, 
Nicolò

**Comment by Sarcasm** [comment]
Can you show what the compilation database looks like?

**Comment by nico202** [comment]
`Compilation Database: irony-cdb-libclang

  Working Directory: /home/IITaudio/Scm/Git/HapticDEMO/buildClang
  Compile Options:   -Isrc/H4F@sha -Isrc -I../src -Iinclude -I../include -I../subprojects/chai3d/include -Isubprojects/chai3d -I../subprojects/chai3d -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -DLINUX -fPIC -pthread -MMD -MQ src/H4F@sha/._api.cc.o -MF src/H4F@sha/._api.cc.o.d

[q] to quit`

**Comment by Sarcasm** [comment]
Hum, this looks reasonable.
I should probably give meson a try at some point, but I don't have time these days.

**Comment by felipeagc** [comment]
I'm also having the same issue, but wasn't having it 2 days ago though (before a clang update on arch linux). Maybe that's the reason. I dual boot with ubuntu, so I tried it there and it still works. Also using the meson/ninja combination.

**Comment by Sarcasm** [comment]
Interesting, maybe you need to recompile irony-server: <kbd>M-x irony-install-server RET RET</kbd>

**Comment by felipeagc** [comment]
I just did, but it still doesn't work.

CMake gives me this warning but it still compiles:
```
CMake Warning at cmake/CheckLibClangBuiltinHeadersDir.cmake:87 (message):
  CheckLibClangBuiltinHeadersDir: unsupported configuration, please report.

    Check with args: /tmp/build-irony-server-1.0.0/CMakeFiles/CMakeTmp/check-libclang-stddef.cpp
    Check output:
      /tmp/build-irony-server-1.0.0/CMakeFiles/CMakeTmp/check-libclang-stddef.cpp:1:10: fatal error: 'stddef.h' file not found

  argv[1]:
  /tmp/build-irony-server-1.0.0/CMakeFiles/CMakeTmp/check-libclang-stddef.cpp

Call Stack (most recent call first):
  src/CMakeLists.txt:8 (check_libclang_builtin_headers_dir)
```

**Comment by Sarcasm** [comment]
Apparently Arch Linux provides Clang 4.0.1 even though I did not get a release mail from LLVM, nor can I see it on http://releases.llvm.org/

At some point I'm supposed to update FindLibClang.cmake to handle new releases automatically, but this is not done yet.

**Comment by felipeagc** [comment]
Ok, it works now. Thanks for the help!

**Comment by nico202** [comment]
Unfortunatly, this is not the case for me. My clang version is:
`clang version 3.9.1 (tags/RELEASE_391/final)`

and my irony-server version:
```
irony-server version 0.2.1
clang version 3.9.1 (tags/RELEASE_391/final)
```

**Comment by Sarcasm** [comment]
Current version on MELPA stable is 1.0.0, you should probably update:

- http://stable.melpa.org/#/irony

**Comment by nico202** [comment]
Upgraded to 1.0.0. 

irony-server version 1.0.0
clang version 3.9.1 (tags/RELEASE_391/final)

Still, the problem remains. Is it possible to manually add include paths to irony only?

**Comment by Sarcasm** [comment]
Yes, but which ones?

irony-additional-compile-options can be configured.

**Comment by nico202** [comment]
The gcc c++/include path? Maybe specifying it manually does work
