### ISSUE TITLE
What is the difference between the two frontends?

### ISSUE THREAD

**Issue by ReimuXMX** [Sarcasm/irony-mode#405]
`completion-at-point-functions` or `company-irony` What different?

If I have installed and configured `company-capf`, do I need to install `company-irony`?

**Comment by Sarcasm** [comment]
company-irony is asynchronous and can give better annotations. The capf interface is useful when using completion-at-point.

**Comment by ReimuXMX** [comment]
So if I don't need the "better annotations (I know what that is)", Do I need `company-irony` ?

Because the `company-irony` seems to block the completion of other backends (such as company-dabbrev and company-c-headers).

My configuration ：
```emacs-lisp
(add-hook 'c-mode-hook
          (lambda ()
            (setq-local company-backends '((company-irony company-c-headers company-dabbrev)
                                           company-files))))
```
I write so, the results of other back-end still does not work.

**Comment by Sarcasm** [comment]
I think your issue has been fixed in company-irony, see the discussion here:

- https://github.com/Sarcasm/company-irony/issues/35#issuecomment-307660004

Maybe you just need to upgrade company-irony?

**Comment by ReimuXMX** [comment]
Yes. I upgraded it.

**Comment by ReimuXMX** [comment]
Ok ... I tried to modify the global variable: `company-backends`, but it was invalid.

I removed the `company-irony` backend and used the `company-capf` for auto-complete ... that's enough
