### ISSUE TITLE
A way to control when irony checking would stop

### ISSUE THREAD

**Issue by hisnawi** [Sarcasm/irony-mode#406]
For clang the option -fmax-errors decides when to stop finding errors.
For Irony I noticed it is 20.
Is there a way to change that? I am looking for all errors and I don't want Irony to stop emitting errors.

**Comment by Sarcasm** [comment]
I think you can configure this in `irony-additional-clang-options`:

- <kbd>M-x customize-variable RET irony-additional-clang-options RET</kbd>

**Comment by hisnawi** [comment]
Thanks
