### ISSUE TITLE
Error from syntax checker irony: Bad I/O task data

### ISSUE THREAD

**Issue by JerryMaxCN** [Sarcasm/irony-mode#408]
When I first use #include and tap C-x C-s, there are some issues accur and I need some help!
Is this caused by libclang's location?

Error from syntax checker irony: Bad I/O task data: [cl-struct-irony-iotask-packaged-task (:start (lambda (process buffer) (if (assq buffer (process-get process :unsaved-buffers)) (irony--server-send-command "reset-unsaved" (irony--get-buffer-path-for-server buffer)) (irony-iotask-set-result t))) :update irony--server-command-update :finish (lambda (process buffer) (process-put process :unsaved-buffers (assq-delete-all buffer (process-get process :unsaved-buffers))))) (#<process Irony> #<buffer main.cpp>) [cl-struct-irony-iotask-result error nil irony-iotask-bad-data (#0 "(error . (no-such-entry \"failed reset unsaved buffer\" \"/home/isacfan/main.cpp\")

**Comment by JerryMaxCN** [comment]
OK, I have found the causes！

**Comment by hisnawi** [comment]
Could you share the causes? I am seeing the same issue as well.

**Comment by JerryMaxCN** [comment]
Another plugin is in conflict with irony-mode, I forget which plugin is. Maybe yasnippet? I will check my git history unless you find the causes.

**Comment by hisnawi** [comment]
I use yasnippet, but I did not disable it to verify if they conflict. So is there a fix other than disabling yasnippet?

**Comment by fleimgruber** [comment]
@JerryMaxCN I am also seeing this and trying to find the cause.  It would be very helpful if you could share some of your insights.

**Comment by asandroq** [comment]
I have this same problem in two environments and only one has yasnippet installed. One is Ubuntu Linux and the other one is macOS High Sierra, both using LLVM binaries downloaded from llvm.org.
