### ISSUE TITLE
Company: An error occurred in auto-begin

### ISSUE THREAD

**Issue by mambolevis** [Sarcasm/irony-mode#417]
Hi,

The following error message appears today:

```
Company: An error occurred in auto-begin
Wrong number of arguments: ((t) (callback) (let ((it (irony-completion-symbol-bounds))) (if it (let ((--cl-cb-- (make-symbol "--cb--"))) (let* ((v --cl-cb--)) (set v callback)) (irony--run-task-asynchronously (irony--candidates-task nil (car it)) (list (quote lambda) (quote (&rest --cl-rest--)) (list (quote apply) (list (quote quote) (function (lambda (G1 candidates-result) (funcall (symbol-value G1) (irony-completion--filter-candidates (irony-iotask-result-get candidates-result)))))) (list (quote quote) --cl-cb--) (quote --cl-rest--))))) (progn (funcall callback nil))))), 3
```
Do you have any idea about this issue?

Regards,
Levis

**Comment by Sarcasm** [comment]
Hum, just a quick guess, but did you upgrade both irony-mode and company-irony or just the former?

**Comment by mambolevis** [comment]
Yes, both. 
I am testing right now because I only updated one computer.

**Comment by mambolevis** [comment]
If I update the following packages the problem appears

![image](https://user-images.githubusercontent.com/13024208/29733153-264e8286-89ec-11e7-933b-0a3a6d2cf7b2.png)

**Comment by mambolevis** [comment]
I update only irony without problems. 

![image](https://user-images.githubusercontent.com/13024208/29733419-4cebe9dc-89ed-11e7-9589-770e51d92044.png)

I confirm that the problem is in `company-irony`

**Comment by Sarcasm** [comment]
What happens if both irony and company-irony are at melpa version 20170821? You don't seem to be on the latest version on any of those.

**Comment by mambolevis** [comment]
In my case this melpa combination work properly: 
```
irony-20170821.1300
company-irony-20170612.1308
```
But the following combination don't work:
```
irony-20170821.1300
company-irony-20170821.1306

```
In my case I need to build irony-server separately using visual studio. I tried to build irony-server yesterday but I couldn't, and for that reason, I opened and extra issue.

**Comment by mambolevis** [comment]
I applied the patchs from `https://github.com/Sarcasm/irony-mode/pull/419` to build the server. 
I also updated both latest versions of irony and company-irony, and everything is working fine.
