### ISSUE TITLE
Cannot complete in irony-mode

### ISSUE THREAD

**Issue by jharwell** [Sarcasm/irony-mode#420]
Hi, 

First of all--great work with irony-mode! Been using it extensively for about a year now. In the last week or so I've started having problems getting irony to complete anything, and get errors like this whenever I trigger completion:

    `Debugger entered--Lisp error: (error "Unknown upattern `(quote smart)'")
      signal(error ("Unknown upattern `(quote smart)'"))
      error("Unknown upattern `%s'" (quote smart))
      pcase--u1(((match company-irony-ignore-case quote smart)) #[257 
  
  "\302\301\242>\204^N^@\301\302\301\242B\240\210\303\302A!\203^Y^@\304\202^Z^@\300\302A^B\"\207" [#[514 "\211C^B\301\242\236\211\204 ^@\302^D^C\242\"\301^E^D\242^CE\301\242$
      pcase--u((((match company-irony-ignore-case quote smart) #[257 "\302\301\242>\204^N^@\301\302\301\242B\240\210\303\302A!\203^Y^@\304\202^Z^@\300\302A^B\"\
    207" [#[514 "\211C^B\301\242\236\211\204 ^@\302^D^C\242\"\301^E^D\242^CE\301\242B$
      pcase--expand(company-irony-ignore-case (((quote smart) (quote smart-case)) ((quote nil) (quote 
    exact)) (other (quote case-insensitive))))
      #[385 "\301^A@^H\"^B^A@\232\203 ^@^A^A\211A@\262^A\232\203 
  
  ^@\211\211AA\262^A\202:^@\211\203(^@\302\303!\210\304^C^C\"\305^C@^E^E^DBB^H#\210\211\262^A\207" [pcase--memoize gethash message "pcase-memoize: equal first branch, yet differe$
      (pcase company-irony-ignore-case ((quote smart) (quote smart-case)) ((quote nil) (quote exact)) ( 
    (other (quote case-insensitive)))
      company-irony--get-matching-style()
  (irony-completion-candidates-async (function (lambda (candidates) (funcall callback (company-irony--make-candidates candidates)))) prefix (company-irony--get-matching-style))
  (closure ((prefix . "") t) (callback) (irony-completion-candidates-async (function (lambda (candidates) (funcall callback (company-irony--make-candidates candidates)))) prefix (company-irony--get-matching-style)))(#[257 "\300\305\303\3$
  #[257 "\302C\303\304\300\"C\305\306\307\310\311\301^F^H^F^H^F^H$\312\"\313\314%\300\211\205a^@\211@^D\302^F^F\242B\240\210^D\242^A@^BA\305\315\316\310\311^F^K^F^K^F  ^F      ^F      %\317\"\320\321%^B\242\322=\204Q^@\211^C!\210\202X^@^$
  company--force-sync(company-call-backend-raw (candidates "") (company-irony))
  company-call-backend(candidates "")
  company--fetch-candidates("")
  company-calculate-candidates("")
  #[0 "\n\203   ^@\nC\202\n^@^K\211\205\207^@\211@\300^A9\204^\^@\306^B!\203(^@\307^B!\205,^@^A\310!\202,^@\311^B\310\"\240\210\300\242\203\200^@\312\300\242!\203z^@\313\300\242!^T\211^R\301\314\f!\240\210\301\242:\204c^@^M\203U^@\315\31$
  funcall(#[0 "\n\203   ^@\nC\202\n^@^K\211\205\207^@\211@\300^A9\204^\^@\306^B!\203(^@\307^B!\205,^@^A\310!\202,^@\311^B\310\"\240\210\300\242\203\200^@\312\300\242!\203z^@\313\300\242!^T\211^R\301\314\f!\240\210\301\242:\204c^@^M\203U^$
  company--begin-new()
  company--perform()
  #[0 "\301 \210^H\207" [company-candidates company--perform] 1 "\n\n(fn)"]()
  funcall(#[0 "\301 \210^H\207" [company-candidates company--perform] 1 "\n\n(fn)"])
  company-auto-begin()
  company-manual-begin()
  company-complete-common()
  (cond ((and (not (use-region-p)) (irony--check-expansion)) (message "complete") (company-complete-common)) (t (message "indent") (call-interactively (quote c-indent-line-or-region))))
  irony--indent-or-complete()
  call-interactively(irony--indent-or-complete nil nil)
  command-execute(irony--indent-or-complete)
`
Any ideas?

**Comment by Sarcasm** [comment]
I have uploaded a fix, let me know if that works for you.

**Comment by jharwell** [comment]
Thanks for the quick response! Unfortunately, I'm still getting the same error, with the same elisp backtrace. Is this something caused by a new version of company? I did recently purge and re-download all my packages from MELPA, and so far irony appears to be the only casualty.

**Comment by Sarcasm** [comment]
Melpa is not instantaneous, maybe you can retry now?
Also, you have to quit Emacs so that the package is reloaded.

**Comment by jharwell** [comment]
I had cloned the updated .el files from github, and then used them to replace the MELPA version. I tried it again with cloning from MELPA today though just for grins, and got the same error :-(

**Comment by Sarcasm** [comment]
If you do <kbd>M-x find-variable RET irony--t-candidates RET</kbd>, do you see `pcase` or `cl-case`?

**Comment by jharwell** [comment]
I see `cl-case`, and when I try to load my irony-mode config, I get this:

`Eager macro-expannsion failure:(error "Unknown pattern '(quote smart)'")`

**Comment by Sarcasm** [comment]
I have uploaded a fix in `company-irony`, hopefully it will be good this time.

**Comment by jharwell** [comment]
That appears to have done it! It seems to be working much more speedily on my machine as well. Thanks for the great work--this is by far the most useful emacs plugin I use for programming.

**Comment by Sarcasm** [comment]
Great to hear, thank you for reporting these issues.
