### ISSUE TITLE
Flycheck with Irony showing different result than when choosing the c/c++-clang option in flycheck

### ISSUE THREAD

**Issue by hisnawi** [Sarcasm/irony-mode#430]
I installed irony with clang and enabled the checker in Flycheck.
But then, I tried selecting the c/c++-clang checker in Flycheck (instead of irony), that I see more meaningful errors.

This is the compilation command when using c/c++-clang:

clang -fsyntax-only -fno-color-diagnostics -fno-caret-diagnostics -fno-diagnostics-show-option -iquote /Users/hisnawi/Dropbox/Coding/cpp_code/DP/ -std\=c\+\+11 -Wall -Wextra -x c\+\+ - < /Users/hisnawi/Dropbox/Coding/cpp_code/DP/uniquePaths.cpp

Since irony is using same Clang, shouldn't it give kind of the same errors? 

How do I find what irony compilation command is, so I could compare? Maybe it is some extra settings.

**Comment by Sarcasm** [comment]
> Since irony is using same Clang, shouldn't it give kind of the same errors?

It should indeed.

> How do I find what irony compilation command is, so I could compare? Maybe it is some extra settings.

You can do <kbd>M-x irony-cdb-menu RET</kbd>.
If you don't have flags like `-Wall` or property include search paths set, the diagnostics won't be good.

**Comment by hisnawi** [comment]
Tried that but it tells me:

no compilation database in use.

With only quit option. No other option does anything, it freezes till I hit q for quit.

**Comment by Sarcasm** [comment]
You have to provide a compilation database:

- https://github.com/Sarcasm/irony-mode#compilation-database

**Comment by hisnawi** [comment]
Oh...I did not know that. I am now working on single files, not a big project so I don't need to have a database. But it seems for irony to work it needs some kind of a database. I will pass until I start a new big project. Until then I will use c/c++-clang that comes with flycheck.

**Comment by alexmurray** [comment]
FYI - a simple .clang_complete file in the same directory as the source files would likely suffice with the following contents:
```
-std=c++11
-Wall
-Wextra
```

**Comment by hisnawi** [comment]
Helpful as usual Alex. Thank you very much.
