### ISSUE TITLE
Fix Gentoo's clang-5 installation

### ISSUE THREAD

**Issue by DirtYiCE** [Sarcasm/irony-mode#439]
#368 fixed gentoo's clang-4 installation, but now with clang-5 out, it broke again. It's installed into `/usr/lib64/llvm/5/`, so `LIBCLANG_KNOWN_LLVM_VERSIONS` in `FindLibClang.cmake` should include version `5` too (and probably `6` for forward compatibility).

**Comment by Sarcasm** [comment]
Thanks for the head up, this is fixed.
