### ISSUE TITLE
I would like to write a manpage for irony-server

### ISSUE THREAD

**Issue by sten0** [Sarcasm/irony-mode#440]
Hi!

I would like to start work on a simple manpage for irony-server.  I'm investigating pod, txt (via txt2man), asciidoc, and .org as possible source formats.  There's also rst (reStructuredText)...  I'm sure there are also several markdown formats, and each one has an emacs mode.  Do you have a preference for any of these?

Please let me know as soon as you can :-)

Cheers,
Nicholas

**Comment by sten0** [comment]
I can also submit a troff file, if you'd prefer...

**Comment by Sarcasm** [comment]
I have a preference for rst if it's possible to get a clean result with it. :)

**Comment by Sarcasm** [comment]
Closing this one as the discussion happens on the PR now. :)
