### ISSUE TITLE
What version/commit of clang-tools-extra was server/run-clang-tidy.py merged from?

### ISSUE THREAD

**Issue by sten0** [Sarcasm/irony-mode#443]
Hello again!

I'm having trouble tracking down the upstream source for 8468de9.  What I tried so far was simple diffing against each commit in https://github.com/llvm-mirror/clang-tools-extra/commits/master/clang-tidy/tool/run-clang-tidy.py but there were no 100% matches.

Would you please confirm what version you merged so that I can update the debian/copyright?  From what I can tell run-clang-tidy.py needs to be attributed to both "University of Illinois at Urbana-Champaign" and to you under the NCSA license.

Thank you!
Nicholas

**Comment by sten0** [comment]
My best guess for the youngest it could possibly be is https://reviews.llvm.org/D5188

And my best guess for the oldest it could possibly be is llvm-mirror/clang-tools-extra@c2e903ec98385b82e35bdb303e411854a2e8c032

**Comment by sten0** [comment]
Would it be possible to depend on upstream run-clang-tidy.py instead?  I was referred to https://wiki.debian.org/EmbeddedCodeCopies when I asked #debian-mentors about this.

**Comment by Sarcasm** [comment]
I'm pretty sure I copied it from this tree, which seems to be your best guess, so good job! :+1: 
- https://github.com/llvm-mirror/clang-tools-extra/blob/c2e903ec98385b82e35bdb303e411854a2e8c032/clang-tidy/tool/run-clang-tidy.py

Then I added modifications so that I find it suitable to run on Travis, i.e. it honors exit code of the underlying processes causing build issues on pull requests.
Arguably, these changes could be upstreamed, but they are not and I need them, so I will keep this copy.

Please note that this script is used only for local development and check of pull requests.
If you intend to package irony-mode, it is not supposed to be part of the distributed binary package.

**Comment by sten0** [comment]
Sweet! :-)  Thank you for the confirmation and the explanation.  Yes, Debian packaging of irony-mode does not include run-clang-tidy.py in the binary package; however, documentation of copyright in src packages is also very strict, which is why I had to look into this.  I've referenced this issue in the source package, and made a copy of your reply in case the URL disappears at some point in the future.  If this is unacceptable please let me know asap.

This issue can be closed now.

**Comment by Sarcasm** [comment]
Do you think I should add a copy of the LLVM license?

It's true that the script shows the following in the header:

```
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
```

But I don't provide the LICENSE.TXT, so maybe I need to edit this header to contain the full text or point to another file in irony-mode sources directly.
Do you have a link to the package you made or the discussion?

**Comment by sten0** [comment]
On Wed, Oct 18, 2017 at 09:00:36PM +0000, Guillaume Papin wrote:
>    Do you think I should add a copy of the LLVM license?
> 
>    It's true that the script shows the following in the header:
> 
>  # This file is distributed under the University of Illinois Open Source
>  # License. See LICENSE.TXT for details.
> 
>    But I don't provide the LICENSE.TXT, so maybe I need to edit this header
>    to contain the full text or point to another file in irony-mode sources
>    directly.
>    Do you have a link to the package you made or the discussion?

Vcs-Git: https://anonscm.debian.org/git/pkg-emacsen/pkg/irony-mode.git
Vcs-Browser: https://anonscm.debian.org/git/pkg-emacsen/pkg/irony-mode.git

The discussion was on IRC OFTC/#debian-mentors and I'm not sure if
it's logged somewhere.

Good point!  That would remove any ambiguity for everyone in the
future.  Ideally I think it would be best to have
clang-tools-extra/LICENSE.TXT in the same directory as
run-clang-tidy.py, and that copy of LICENSE.TXT should come from the
clang-tools-extra@commit where ran-clang-tidy.py was forked.  That way
you won't need to modify the header.

Additionally clang-tools-extra/CODE_OWNERS.TXT should also be in ./ of
run-clang-tidy.py (also from clang-tools-extra@commit)

Cheers,
Nicholas

**Comment by Sarcasm** [comment]
Thanks!
