### ISSUE TITLE
Help setup auto-complete on Windows/MinGW64

### ISSUE THREAD

**Issue by yoacompsci** [Sarcasm/irony-mode#444]
Hello Guillaume,
I‘ve download the “LLVM source code (.sig)” and “Clang source code (.sig)” and build Clang on Windows/MinGW. After that, I’ve install emacs (25.1) and install the following three packages from melpa:
-	irony
-	company
-	company-irony
My init.el file configuration is the next (nothing else):

```el
;----------------------------------------------------------------------------------------------------
; start package.el with emacs
(require 'package)
; add MELPA to repository list
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
; initialize package.el
(package-initialize)

;; Enable company in all major modes
(add-hook 'after-init-hook 'global-company-mode)
; Load company backends
(eval-after-load 'company
  '(add-to-list 'company-backends 'company-irony))

;; Irony mode
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

(when (boundp 'w32-pipe-read-delay)
  (setq w32-pipe-read-delay 0))
;; Set the buffer size to 64K on Windows (from the original 4K)
(when (boundp 'w32-pipe-buffer-size)
  (setq irony-server-w32-pipe-buffer-size (* 64 1024)))
;------------------------------------------------------------------------------------------------
```

After that, I proceed to compile the Irony-server. The followed steps have been the next ones:
1. cd to Irony’s package site.

        D:\hh_home\.emacs.d\elpa\irony-20171002.1130\server

2. create build directory.
        mkdir build && cd build

3. compile with cmake(cmake-3.9.4-win64-x64) typing in cmd these three commands

        cmake -DLIBCLANG_LIBRARY=D:\tt_tools\LLVM\5_0_0\llvm\bin\libclang.dll -G "MinGW Makefiles" ..
        mingw32-make
        "cmake" "-DCMAKE_INSTALL_PREFIX=d:/hh_home/.emacs.d/irony/" "d:/hh_home/.emacs.d/elpa/irony-20171002.1130/server" && "cmake" --build . --use-stderr --config Release --target install

Everything seems OK at this point. I checked that the Cmake placed irony-server.exe in the specified folder.
After that, I run emacs with simple hello.cpp file and check emacs starts in company-mode and irony-mode activated but irony-server.exe is not running. 
Just when I type M-x company-irony is when irony-server.exe starts but doesn’t show anything related apparently with the completion at point should be and seems that company-irony mode is deactivated automatically even with company-mode and irony-mode are active.
Additionally I checked i.e: std::vector<int> vec; vec. ¿? and doesn’t show anything and the when I type M-x company-mode the buffer says “Cannot complete at point”.
To specify the compilation flags and the system header locations I’m using the following .clang_format file in D:\

--------------------------------------------------------------------------------------------------------------

```
-std=c++14 
-target
x86_64-w64-mingw32
-Wall
-pedantic
-DDEBUG
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/bits
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/x86_64-w64-mingw32
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/backward
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/include
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include
```
---------------------------------------------------------------------------------------------------------

I’ve obtained the location of my paths typing `cpp -xc++ -Wp,-v < NUL`  and copying literally from …search stars here. By the way: gcc version 7.2.0 (GCC), Target: x86_64-w64-mingw32 and Thread model: posix.
I’ve made a lot of test to try to enable this feature but nothing… :-( 
Hope someone can help me litle bit…
Many thanks

**Comment by yoacompsci** [comment]
Sorry for the format,

**Comment by Sarcasm** [comment]
If fixed up the formatting.

Did you notice the 2 wiki pages?
- https://github.com/Sarcasm/irony-mode/wiki/Setting-up-irony-mode-on-Windows
- https://github.com/Sarcasm/irony-mode/wiki/Setting-up-irony-mode-on-Windows-using-MSVC

I recommend that you test checking `irony-server --version` in the terminal.
Then you try a project that require zero compile options, just trying to complete a locally defined struct members for example.
If `--version` works but not the completion, then you have to try completion directly using the irony-server command, but this is slightly annoying to do.

From experience, Windows can be silent if you don't launch from `cmd.exe` sometimes, never understood why, but if an application just execute without any message I have found useful to try in cmd.exe.

**Comment by yoacompsci** [comment]
Hello Guillaume,
After reading the 2 wiki pages, I found that my emacs *exec_path* was not properly configured. After fixed that issue, in a simple *test.cpp file*, I have checked with irony-mode activated, at completion point, company-irony is automatically activated in the mode line. 

All the local completions that I have made shows the correct completion options.

Then I try with one .clang-complete file to make STL completions, but the message “No completion found, user-error: Cannot complete at point” was shown.

`-std=c++14 
-target
x86_64-w64-mingw32
-Wall
-pedantic
-DDEBUG
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/bits
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/x86_64-w64-mingw32
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../include/c++/7.2.0/backward
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/include
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/include-fixed
-ID:\tt_tools\mingw\distro\15_3\bin\../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/include
-ID:\tt_tools\LLVM\5_0_0\llvm\lib\clang\5.0.0\include
-ID:\tt_tools\LLVM\5_0_0\llvm\include` 

I get the paths shown in the .clang-complete file typing in the cmd:

`cpp -xc++ -Wp,-v < NUL
clang++ -E -x c++ - -v < NUL`

copying literaly just before 

`#include <...> search starts here:...`

This file was in the same path of the test.cpp file. I made some test copying the .clang-format file to different locations(home, etc...), modifying the content of the .format-clang file but didn´t work. Would be possible to get the system headers completions with the .clang-format?
Many thanks

**Comment by Sarcasm** [comment]
When you say `.clang-format`, do you mean `.clang_complete`?
Is the output of <kbd>M-x irony-cdb-menu RET</kbd> correct?

**Comment by yoacompsci** [comment]
Hello Guillaume,
No, it was a mistake that I made with the name of the file. After chanche it, the local and system header completions works fine, solved. Now I have this great tool in my configuration to start to work with it.

Only one question more related with the `.clang_complete` file, it must be in the same root of each file or project or can be in one common location to all the files or projects I’m working with, i.e: home directory, or another specific folder for company-irony.
Many thanks

**Comment by eksea** [comment]
@Sarcasm 
I followed the wiki https://github.com/Sarcasm/irony-mode/wiki/Setting-up-irony-mode-on-Windows
I installed cmake via pacman, but cmake generator doesn't contain "MSYS Makefiles". All generators lists below:
![image](https://user-images.githubusercontent.com/8746029/32584079-a4a64788-c531-11e7-9345-22d1d1d4d61c.png)

**Comment by cy20lin** [comment]
@eksea 
Maybe you can use "Unix Makefiles" Instead.
```sh
# install make 
pacman -S make
# build irony-server
cmake -GUnix\ Makefiles /path/to/irony-mode/server
```

**Comment by eksea** [comment]
@cy20lin 
I solved the problem by "pacman -S mingw-w64-x86_64-cmake"
Thanku  all the same.

**Comment by yoacompsci** [comment]
Hello Guillaume, 
This issue could be closed as solved.
Thanks for the support!!!

**Comment by Sarcasm** [comment]
Great, thank you for telling me.
