### ISSUE TITLE
latest use-package-20171203.1313 broke irony

### ISSUE THREAD

**Issue by mambolevis** [Sarcasm/irony-mode#452]
Hi,

It is just for information:
With the latest update of (use-package-20171203.1313) from MELPA, Irony mode doesn't work.
They provide several workarounds to temporarily solve the problem of use-package but they not necessarily work for irony. [https://github.com/jwiegley/use-package/issues/533]

**Comment by Sarcasm** [comment]
thanks for letting me know, they seem quite active on the issue, maybe it's fixed now?

**Comment by mambolevis** [comment]
I tested the new "fixed"version of use-package (`use-package-20171204.1703`) and irony did not work.

On the oder hand, If I used a previos version, for example, `use-package-20171030.1428` irony works properly.

**Comment by mambolevis** [comment]
The explanation and solution of this issue can be found in the following link: 
https://github.com/jwiegley/use-package/issues/561#issuecomment-349449818
