### ISSUE TITLE
Suggestion for code navigation 

### ISSUE THREAD

**Issue by zhihuiFan** [Sarcasm/irony-mode#453]
irony-mode works for me like a charm.  and eldoc also works now.  what is your suggestion for code navigation?

looks rtags have this features,  but since some functions are duplicated with irony-mode and rtags, I don't want setup both. 

Thanks

**Comment by Sarcasm** [comment]
Irony-mode does not provide the feature, so you probably will have to setup multiple tools or find an alternative to irony-mode that provides everything.

I would suggest [rtags](https://github.com/Andersbakken/rtags/) or [cquery](https://github.com/jacobdufault/cquery), with a slight preference for the latter.
TBH, maybe it even replaces irony-mode, YMMV.

And for the future, I wish [clangd](https://clang.llvm.org/extra/clangd.html).

**Comment by zhihuiFan** [comment]
Thanks @Sarcasm,  I will try rtags.
