### ISSUE TITLE
Irony CDB cannot-load-database

### ISSUE THREAD

**Issue by innerout** [Sarcasm/irony-mode#465]
I have created the compile_commands.json with compiledb-generator.I have the repo in my pc and in a remote machine that i run my experiments.When i develop the code locally irony finds the compilation database and works perfectly.When i develop remotely irony reports the error that cannot find the compilation database.My pc has arch linux and the remote pc centos 7.I cannot understand what could cause the problem when the server is built without any errors and locally works perfect.

Irony CDB: error in compilation database: (irony-server-error cannot-load-database "failed to load compilation database from directory" "/home1/public/username/projectname/folder/")
In directory folder there is the compilation database and i am working in /home1/public/username/projectname/folder/tree/ 
Locally it finds the compilation database /home1/public/username/projectname/folder/ but remotely while the file exists, irony throws the above error.
Also i created the compilation database with intercept-build and bear but the same thing happened!
My configuration.
```elisp
(use-package company
  :ensure t
  :init(add-hook 'after-init-hook 'global-company-mode)
  :config
  (setq company-minimum-prefix-length 1)
  )

(use-package irony
  :ensure t
  :init
  (add-hook 'c++-mode-hook 'irony-mode)
  (add-hook 'c-mode-hook 'irony-mode)
  (add-hook 'objc-mode-hook 'irony-mode)
(defun my-irony-mode-hook ()                                                                                                                                                                                 
(define-key irony-mode-map [remap completion-at-point]                                                                                                                                                     
'irony-completion-at-point-async)                                                                                                                                                                        
(define-key irony-mode-map [remap complete-symbol]                                                                                                                                                         
'irony-completion-at-point-async))                                                                                                                                                                       
(add-hook 'irony-mode-hook 'my-irony-mode-hook)   
  (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
  )

(use-package company-irony
  :ensure t
  :init(eval-after-load 'company
	 '(add-to-list 'company-backends 'company-irony))
  )

(use-package company-irony-c-headers
  :ensure t
  :init(eval-after-load 'company
	 '(add-to-list
	   'company-backends '(company-irony-c-headers company-irony)))
  )

```

**Comment by innerout** [comment]
@Sarcasm I think i found the problem of the error the remote machine uses centos 7 and the path of llvm is /opt/llvm-5.0.0/ could you add this path to be checked too? My laptop has arch so i suppose irony finds in some way llvm.

**Comment by Sarcasm** [comment]
If LLVM is installed in a "non standard" way, then you have to tell cmake when you build irony-server.
You can do `cmake -DCMAKE_PREFIX_PATH=/opt/llvm-5.0.0/ ...` for example.

Let me know if that works for you.

**Comment by innerout** [comment]
Do i have to point to some executable inside the llvm-5.0.0 folder because it does not load libclang when compile_commands.json fails to load.

**Comment by Sarcasm** [comment]
I don't know what is the layout of your llvm-5.0.0 folder.
irony-server needs 3 things:
- the path to the libclang headers
- the path to the libclang library
- the path to the libclang resource directory, a directory where builtin headers are available, such as stddef.h

Usually, this can be found in a given prefix under `<prefix>/include/clang-c/Index.h`, `<prefix>/lib/libclang.so` and `<prefix>/lib/clang/$version/include`.
If the llvm-5.0.0 folder contains these files, then it should be a valid prefix.

**Comment by innerout** [comment]
My llvm folder has 4 folders bin,include,lib64 and share

**Comment by innerout** [comment]
irony-cdb-menu prints this.The error is still printed should i assume that irony runs ok and ignore the error?
Compilation Database: irony-cdb-json
Working Directory: /home/geo/folder/neokr
Compile Options:   -Wall -DSTANDALONE -Wfatal-errors

**Comment by innerout** [comment]
I created with cc args.py the clang_complete and the error does not appear anymore is it equivalent to the compilation database?Or should i try to fix the problem that made me open this issue?
