### ISSUE TITLE
Irony-Server is broken - exit code 127

### ISSUE THREAD

**Issue by tim-hilt** [Sarcasm/irony-mode#473]
When i tried to write some C-Code today, i realized that there is no completion anymore and found the error-message `irony-server is broken! /home/tim/.emacs.d/irony/bin/irony-server exited with status 127`
and after running `~/.emacs.d/irony/bin/irony-server` in the shell (bash) there was a message saying ` error while loading shared libraries: libclang.so.5: cannot open shared object file: No such file or directory`. 

After looking up my clang version, i realized, that it was updated last friday (23 March) and is now clang 6.0.0.
Is this possibly the reason for the error? Are there any workarounds?

Emacs is 25.3.1
Irony is 20180104.1109

**Comment by Sarcasm** [comment]
Rebuilding irony-server should be sufficient:

<kbd>M-x irony-install-server RET</kbd>

**Comment by tim-hilt** [comment]
Yep, that solved it! Sorry for the noise and thank you!

**Comment by MarcvdSluys** [comment]
This will happen regularly, after a system update.  Would it be useful to add this to the FAQ?
