### ISSUE TITLE
Why the difference between getting compile options and completion?

### ISSUE THREAD

**Issue by stsquad** [Sarcasm/irony-mode#480]
I'm seeing delays opening files in Emacs as the irony code falls back to manually reading the JSON as it can't find compile options. However I note in the logs the when computing completions in the same file it's fine:

    execute: Command{action=Command::GetCompileOptions, file='/home/alex/lsrc/qemu/qemu.git/hw/misc/iotkit-secctl.c', unsavedFile='', dir='/home/alex/lsrc/qemu/qemu.git/', line=0, column=0, prefix='', caseStyle='exact', flags=[], opt=off}

versus:

    execute: Command{action=Command::Complete, file='/home/alex/lsrc/qemu/qemu.git/hw/misc/iotkit-secctl.c', unsavedFile='', dir='', line=76, column=1, prefix='', caseStyle='exact', flags=['-x', 'c', '-working-directory', '/home/alex/lsrc/qemu/qemu.git/arm-softmmu', '-iquote', '/home/alex/lsrc/qemu/qemu.git/hw/misc', '-iquote', 'hw/misc', '-iquote', '/home/alex/lsrc/qemu/qemu.git/tcg', '-iquote', '/home/alex/lsrc/qemu/qemu.git/tcg/i386', '-I/home/alex/lsrc/qemu/qemu.git/linux-headers', '-I/home/alex/lsrc/qemu/qemu.git/linux-headers', '-iquote', '.', '-iquote', '/home/alex/lsrc/qemu/qemu.git', '-iquote', '/home/alex/lsrc/qemu/qemu.git/accel/tcg', '-iquote', '/home/alex/lsrc/qemu/qemu.git/include', '-I/usr/include/pixman-1', '-Werror', '-DHAS_LIBSSH2_SFTP_FSYNC', '-pthread', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-fPIE', '-DPIE', '-m64', '-mcx16', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-Wstrict-prototypes', '-Wredundant-decls', '-Wall', '-Wundef', '-Wwrite-strings', '-Wmissing-prototypes', '-fno-strict-aliasing', '-fno-common', '-fwrapv', '-Wexpansion-to-defined', '-Wendif-labels', '-Wno-shift-negative-value', '-Wno-missing-include-dirs', '-Wempty-body', '-Wnested-externs', '-Wformat-security', '-Wformat-y2k', '-Winit-self', '-Wignored-qualifiers', '-Wold-style-declaration', '-Wold-style-definition', '-Wtype-limits', '-fstack-protector-strong', '-I/usr/include/p11-kit-1', '-I/usr/include/libpng16', '-I/usr/include/spice-server', '-I/usr/include/spice-1', '-I/usr/include/capstone', '-I../linux-headers', '-iquote', '..', '-iquote', '/home/alex/lsrc/qemu/qemu.git/target/arm', '-DNEED_CPU_H', '-iquote', '/home/alex/lsrc/qemu/qemu.git/include', '-O2', '-U_FORTIFY_SOURCE', '-D_FORTIFY_SOURCE=2', '-g'], opt=off}

Now is this related to the fact the build target for the binary is in one of many subdirs? Are there different heuristics at work here? From compile_commands.json:

        "arguments": [
            "cc",
             ...

           "hw/misc/iotkit-secctl.o",
            "../hw/misc/iotkit-secctl.c"
        ],
        "directory": "/home/alex/lsrc/qemu/qemu.git/arm-softmmu",
        "file": "../hw/misc/iotkit-secctl.c"

And then its also built in:

           "hw/misc/iotkit-secctl.o",
            "../hw/misc/iotkit-secctl.c"
        ],
        "directory": "/home/alex/lsrc/qemu/qemu.git/aarch64-softmmu",
        "file": "../hw/misc/iotkit-secctl.c"

**Comment by Sarcasm** [comment]
Hi,

I'm sorry but I don't understand your issue, is it possible to reformulate it some other way?

Still, I can try to shed some lights.

The first request, GetCompileOptions, is to ask libclang if it knows the compile option for the given file.
This is the `irony-cdb-compilation-databases` database `irony-cdb-libclang` which triggers this.
This is usually done once, when the buffer is first opened.

The second request, Complete, is a completion request.
This needs the compile options, either coming from the previous GetCompileOptions, or from some other methods, registered in `irony-cdb-compilation-databases`.


I'm aware of one situation where finding the compile options is slow.
It's when there is a big compilation database, which does not contain the file.
In this case, there is an Elisp algorithm, which tries to guess a proper compile option.
The algorithm is not really good for big databases in my experience.

Personally, I have this guessing algorithm disabled in my configuration.
Instead, I expect the compilation database to be properly setup, and if it is not, I print a message to let me know about it.

```elisp
  (defun sarcasm-irony-cdb-not-found (command &rest args)
    (when (eq command 'get-compile-options)
      (message "Irony: compile options not found!")
      nil))
  (setq-default irony-cdb-compilation-databases '(irony-cdb-clang-complete
                                                  irony-cdb-libclang
                                                  sarcasm-irony-cdb-not-found))
```

One issue is the header files, which are usually not in the compilation database.
For them, I use compdb (https://github.com/Sarcasm/compdb), to generate a compilation database with the header files.

**Comment by stsquad** [comment]
Ahh so the compile options in the second request have come from the internal (elisp) json wrangling of the compile_commands.json? I'll disable the fall-back and see if that is the case.

**Comment by stsquad** [comment]
Hmm so yes the compilation database can't handle the case where:
 
       "directory": "/home/alex/lsrc/qemu/qemu.git/aarch64-softmmu",
        "file": "../hw/misc/iotkit-secctl.c"

Because /home/alex/lsrc/qemu/qemu.git/aarch64-softmmu/../hw/misc/iotkit-secctl.c is equivalent to /home/alex/lsrc/qemu/qemu.git/hw/misc/iotkit-secctl.c which is the path I opened.

**Comment by Sarcasm** [comment]
I'm not sure what you mean by can't handle?

I think LLVM does a filesystem stat to check for file equivalence, using a function like that: http://llvm.org/doxygen/namespacellvm_1_1sys_1_1fs.html#a142386357a8879fc0b5041dc2e275bf5

**Comment by Sarcasm** [comment]
I expect the libclang backend to return all the compile commands where `file` expanded against `directory` is the filesystem equivalent of the `buffer-file-name`.

However, irony-mode only use the first entry.

**Comment by stsquad** [comment]
Hmm what's the best way to debug this then because it's clearly failing to find the compile options on start-up.

**Comment by Sarcasm** [comment]
You should make sure the compilation database is found.
The easier, is to put it in a parent directory of your file/at the root of the project, `locate-dominating-file` is used.
But irony can also look up in build directories, if you tell it.

Also, from the command line, you can call irony-server directory, like this:

```
$ ~/.emacs.d/irony/bin/irony-server get-compile-options /path/to/build/directory /path/to/file.cpp
```

I'm not sure how relative paths are handled, so you may want to use absolute paths just in case.

**Comment by stsquad** [comment]
I think this is a confusion caused by QEMU's build directory structure. The is a top level build directory but many files a re-compiled multiple times for each QEMU target we build. So:

    ~/.emacs.d/irony/bin/irony-server get-compile-options (pwd)/arm-softmmu/ (pwd)/hw/misc/iotkit-secctl.c
    execute: Command{action=Command::GetCompileOptions, file='/home/alex/lsrc/qemu/qemu.git/hw/misc/iotkit-secctl.c', unsavedFile='', dir='/home/alex/lsrc/qemu/qemu.git/arm-softmmu/', line=0, column=0, prefix='', caseStyle='exact', flags=[], opt=off}
    (success . (
    (("cc" "-c" "-iquote" "/home/alex/lsrc/qemu/qemu.git/arm-softmmu/../hw/misc" "-iquote" "hw/misc" "-iquote" "/home/alex/lsrc/qemu/qemu.git/tcg" "-iquote" "/home/alex/lsrc/qemu/qemu.git/tcg/i386" "-I/home/alex/lsrc/qemu/qemu.git/linux-headers" "-I/home/alex/lsrc/qemu/qemu.git/linux-headers" "-iquote" "." "-iquote" "/home/alex/lsrc/qemu/qemu.git"
    "-iquote" "/home/alex/lsrc/qemu/qemu.git/accel/tcg" "-iquote" "/home/alex/lsrc/qemu/qemu.git/include" "-I/usr/include/pixman-1" "-Werror" "-DHAS_LIBSSH2_SFTP_FSYNC" "-pthread" "-I/usr/include/glib-2.0" "-I/usr/lib/x86_64-linux-gnu/glib-2.0/include" "-fPIE" "-DPIE" "-m64" "-mcx16" "-D_GNU_SOURCE" "-D_FILE_OFFSET_BITS=64" "-D_LARGEFILE_SOURCE" "-Wstrict-prototypes" "-Wredundant-decls" "-Wall" "-Wundef" "-Wwrite-strings" "-Wmissing-prototypes" "-fno-strict-aliasing" "-fno-common" "-fwrapv" "-Wexpansion-to-defined" "-Wendif-labels" "-Wno-shift-negative-value" "-Wno-missing-include-dirs" "-Wempty-body" "-Wnested-externs" "-Wformat-security" "-Wformat-y2k" "-Winit-self" "-Wignored-qualifiers" "-Wold-style-declaration" "-Wold-style-definition" "-Wtype-limits" "-fstack-protector-strong" "-I/usr/include/p11-kit-1" "-I/usr/include/libpng16" "-I/usr/include/spice-server" "-I/usr/include/spice-1" "-I/usr/include/capstone" "-I../linux-headers" "-iquote" ".." "-iquote" "/home/alex/lsrc/qemu/qemu.git/target/arm" "-DNEED_CPU_H" "-iquote"
    "/home/alex/lsrc/qemu/qemu.git/include" "-O2" "-U_FORTIFY_SOURCE" "-D_FORTIFY_SOURCE=2" "-g" "-o" "hw/misc/iotkit-secctl.o" "../hw/misc/iotkit-secctl.c" ) . "/home/alex/lsrc/qemu/qemu.git/arm-softmmu")
    ))

    ;;EOT

Works when I manually do a make inside arm-softmmu and create a copy of compile_commands.json in there. But if I just build at the top level:

     ~/.emacs.d/irony/bin/irony-server get-compile-options (pwd) (pwd)/hw/misc/iotkit-secctl.c
    execute: Command{action=Command::GetCompileOptions, file='/home/alex/lsrc/qemu/qemu.git/hw/misc/iotkit-secctl.c', unsavedFile='', dir='/home/alex/lsrc/qemu/qemu.git', line=0, column=0, prefix='', caseStyle='exact', flags=[], opt=off}
    (success . (
    ))

    ;;EOT

And of course it fails when I don't have a sub-compile_commands.json:

    ~/.emacs.d/irony/bin/irony-server get-compile-options (pwd)/arm-softmmu/ (pwd)/hw/misc/iotkit-secctl.c
    execute: Command{action=Command::GetCompileOptions, file='/home/alex/lsrc/qemu/qemu.git/hw/misc/iotkit-secctl.c', unsavedFile='', dir='/home/alex/lsrc/qemu/qemu.git/arm-softmmu/', line=0, column=0, prefix='', caseStyle='exact', flags=[], opt=off}
    LIBCLANG TOOLING ERROR: fixed-compilation-database: Error while opening fixed database: No such file or directory
    json-compilation-database: Error while opening JSON database: No such file or directory

    (error . (cannot-load-database "failed to load compilation database from directory" "/home/alex/lsrc/qemu/qemu.git/arm-softmmu/"))

    ;;EOT

**Comment by stsquad** [comment]
OK I think this is a bug in libclang so I'm closing this issue. I've worked around it for the time being with a script: https://github.com/stsquad/scripts/blob/master/fixup-compiledb.py
