### ISSUE TITLE
Default to 64 bit compilation

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#487]
@Sarcasm 
I wonder if we should set the default CMAKE arguments to compile the server in 64bit land. There is nothing stopping the user from doing this themselves, but needing to remember to add the "-g Win64 15 2017" flag is somewhat cumbersome (if compiling for Windows /MSVC compiler).

I will close this ticket swiftly after I hear your opinion.

**Comment by Sarcasm** [comment]
Maybe just use `irony-extra-cmake-args`:

https://github.com/Sarcasm/irony-mode/blob/2b1db096b65260fa06690a81ce4e9fca2d164cdf/irony.el#L100-L103

I would gladly accept a PR that document this in the README, or maybe it can be added to the wiki.
