### ISSUE TITLE
Post-completion expension not replacing first placeholder content

### ISSUE THREAD

**Issue by Kristaba** [Sarcasm/irony-mode#493]
First of all, thanks a lot for this amazing completion mode!

I have a weird bug with `irony-mode` using `company-irony` and `yasnipet`, and my skills in debugging emacs lisp are somewhat limited...
When selecting a possible completion with multiple placeholder (template or function parameters), the post-completion put the correct placeholder but the first one behave differently from the other.
Instead of replacing the placeholder with inserted text, it is inserted at the beginning of the placeholder content. It is a small details, but require to delete the initial content each time before to put the desired value, making completion somewhat painful.

The other placeholders behave as expected (inserting any character delete the initial placeholder text).
In addition, if there is only one placeholder, it also behaves as expected...
I notice no issue with other `yasnipet` use case (such as expanding a snipet manually, even with several placeholder with default value).

To clarify the issue, let assume I just selected `my_method` from Company completion:
```cpp
obj.my_method(unsigned int x, unsigned int y)
//            ~~~~~~~~~~~~~~ : default placeholder, active (highlighted)
```
After inserting "my_var" it ends up with the following:
```cpp
obj.my_method(my_varunsigned int x, unsigned int y)
//            ~~~~~~~~~~~~~~~~~~~~ : placeholder, active (highlighted)
```
Whereas switching to the next placeholder and inserting the same text ends up with:
```cpp
obj.my_method(unsigned int x, my_var)
//                            ~~~~~~ : placeholder, active (highlighted)
```

If someone can give me some pointers to possible causes and/or ways to debug the post-completion steps to find the issue, it would be really helpful.

**Comment by Kristaba** [comment]
Ok, we can forget about that...
I was sure to have up-to-date yasnippet, but it seems it was not the case.
Solved after updating all packages, sorry for the useless noise!

**Comment by npetrenko** [comment]
I have exactly the same issue as described

@Kristaba could you tell me if you have really resolved the issue? My yasnippet version is 0.13.0, and it seems to be the latest

**Comment by npetrenko** [comment]
I've checked out commit `1e713608682685d4a9b78519c84e3196e207c353` (july 22) from [yasnipper github repo](https://github.com/joaotavora/yasnippet/commits/master), and it seems to be working OK

**Comment by npetrenko** [comment]
Possible fix:
https://github.com/hlissner/doom-emacs/issues/650
