### ISSUE TITLE
issue with using with use-package

### ISSUE THREAD

**Issue by jstaursky** [Sarcasm/irony-mode#523]
Minor issue but took me a minute to notice
If you try and do the following with `use-package` there is an error 
```
(use-package irony
  :ensure t
  :hook (c-mode c++-mode objc-mode)
)
```
But if you do the following--which is supposed to be equivalent according to the main pg of use-package--there is no error.
```
(use-package irony
  :ensure t
  :hook ((c++-mode . irony-mode)
         (c-mode . irony-mode)
         (objc-mode . irony-mode))
)
```
Note how in one version `irony-mode` is spelled out but not with the other--I think use-package expects the package name to match with the mode name.

**Comment by Sarcasm** [comment]
Indeed, as the package is not named with the `-mode` suffix, I would expect the second form to be the correct one.

Was the 1st form recommended somewhere?

**Comment by jstaursky** [comment]
yeah take a look at the _hooks_ section of [use-package](https://github.com/jwiegley/use-package) you can see the mention of them being equivalent.
Admittedly this is a minor gripe but if a quick fix is possible, I'd prefer to use the less verbose version.

**Comment by Sarcasm** [comment]
Well, I have the feeling that for this to work, irony would have to be renamed irony-mode.
Maybe we should ask the use-package project if that is correct.

When I looked whether or not the package should be named irony or irony-mode, I concluded that it should be irony for *some* reasons, which I don't remember now.
But it is something we can see on some famous packages too, such as company or flycheck.

**Comment by jstaursky** [comment]
Was thinking that might be the case as well, but was hoping otherwise. Seems like it would be a pretty noticeable oversight to miss though, hard to think he would not have considered such a use case. Suppose I'll open an issue on use-package. Thanks
