### ISSUE TITLE
server-compilation: clang-c/Index.h can not be found

### ISSUE THREAD

**Issue by tastytea** [Sarcasm/irony-mode#530]
clang version: 7.1.0  
OS: Gentoo Linux

Since 0ae10b7eaab6f76af5685ecb41e9400f25748085 (I think), cmake can not find `clang-c/Index.h`¹. When I add `${CLANG_INCLUDE_DIRS}` to `target_include_directories(irony-server […]`, the server compiles successfully.

https://github.com/Sarcasm/irony-mode/blob/80c3ce06b6d6eadc759c65958518d651109671d2/server/src/CMakeLists.txt#L63

[irony-server_build-log.txt](https://github.com/Sarcasm/irony-mode/files/3185114/irony-server_build-log.txt)

¹ The file path is`/usr/lib/llvm/7/include/clang-c/Index.h` on my computer.

**Comment by Sarcasm** [comment]
Thank you for the report, indeed, I saw that coming:

https://github.com/Sarcasm/irony-mode/blob/0ae10b7eaab6f76af5685ecb41e9400f25748085/server/src/CMakeLists.txt#L5-L11

I will create a new imported target will all the properties properly setup I think.
Don't hesitate to ping me back on this if I forget about it, I cannot do it just now.

**Comment by Sarcasm** [comment]
I attempted a fix, let me know if that works.

**Comment by tastytea** [comment]
It works now, thanks!

**Comment by Sarcasm** [comment]
Great, thanks for the feedback!
