### ISSUE TITLE
Irony stopped working and I am unable to reinstall the irony-server afterwards

### ISSUE THREAD

**Issue by yilkalargaw** [Sarcasm/irony-mode#541]
irony-server suddenly stoped so i reinstalled irony package and when ever i  run irony-server i get the error
```
cmake -DCMAKE_INSTALL_PREFIX\=/home/ioner/.emacs.d/irony/  /home/ioner/.emacs.d/elpa/irony-20190516.2348/server && cmake --build . --use-stderr --config Release --target install
CMake Error at /lib64/cmake/clang/ClangConfig.cmake:10 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/build-irony-server-1.3.1/CMakeFiles/CMakeOutput.log".
```

**Comment by 3246251196** [comment]
Sometimes it helps to clean the build directory and start from scratch. I never use package managers in emacs and do things manually, but if I were you I would {{rm -rf /tmp/*irony*}}, remove the package from emacs (if that is possible) and just start all over again.

Failing that, you can install things manually.

**Comment by Sarcasm** [comment]
It's weird, the ClangConfig.cmake is installed, but not the LLVMConfig? Although the former depends on the latter.
What is your distribution? It could be a packaging issue, installing an unusable ClangConfig.cmake.
Maybe you need to install something like libllvm-devel?
Also, what is the version of Clang?

**Comment by yilkalargaw** [comment]
sorry for the late answer internet blockage at our country. I use fedora an I just updated to Fedora 30. before that things worked fine but after a system upgrade this happened. It may not be an irony specific issue but it seems to be the only thing affected by (showing this) behaviour

**Comment by sten0** [comment]
Hi @yilkalargaw,

Would you please confirm if v1.4.0 with Fedora 30 + regular updates and bugfixes?

Thanks,
Nicholas

**Comment by yilkalargaw** [comment]
yep it has fixed the problem
