### ISSUE TITLE
Completion: Case

### ISSUE THREAD

**Issue by 3246251196** [Sarcasm/irony-mode#544]
Reference: https://github.com/Sarcasm/irony-mode/issues/164

I just happened to install latest irony mode (but I did not test latest company-irony, but is about 6 months old only) and compile llvm/clang from source. I was testing the protected bug. 

Regardless, I now notice that latest irony mode seems to ignore case. For example,
```

class A
{
  int _displayId;
void fn();
};


A::fn()
{
  _dis[]
}
```

Completions show a lot of system things such as _DIS*.

I have looked at general customization options for company and company-irony. In company-irony Company Irony Ignore Case is turned off.

Am I missing something here or is this a feature?

Thanks.

**Comment by Sarcasm** [comment]
Did you use the latest company-irony?

There is one commit since the last release, with a fix for your issue:
- https://github.com/Sarcasm/company-irony/pull/43

**Comment by 3246251196** [comment]
@Sarcasm 
Thanks. I should have tried with latest CI, but it hardly ever changes so I didn't thank that would be the problem.

Anyway, solved.
