### ISSUE TITLE
please tag a new release (1.3.1 ftbfs with libclang-9)

### ISSUE THREAD

**Issue by sten0** [Sarcasm/irony-mode#548]
Hi @Sarcasm,

Please see attached logs that show how 1.3.1 fails to build against libclang-9, but where c7cca52 succeeds.  Given #543 I'm now more aggressively tracking the latest available stable LLVM toolchain in Debian.
[logs_for_v1.3.1_ftbfs_and_c7cca52_success.zip](https://github.com/Sarcasm/irony-mode/files/3679122/logs_for_v1.3.1_ftbfs_and_c7cca52_success.zip)

Cheers,
Nicholas

**Comment by Sarcasm** [comment]
Done, thank you for reminding me. :+1:
