### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jstaursky** [Sarcasm/irony-mode#549]
Can you make a lisp variable so that the user can set it in emacs to their system includes path and irony will start indexing those system headers that match those listed in the currently open file?

I know you can setup compilation database, set clang-additional-options, etc. but its sort of a pain to do that every time; it would be nice if indexing happened automatically in certain directories. ccls does this but I found it too heavy otherwise.

**Comment by sten0** [comment]
I wonder if it would be better to do this per-project with a `.dir-locals.el` ?
https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

**Comment by jstaursky** [comment]
Well my point is that the need to specify paths for everything is sort of tedious, especially when I just want to write something short to experiment with a library I just installed or something

**Comment by Sarcasm** [comment]
If you want indexing, I would recommend clangd + an lsp package like eglot, or ccls.
There is no point implementing a poor indexing in irony-mode, when clangd, rtags, ccls, cquery already implemented it.
