### ISSUE TITLE
Cannot find a way to install Clang libs for irony

### ISSUE THREAD

**Issue by Encorpluptit** [Sarcasm/irony-mode#551]
Hi,

I'm on Fedora 30, and like many i have problems with clang libs when trying to use the command in emacs:
irony-install-server.
I got the error message below.

I couldn't find clang libs and header via updatedb and locate.
About a week about i tried by myself to reinstall llvm and clang for getting those libs/headers.
Ended up broking my Fedora 28.
llvm, llvm-libs, clang, clang-libs are installed and i can't find anything to help me resolve this.

How can i install those ?

-*- mode: compilation; default-directory: "/tmp/build-irony-server-1.4.0/" -*-
Compilation started at Tue Nov  5 13:51:41

cmake -DCMAKE_INSTALL_PREFIX\=/home/dbernard/.emacs.d/irony/  /home/dbernard/.emacs.d/elpa/irony-20191009.2139/server && cmake --build . --use-stderr --config Release --target install
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at src/CMakeLists.txt:4 (find_package):
  By not providing "FindClang.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Clang", but
  CMake did not find one.

  Could not find a package configuration file provided by "Clang" with any of
  the following names:

    ClangConfig.cmake
    clang-config.cmake

  Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
  "Clang_DIR" to a directory containing one of the above files.  If "Clang"
  provides a separate development package or SDK, be sure it has been
  installed.

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibClang (missing: LIBCLANG_LIBRARY LIBCLANG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibClang.cmake:94 (find_package_handle_standard_args)
  src/CMakeLists.txt:28 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/build-irony-server-1.4.0/CMakeFiles/CMakeOutput.log".

Compilation exited abnormally with code 1 at Tue Nov  5 13:51:46

**Comment by Encorpluptit** [comment]
Ok I found, sorry.
After 10h trying things by myself, I found it 5 mins after posting this.

**Comment by polortiz4** [comment]
How did you fix it?
