### ISSUE TITLE
disable irony-mode completion inside comments

### ISSUE THREAD

**Issue by mambolevis** [Sarcasm/irony-mode#563]
Hi,

Could you please indicate me, how to avoid irony autocompletion inside comments?
My workaround right now is to deactivate irony when I need to write comments

Thanks

**Comment by SL-RU** [comment]
I've got the same problem also in the strings between the quotes.

**Comment by mambolevis** [comment]
I solved the issue. It was a problem with my company configuration. Now it is working fine.

**Comment by SL-RU** [comment]
> I solved the issue. It was a problem with my company configuration. Now it is working fine.

Can you say what you've fixed in the configuration?

**Comment by mambolevis** [comment]
I change my company-backends. You can customize it using:
C-h v `company-backends`
