### ISSUE TITLE
Header browser with automatic incluision

### ISSUE THREAD

**Issue by UltraBlackLinux** [Sarcasm/irony-mode#582]
Hey there,
I'm currently setting up irony-mode for C++ developement on doom emacs, but I'm facing an annoying issue:
I can't have irony-mode autocomplete stuff that I haven't yet imported. So I went ahead and installed cpp-auto-include only to discover that it's autocomplete is hardcoded and doesn't work for many headers like thread or chrono. I though noticed, that clang provides automatic including of these headers.
Apparently there is also [include what you use](https://github.com/include-what-you-use/include-what-you-use), but I have no clue (at all) how to integrate that into emacs, given that I am also pretty new to it.
So here comes my feature request: A feature to automatically include the required header files (coming along with a "header browser", that pretty much autocompletes functions that have not yet been imported. If you are unsure what I mean, head over to coc for vim, it does exactly that, but worse (since it's using clang and thus requires CMake's Export-compile-commands feature, that I seem to be able to avoid with Emacs packages)
Is this ever going to be a feature in irony-mode?
Thanks!

**Comment by Sarcasm** [comment]
Hello,

That's not going to be a feature of irony-mode.
I would recommend [clangd](https://clangd.llvm.org/), which indexes your code and can provide completion for non-included types (and is capable of auto-including the corresponding header).
