### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by skormel** [Sarcasm/irony-mode#70]
Hi,

I'm trying to get working irony but I get this error the launch cmake:

cmake .. && make -j 4
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find LibClang (missing: LibClang_LIBRARY LibClang_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibClang.cmake:35 (find_package_handle_standard_args)
  server/CMakeLists.txt:4 (find_package)

These are the packages i've got installed in my system (Debian Jessie 64 bits) (see attached image)

Can you give some clue about the error?

Thanks.
![2013-10-21_14 58 08-fullscreen](https://f.cloud.github.com/assets/5737429/1372398/c63397ea-3a50-11e3-94cb-f94965fb3d96.png)

**Comment by wildneuro** [comment]
Installing of libclang-3.5-dev solved to me

**Comment by erizhang** [comment]
I encountered same problem during execute ```irony-install-server``` on Yosemite, the quick solution is install llvm by command ```brew install llvm --with-clang```.

**Comment by chenhong805** [comment]
I get similiar error too.. I tried many things, but it doesn't work to me. ( My OS is MacOS, Yosemite )
Here is the `error` , I tried to build in shell:


$ cmake -DCMAKE_INSTALL_RPATH_USE_LINK_PATH\=ON /usr/lib/ -DCMAKE_INSTALL_PREFIX\=/Users/jinhongc/.emacs.d/irony/ /Users/jinhongc/.emacs.d/elpa/irony-20150614.1225/server && cmake --build . --use-stderr --config Release --target install
CMake Error at /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find LibClang (missing: LIBCLANG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.2.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibClang.cmake:87 (find_package_handle_standard_args)
  src/CMakeLists.txt:3 (find_package)


I can locate `libclang.dylib` in `/usr/lib`, and I linked it into /usr/lib/ :

lrwxr-xr-x    1 root  wheel       58 Jun 26 19:52 libclang.dylib@ -> /Library/Developer/CommandLineTools/usr/lib/libclang.dylib

Here is what I tried:
1. `LD_LIBRARY_PATH="/usr/lib" `
2.  added `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH\=ON /usr/lib/ `
3. `brew install llvm --with-clang`, it gave me `Warning: llvm-3.6.1 already installed`


I don't know how to customize a `hint` for `libclang`, the link https://github.com/Sarcasm/irony-mode/blob/develop/cmake/FindLibClang.cmake#L20 seems doesn't work any more, where can I find helps ? Thanks!

**Comment by 3246251196** [comment]
Can I request to reopen this. I am trying this myself on an Ubuntu 1204 system and I am getting the same issue.

**Comment by Sarcasm** [comment]
@chenhong805: see https://github.com/Sarcasm/irony-mode/wiki/Mac-OS-X-issues-and-workaround and look in the issues for Mac OS X issues, there are other more specifics out there. I cannot provide good help for Mac though, as I don't own such platform.

@3246251196: sorry but you will need to be more specific and create a new issue, this issue is old and the ways libclang is found have changed since. Create a new issue, post logs, ...

**Comment by 3246251196** [comment]
@Sarcasm 

I actually tried: https://github.com/Sarcasm/irony-mode/issues/167

And passed in directly. It worked.

I also tried this on Windows today at work without an issue at all.

**Comment by Sarcasm** [comment]
You can use the rpath otherwise, see this last item in the FAQ: https://github.com/Sarcasm/irony-mode/blob/8cf1223d4ab11c71bb01aea6f3c6183603435722/README.md#faq
