### ISSUE TITLE
irony-pp: restore functionality and check completion of header with angle brackets

### ISSUE THREAD

**Issue by Sarcasm** [Sarcasm/irony-mode#98]
The implementation may be wrong and skip non-system directories.

**Comment by hotpxl** [comment]
Hi. I don't see why this is closed. This script kinda works. I'm tweaking it right now. I have never done elisp or any lisp before so I am not finishing any soon :< . But my hopes are high. So if I could get the `irony-complete-pp-at` function working, will you be able to hook it back into `company-irony`?

**Comment by hotpxl** [comment]
FYI. I'm from the other issue in `company-irony` asking about header completion.

**Comment by Sarcasm** [comment]
@hotpxl BTW did you try https://github.com/randomphrase/company-c-headers ?

**Comment by hotpxl** [comment]
So you think I could extract user options from `irony`, and plug it into `company-c-headers`?

**Comment by Sarcasm** [comment]
Probably, that's what you will have to do anyway if you implement the whole plugin, the advantage by reusing company-c-headers is that you won't to code the rest.
